### ISSUE TITLE
Linux ISO type detection not working?

### ISSUE THREAD

**Issue by steve6375** [a1ive/grub2-filemanager#100]
This may be something I have done, but agFM no longer seems to detect the type of ISO and change the icon, etc,
loop_detect.sh for example does not seem to run?
I have removed \boot\grubfm\config from my USB drive but it still does not detect the ISO type - e.g. manjaro, Ubuntu, etc.
Can you tell me something I can do to check/fix it?

**Comment by a1ive** [comment]
manjaro
![深度截图_plasmashell_20200217192735](https://user-images.githubusercontent.com/10670106/74649992-b247b700-51bb-11ea-9b5f-ce1f58d44d6f.png)
![深度截图_plasmashell_20200217192748](https://user-images.githubusercontent.com/10670106/74650010-ba075b80-51bb-11ea-8d27-eae64805017c.png)
lubuntu
![深度截图_plasmashell_20200217192815](https://user-images.githubusercontent.com/10670106/74650038-c8ee0e00-51bb-11ea-9f85-48a9daaa2ffd.png)
![深度截图_plasmashell_20200217192821](https://user-images.githubusercontent.com/10670106/74650063-d4413980-51bb-11ea-9e6f-8e47fb351452.png)

**Comment by a1ive** [comment]
> no longer seems to detect the type of ISO and change the icon
select 'Boot ISO (Loopback)' to run iso-detection.
We don't detect it automatically because it's too slow on fat32 partition.

**Comment by steve6375** [comment]
ah - OK
I thought you would detect the type after the ISO had been selected.
Surely it would only take  second?

**Comment by steve6375** [comment]
![image](https://user-images.githubusercontent.com/1469350/74650425-9cb19d80-5179-11ea-98f3-455c7ed134e1.png)

Feb03 version detected type when ISO was selected.
Has this changed?

**Comment by a1ive** [comment]
> ![image](https://user-images.githubusercontent.com/1469350/74650425-9cb19d80-5179-11ea-98f3-455c7ed134e1.png)
> 
> Feb03 version detected type when ISO was selected.
> Has this changed?

yes.

**Comment by steve6375** [comment]
OK - please close this if you don't intend to make any changes then.
It would be nice if all CD icons in the list were changed to 'Manjaro' icon though...

**Comment by a1ive** [comment]
old version:
Boot ISO (Loopback) --> boot (loop)/boot/grub/loopback.cfg
Boot $distro From ISO --> boot scripts in $prefix/distro/$distro.sh
current:
Boot ISO (loopback.cfg) --> boot (loop)/boot/grub/loopback.cfg
Boot ISO (Loopback) --> detect and boot scripts in $prefix/distro/$distro.sh
maybe we should change the menu text to make it less confusing?

**Comment by steve6375** [comment]
thanks
