### ISSUE TITLE
Legacy mode winPE not booting

### ISSUE THREAD

**Issue by steve6375** [a1ive/grub2-filemanager#102]
ISO has \bootmgr and \boot\boot.sdi and does boot OK using Easy2Boot option.

![image](https://user-images.githubusercontent.com/1469350/74727355-f0cf8700-5238-11ea-9df3-b124ff037aac.png)
![image](https://user-images.githubusercontent.com/1469350/74726989-540ce980-5238-11ea-832b-c4419a06ffb0.png)

**Comment by steve6375** [comment]
I think issue is because of case-sensitive
![image](https://user-images.githubusercontent.com/1469350/74727814-a0a4f480-5239-11ea-8603-5fbf22073fa3.png)

better to use  bootmgr and boot.sdi from (wimboot) loopback rather than (loop)?

**Comment by a1ive** [comment]
> remove filename case sensitivity?

I have no idea how to make ntfs/iso case insensitive in grub2.

**Comment by steve6375** [comment]
I don't either.

maybe test a few cases but default to using (wimboot)

if [ -f (loop)/boot ] ; then set bootdir=boot
if [ -f (loop)/Boot ] ; then set bootdir=Boot
if [ -f (loop)/BOOT ] ; then set bootdir=BOOT
set bootsdi=(wimboot)/boot.sdi
set s=(loop)/${bootdir}/boot.sdi
if [ -f ${s} ] ; then set bootsdi=${s} ; fi
set s=(loop)/${bootdir}/Boot.sdi
if [ -f ${s} ] ; then set bootsdi=${s} ; fi
set s=(loop)/${bootdir}/BOOT.sdi
if [ -f ${s} ] ; then set bootsdi=${s} ; fi
set s=(loop)/${bootdir}/BOOT.SDI
if [ -f ${s} ] ; then set bootsdi=${s} ; fi

and same for bootmgr ?

**Comment by steve6375** [comment]
I guess same could also apply to \sources\boot.wim ??
May be \Sources or \SOURCES  or Boot.wim or BOOT.WIM ??

**Comment by a1ive** [comment]
It seems that all ms windows installation iso use lower case names.

**Comment by steve6375** [comment]
DLC WinPE ISO, HBCD PE ISO, WinPESE ISO all use \Boot  not \boot.

but they do have \sources\boot.wim (all lower case)

With WinPE ISOs and non-MS All-in-One Windows install ISOS, it will just depend on how they are authored/made.
