### ISSUE TITLE
Info - text viewer displays tabs as o

### ISSUE THREAD

**Issue by steve6375** [a1ive/grub2-filemanager#104]
The hex viewer will show tabs and other white-space bytes
so the text viewer should show tabs as spaces?

![image](https://user-images.githubusercontent.com/1469350/74936272-c2d97680-53e1-11ea-9249-be1bca832274.png)

**Comment by a1ive** [comment]
I think this problem may be caused by the font

**Comment by steve6375** [comment]
Too complex for me!
P.S. Is there a way to clear the terminal screen?
clear does not seem to work in UEFI mode
is there a grubfm_clear function ?

**Comment by a1ive** [comment]
Display for tab and other non-printable characters depends on fonts.
More Perfect DOS VGA
![21082258](https://user-images.githubusercontent.com/10670106/74992814-29af6c00-5484-11ea-9383-06b51e2f93d5.png)
Unifont Regular
![21082414](https://user-images.githubusercontent.com/10670106/74992855-3fbd2c80-5484-11ea-8a16-9fd905123830.png)

**Comment by steve6375** [comment]
I prefer unifont regular  because it prints [HT] symbol, but it is your decision...

**Comment by a1ive** [comment]
> P.S. Is there a way to clear the terminal screen?
> clear does not seem to work in UEFI mode

unset debug and then clear works ...

**Comment by steve6375** [comment]
wow! I have been trying to use clear for ages! Thanks.
