### ISSUE TITLE
Kaspersky Rescue Disk ISO does not UEFI64 boot

### ISSUE THREAD

**Issue by steve6375** [a1ive/grub2-filemanager#120]
https://support.kaspersky.com/viruses/krd18

This will MBR boot and will UEFI32 boot from the agFM - partnew\easy2boot option.

However, UEFI64 does not work.

![image](https://user-images.githubusercontent.com/1469350/75675662-76aef180-5c7f-11ea-87b9-e9801f59ecae.png)

chainloader (loop)/efi/boot/bootx64.efi  
![image](https://user-images.githubusercontent.com/1469350/75675759-abbb4400-5c7f-11ea-8f8b-7cc412ea50fa.png)

**Comment by a1ive** [comment]
```
partnew /xxx/krd,iso hd0 3
map -n /xxx/krd.iso
map -u
chainloader -b -t (cd0)/EFI/boot/krd_grub.efi
```
this works.

**Comment by steve6375** [comment]
nice! thanks.
