### ISSUE TITLE
MBR booting via wimboot to Win10 ISO not working on Lenovo Ideapad 300

### ISSUE THREAD

**Issue by steve6375** [a1ive/grub2-filemanager#122]
MBR-boot - use 'Boot Windows from ISO' on WIn10 x64 iso.

I see wimboot loading the boot.wim, I see windows loading bar for short time, all seems fine, then instead of the circle of spinning dots, I get this screen and everything has frozen.
![image](https://user-images.githubusercontent.com/1469350/76142147-d122c600-6062-11ea-8c08-67171cba9333.png)

Same thing works OK in VBox VM, so must be issue with IdeaPad 300 BIOS?

UEFI-booting to the same ISO works OK and I get to Setup.
Same ISO works using wimboot from grub4dos on same IdeaPad 300 - so grub2/wimboot/memory issue?

**Comment by a1ive** [comment]
Switch to 'text mode' (terminal_output console) first?

**Comment by steve6375** [comment]
I did same MBR boot test on my Asus Z87 PC.
It has two monitors - VGA + HDMI
It booted same Win10 ISO successfully but
VGA Monitor = Windows Setup 
HDMI Monitor = same screen as the IdeaPad 300
will check text mode...

**Comment by steve6375** [comment]
Setting text mode using F4 did not help - same issue.
If I press Alt_N then LED flashes, so I think it is a terminal output issue.
But how to fix?

**Comment by a1ive** [comment]
try `linux16 (wimboot)/wimboot pause;`

**Comment by steve6375** [comment]
oh wait, sorry, if I used text mode from agFM menu **it does work**.
(i tested from a menu entry after setting text mode and that did not work).
Maybe the command for text mode should be automatically issued before any MBR boot?

**Comment by a1ive** [comment]
https://github.com/a1ive/grub2-filemanager/blob/c949968afbcc51fb2d8165c03ff3f262021bab5f/boot/grubfm/distro/win.sh#L3-L6

try to `echo` something to make sure it really switched to text mode?

**Comment by steve6375** [comment]
OK - i copied win.sh and added several echo lines before and after wimboot commands.
It has definitely switched to text mode - whole screen is shown and not in graphics mode, but it still boots to the wrong screen!

**Comment by steve6375** [comment]
![image](https://user-images.githubusercontent.com/1469350/76142693-e6e6ba00-6067-11ea-9c00-c8a99ed58e41.png)
![image](https://user-images.githubusercontent.com/1469350/76142703-f49c3f80-6067-11ea-92c8-0675c94aa17b.png)

**Comment by steve6375** [comment]
progress_indicator ????

**Comment by steve6375** [comment]
I removed progress_indicator=1 and added
	  terminal_output console;
just before boot command, but still same issue!

**Comment by a1ive** [comment]
what if just run `linux16 (wimboot)/wimboot pause`?

**Comment by steve6375** [comment]
adding wimboot pause fixes it!

**Comment by steve6375** [comment]
![image](https://user-images.githubusercontent.com/1469350/76143176-206df400-606d-11ea-9059-08c2a582ccab.png)

**Comment by steve6375** [comment]
I fixed the issue using   console followed by clear command

```
  if [ "$grub_platform" = "pc" ];
  then
    set enable_progress_indicator=1;
    linux16 (wimboot)/wimboot;
	terminal_output console;
	clear
```

**Comment by steve6375** [comment]
actually only clear command is required.

**Comment by a1ive** [comment]
good. but why does this work?

**Comment by steve6375** [comment]
sorry, all my experiments are meaningless!
The behaviour is unpredicatable.
I did five boots
1. power on
2. Boot to agFM MBR
3. Select ISO
4. power off

results were:  
FAIL
OK
FAIL
FAIL
OK

So I don't think clear or console is doing anything!!!  It seems to be a **random** issue. It only fails approx 50% each boot.

**Comment by steve6375** [comment]
wimboot pause does NOT fix it!
It was just luck when I tested it.

**Comment by a1ive** [comment]
I have no idea...

**Comment by farukgkc** [comment]
Hi,

Tnctr - Serhat100 is commit;

initrd16 newc:bootmgr:(wimboot)/bootmgr \
               newc:bootmgr.exe:(wimboot)/bootmgr.exe \
               newc:bcd:(wimboot)/bcd \
               newc:boot.sdi:(wimboot)/boot.sdi \
               newc:null.cfg:(envblk)/null.cfg \
               newc:mount_x64.exe:(install)/mount_x64.exe \
               newc:mount_x86.exe:(install)/mount_x86.exe \
               newc:start.bat:(install)/start.bat \
               newc:winpeshl.ini:(install)/winpeshl.ini \
               newc:boot.wim:"${1}";
    else
      initrd16 newc:bootmgr:(wimboot)/bootmgr \
               newc:bootmgr.exe:(wimboot)/bootmgr.exe \
               newc:bcd:(wimboot)/bcd \
               newc:boot.sdi:(wimboot)/boot.sdi \
               newc:null.cfg:(envblk)/null.cfg \
               newc:mount_x64.exe:(install)/mount_x64.exe \
               newc:mount_x86.exe:(install)/mount_x86.exe \
               newc:start.bat:(install)/start.bat \
               newc:winpeshl.ini:(install)/winpeshl.ini \
               newc:autounattend.xml:"${2}" \
               newc:boot.wim:"${1}";
      cat ${prefix}/null.cfg;
      insmod gfxterm
      set gfxmode=1920x1080,1366x768,1024x768,800x600,auto
      set gfxpayload=1920x1080,1366x768,1024x768,800x600,auto
      terminal_output gfxterm
      boot;
  fi;

**Comment by steve6375** [comment]
null.cfg does not exist. So those lines do nothing.

But just adding terminal_output gfxterm  works 👍 

               newc:boot.wim:"${1}";
    fi;
	set gfxmode=1920x1080,1366x768,1024x768,800x600,auto
	set gfxpayload=1920x1080,1366x768,1024x768,800x600,auto
	terminal_output gfxterm
	drivemap -s hd0 hd1
    boot;

**Comment by a1ive** [comment]
> null.cfg does not exist. So those lines do nothing.
> 
> But just adding terminal_output gfxterm works 👍
> 
> ```
>            newc:boot.wim:"${1}";
> fi;
> set gfxmode=1920x1080,1366x768,1024x768,800x600,auto
> set gfxpayload=1920x1080,1366x768,1024x768,800x600,auto
> terminal_output gfxterm
> drivemap -s hd0 hd1
> boot;
> ```

or just delete `terminal_output console`?

**Comment by steve6375** [comment]
What if the user has set a text menu instead of a theme?

**Comment by steve6375** [comment]
Changing to gfx_term at this point does NOT fix the issue - it becomes random again!

function win_isoboot {
  set lang=en_US;
  #terminal_output console;
  terminal_output gfxterm
  set installiso="${grubfm_path}";

**Comment by steve6375** [comment]
It only works if 
terminal_output gfxterm is placed before the boot command.

the wimboot newc commands seems to change the mode to console when it starts to boot even if gfxterm is set beforehand.

I tried 
terminal_output gfxterm
(initrd16 ...etc.)
terminal_output gfxterm
drivemap -s hd0 hd1
boot

and this still failed

but
terminal_output console
(initrd16 ...etc.)
	set gfxmode=1920x1080,1366x768,1024x768,800x600,auto
	set gfxpayload=1920x1080,1366x768,1024x768,800x600,auto
	terminal_output gfxterm
	drivemap -s hd0 hd1
boot

8 consecutive boots and no fails!

**Comment by steve6375** [comment]
I presume gfxpayload is not needed though?

**Comment by steve6375** [comment]
This line is not required.
set gfxpayload=1920x1080,1366x768,1024x768,800x600,auto

tested with 8 consecutive boots all OK.

So best fix is

```
terminal_output console
...
(initrd16 ...etc.)
	set gfxmode=1920x1080,1366x768,1024x768,800x600,auto
	terminal_output gfxterm
	drivemap -s hd0 hd1
boot
```

**Comment by a1ive** [comment]
`set gfxmode=1920x1080,1366x768,1024x768,800x600,auto`
Is this line needed?

**Comment by steve6375** [comment]
It is not needed on my IdeaPad 300 if the Slack theme is used (gfxmode is already set to 1024x768), but maybe it would be better to include it? What if the user has set a different graphics mode  or different theme or is using text mode for the menu?

**Comment by a1ive** [comment]
> It only works if
> terminal_output gfxterm is placed before the boot command.
> 
> the wimboot newc commands seems to change the mode to console when it starts to boot even if gfxterm is set beforehand.
> 
> I tried
> 
> ```
> terminal_output gfxterm
> (initrd16 ...etc.)
> terminal_output gfxterm
> drivemap -s hd0 hd1
> boot
> ```
> 
> and this still failed!!
> 
> but this ALWAYS WORKS
> 
> ```
> terminal_output console
> (initrd16 ...etc.)
> 	set gfxmode=1920x1080,1366x768,1024x768,800x600,auto
> 	set gfxpayload=1920x1080,1366x768,1024x768,800x600,auto
> 	terminal_output gfxterm
> 	drivemap -s hd0 hd1
> boot
> ```
> 
> 8 consecutive boots and no fails!

linux16
https://github.com/a1ive/grub/blob/338757121da3a5dd7162750539558ff447c36fc3/grub-core/loader/i386/pc/linux.c#L66

**Comment by steve6375** [comment]
If I boot on a PC with VGA+HDMI monitors, then **without gfxterm** I get the agFM menu left on the HDMI monitor and Windows Setup on the VGA monitor.
But if I add the  gfxterm line, then BOTH VGA and HDMI monitors show Windows Setup.
