### ISSUE TITLE
Files with $ in filename don't work

### ISSUE THREAD

**Issue by steve6375** [a1ive/grub2-filemanager#129]
e.g.
boot$.wim

**Comment by a1ive** [comment]
Should we put dollar sign in filename?

**Comment by steve6375** [comment]
it is commonly used for E2B files so that it is listed first in the menu (alphabetically sorted)
e.g. $_boot.wim
Is it a big problem?  Not fixed by using ' instead of " somewhere?

**Comment by a1ive** [comment]
I think `"\$"` works, but this will change the length of the filename string, which will cause much trouble.

**Comment by steve6375** [comment]
$_boot.wim is not even listed in the agFM menu.
_$boot.wim is listed but doesnt run

**Comment by steve6375** [comment]
OK - maybe we just say it is a known limitation of agFM?  $ is not allowed in filenames?

**Comment by a1ive** [comment]
OK.
Maybe you can use `!` to replace `$`?
