### ISSUE TITLE
enhancement: add play command

### ISSUE THREAD

**Issue by steve6375** [a1ive/grub2-filemanager#132]
This is trivial, but is it possible to support the grub2 play command (both Legacy and UEFI)?
If not, don't worry.

**Comment by a1ive** [comment]
Yes, but why?

**Comment by steve6375** [comment]
to make an audible signal to user. e.g. if run an OS install from USB drive and then it reboots back to the USB drive afterwards, the notes\tune will signal that the system has rebooted and ready for next operation.
Use can add notes\tune using config file if they want to.

**Comment by a1ive** [comment]
gfxmenu module can also play tunes.
```
export grub_sound_speed=110;
export grub_sound_start="220 277 330 440 185 220 277 370 294 370 440 587 330 415 494 659";
export grub_sound_select="0";

menuentry "FM" {
  unset grub_sound_speed;
  grubfm;
}

  ...
```

**Comment by steve6375** [comment]
If I add this to config - it plays a continuous note and no timeout (stopped)
when I run FM menu it then plays tune and timeout starts
???

**Comment by a1ive** [comment]
???
why config?
add it to your main menu.cfg

**Comment by steve6375** [comment]
config -> startup_menu.txt

I added it to startup_menu.txt

On first boot I get continuous note and timeout does not run until I press a key

**Comment by steve6375** [comment]
works correctly if I re-run the startup_menu.txt from within agFM. So problem is only on first boot. Both UEIF and MBR affected.

**Comment by steve6375** [comment]
Issue is caused by these lines
```
terminal_input at_keyboard;
keymap "(${user})/boot/grubfm/keyboard_maps/United Kingdom gb.gkb"
```
works correctly if I comment them out!

**Comment by steve6375** [comment]
I added these lines instead (UEFI64)
```
insmod ($user)/play.mod
play 1750 523 1 392 1 523 1 659 1 784 1 1047 1 784 1 415 1 523 1 622 1 831 1 622 1 831 1 1046 1 1244 1 1661 1 1244 1 466 1 587 1 698 1 932 1 1195 1 1397 1 1865 1 1397 1

```

It has a similar affect - on first boot, tune plays but 5 second countdown timeout is frozen. Have to press a key to continue with countdown and use menu.
It is the 
terminal_input at_keyboard 
which causes the problem
Even just pressing the CTRL key is enough to start the countdown timer - so it seems to need an interrupt?
Must use real system to test as not the same in a VBox (no PC speaker).

**Comment by a1ive** [comment]
I don't know how to fix it.
