### ISSUE TITLE
query: Why is not used original version wimboot ? What reasons?

### ISSUE THREAD

**Issue by dialmak** [a1ive/grub2-filemanager#133]
Sorry for the bad english ...
Why is not used original version wimboot ? What reasons?
And why not allowed use the answer file for Windows distributions with 32 and 64 versions together? This was unexpected...

**Comment by steve6375** [comment]
UEFi or Legacy\MBR Wimboot?

**Comment by dialmak** [comment]
Hmm. In my opinion they are identical.
Let's look from the other side.
Example 
- Original http://git.ipxe.org/releases/wimboot/wimboot-latest.zip 
https://i.vgy.me/thByyR.png
https://i.vgy.me/lHZDrz.png
- Version in last grub2-filemanager
https://i.vgy.me/L8D921.png

**Comment by steve6375** [comment]
> And why not allowed use the answer file for Windows distributions with 32 and 64 versions together? This was unexpected...

Please give step-by-step details how I can reproduce this issue? What ISO? What is location if ISO and XML file?

**Comment by dialmak** [comment]
In general, an answer file is supported.
But in the case of creating an ISO file for with x86/x64 together through the utility Microsoft  _MediaCreationTool1909.exe_, this does not work.
The reason is visible in the file _start.bat_ https://i.vgy.me/PoB4u3.png

**Comment by steve6375** [comment]
Where is the install file located in your ISO?

It works on my dual ISO
![image](https://user-images.githubusercontent.com/1469350/76563463-5e20b180-649f-11ea-83c2-32b56d4f7cb5.png)

**Comment by dialmak** [comment]
Hmm. It works of course, but the answer file autounattend.xml does not apply!!!

**Comment by dialmak** [comment]
There is one more problem. If you try to install Windows for BIOS from a USB flash drive (MBR), then on some computers the bootloader will be installed on the USB flash drive. That is, disk swaping is required.
I did not check for EFI, there most likely it is optional ..

**Comment by steve6375** [comment]
Do you have latest version? That issue was reported and fixed.
Issue 121
https://github.com/a1ive/grub2-filemanager/issues/121

**Comment by dialmak** [comment]
1. autounattend.xml does not apply for Windows distributions with 32 and 64 versions together 
 through the utility Microsoft MediaCreationTool1909.exe
2. Windows install, but the bootloader is installed on a flash (active partition MBR).

**Comment by dialmak** [comment]
In G4D this is solved in one line
_if "%@root:~1,3%"=="hd0" && map (hd0) (hd1) && map (hd1) (hd0) && map --rehook_

**Comment by steve6375** [comment]
drivemap -s hd0 hd1
is used - see issue 121
Why does this not work for you?

**Comment by dialmak** [comment]
I’ll check again. And why are there no conditions? This is strange...

**Comment by a1ive** [comment]
> Why is not used original version wimboot ? What reasons?

UEFI?
original wimboot only supports iPXE.
1) It doesn't use "EFI handover protocol" so it can't recognize the initrdfs created by grub2 or syslinux.
2) It fails (BCD 0xc000000f ERROR) if UEFI Secure Boot is enabled.
3) Using it to boot a WIM consumes more memory (2x) than booting WIM using bootmgfw.efi.

You need to apply [this patch](https://github.com/a1ive/grub/blob/master/grub-core/map/wimboot/linuxefi.patch) to wimboot and then it will work under UEFI grub2.
