### ISSUE TITLE
autounattend.xml does not apply for Windows distributions with 32 and 64 versions together

### ISSUE THREAD

**Issue by dialmak** [a1ive/grub2-filemanager#134]
autounattend.xml does not apply for Windows distributions with 32 and 64 versions together
through the utility Microsoft MediaCreationTool1909.exe
The reason is visible in the file start.bat https://i.vgy.me/PoB4u3.png

**Comment by steve6375** [comment]
The bat file also does not work if the ISO contains .swm files instead of .wim or .esd files.

**Comment by a1ive** [comment]
> The bat file also does not work if the ISO contains .swm files instead of .wim or .esd files.

I don't have a .swm ISO.Could you please modify the bat and test it?

**Comment by steve6375** [comment]
It is difficult for me to modify the batch file.
Would it hurt if you add test for *.swm files? I can then test.
I test for install.* in my batch files for E2B.

**Comment by a1ive** [comment]
> It is difficult for me to modify the batch file.
> Would it hurt if you add test for
> 
> > .swm
> 
> files? I can then test.
> I test for
> 
> > install.*
> 
> in my batch files for E2B.

[grubfmx64.efi.zip](https://github.com/a1ive/grub2-filemanager/files/4328619/grubfmx64.efi.zip)
[install.gz](https://github.com/a1ive/grub2-filemanager/files/4328621/install.gz)

**Comment by steve6375** [comment]
Looks good...

Current release with ISO+install.swm
![image](https://user-images.githubusercontent.com/1469350/76608267-3d8f4080-650d-11ea-8cd6-0cc4de392dbe.png)

test grubfm64.efi.zip
![image](https://user-images.githubusercontent.com/1469350/76608326-57308800-650d-11ea-9569-83be7850a823.png)

**Comment by steve6375** [comment]
ISOs with .swm files can be made using SplitWinISO.exe from the MPI Tool Kit of Easy2Boot.
![image](https://user-images.githubusercontent.com/1469350/76608548-b7bfc500-650d-11ea-9d94-a51a0a835d31.png)
Use Convert button.
