### ISSUE TITLE
Files with all uppercase letters shown as lowercase

### ISSUE THREAD

**Issue by steve6375** [a1ive/grub2-filemanager#135]
FAT32 filesystem
![image](https://user-images.githubusercontent.com/1469350/76679371-dab6ab80-65d7-11ea-9a39-dbb2af757721.png)
![image](https://user-images.githubusercontent.com/1469350/76679446-73e5c200-65d8-11ea-818b-34d4556a9ee4.png)

**Comment by a1ive** [comment]
It's a bug in Windows.
File rename doesn't always work.You have to create a new file or make a
copy.

**Comment by steve6375** [comment]
Even when creating a new file?
![image](https://user-images.githubusercontent.com/1469350/76679704-5d406a80-65da-11ea-9672-6c12e7a15248.png)

**Comment by steve6375** [comment]
![image](https://user-images.githubusercontent.com/1469350/76680031-2ddf2d00-65dd-11ea-9cfd-2dc481f23075.png)
FAT entry is in capitals

**Comment by steve6375** [comment]
Ok if long filename
![image](https://user-images.githubusercontent.com/1469350/76680078-99c19580-65dd-11ea-92aa-89dd6109ba69.png)

**Comment by a1ive** [comment]
![深度截图_选择区域_20200314182825](https://user-images.githubusercontent.com/10670106/76680405-2b072b00-6623-11ea-9d76-12a15db5ab86.png)
![深度截图_plasmashell_20200314183024](https://user-images.githubusercontent.com/10670106/76680407-2e9ab200-6623-11ea-83bf-111e14bcee53.png)
![深度截图_选择区域_20200314183049](https://user-images.githubusercontent.com/10670106/76680409-30fd0c00-6623-11ea-81cb-764bffa2647f.png)

**Comment by steve6375** [comment]
So linux and grub2 lie - Windows tells the truth?

**Comment by steve6375** [comment]
Seems the default in many OS's is to use lowercase for shortnames on FAT volumes
http://lkml.iu.edu/hypermail/linux/kernel/0503.3/1450.html

**Comment by steve6375** [comment]
I guess it may break case-sensitive menus already created by other users if this was changed to 'mixed' (as is correct)!

**Comment by a1ive** [comment]
[grubfmx64.efi.zip](https://github.com/a1ive/grub2-filemanager/files/4332603/grubfmx64.efi.zip)

**Comment by a1ive** [comment]
![深度截图_选择区域_20200314185935](https://user-images.githubusercontent.com/10670106/76680792-c221b200-6626-11ea-807d-fb57a7f4912a.png)
![深度截图_选择区域_20200314185957](https://user-images.githubusercontent.com/10670106/76680796-c64dcf80-6626-11ea-990d-608d7597d738.png)
![深度截图_选择区域_20200314190142](https://user-images.githubusercontent.com/10670106/76680797-c948c000-6626-11ea-870b-40f4740c04a0.png)
![深度截图_选择区域_20200314190159](https://user-images.githubusercontent.com/10670106/76680799-ccdc4700-6626-11ea-9d7f-dc4d4f51cbc1.png)
Now dirname is UPPERCASE in grub. Strange.

**Comment by steve6375** [comment]
If dir is 8.3 then will be uppercase.
Will changing behaviour cause issues with current user menus?

**Comment by a1ive** [comment]
no. fat is always case-insensitive.

**Comment by steve6375** [comment]
OK. so should not cause any issues. So OK to commit change?

**Comment by a1ive** [comment]
I don't think so.
This solution is not perfect (dirname).
