### ISSUE TITLE
引导Android x86镜像包

### ISSUE THREAD

**Issue by ljx129** [a1ive/grub2-filemanager#14]
可否能在Android x86运行起来后，把该安装的应用软件以及一些配置文件都安装好，然后把这个系统打包成ISO镜像，类似Windows ghost镜像。然后通过grub引导这个ISO呢？请问这个问题有办法解决吗？

**Comment by a1ive** [comment]
用unsquashfs解压*.sfs，修改之后再用mksquashfs打包。

**Comment by ljx129** [comment]
楼主你的想法我还没get到。
我现在想用这两个命令完成打包镜像和解压镜像，
打包镜像：
        dd bs=512  count=fdisk命令中最大的end数+1   if=/dev/sda | gzip  -9  >/ghost.img.gz
镜像还原：
gzip  -dc  /ghost.img.gz  | dd  of=/dev/sda
但是在Android x86平台上会提示：
dd: /dev/sda: No such file or directory
我还在查原因呢，/dev/sda就是硬盘，肯定会存在的，我用debug模式进去是可以看见的。

**Comment by jonathanhzs** [comment]
先搞一个data.img，装好APP，做好所有的设置，然后把没用的删除，留下需要的打包到system里，利用initrd加载到内存中运行。思路是这样的，加油。
