### ISSUE TITLE
sbpolicy causing BIOS corruption?

### ISSUE THREAD

**Issue by steve6375** [a1ive/grub2-filemanager#140]
A user reported a severe problem when booting agFM using the Insecure EFI shim as (/EFI/BOOT/BOOTX64.EFI) and then running
sbpolicy --install from /boot/grub/grub.cfg before loading grubfmx64.efi.

He has a Lenovo B40 30 laptop (not PC). After UEFI64 booting from an E2B+agFM flash drive, he now cannot get into the BIOS Setup menu. It also will not boot to grubfmx64.efi. It will still boot to Windows from the hard disk however.

Is it possible that some UEFI patching in sbpolicy or agFM has caused this?

I was wondering if it is possible to configure the /boot/grub/grub.cfg file so that it could detect if it was being booted in Secure Boot mode and ask the user if they wanted to install sbpolicy --install at their own risk?
Is this possible? 
Also the read command does not work at this point (no modules loaded?).

Also, my /boot/grub/grub.cfg file currently has:

```
insmod /boot/grub/sbpolicy.mod
sbpolicy --install
chainloader /grubfmx64.efi
boot
```

but I notice that the F4 'Install override security policy' has... 

![image](https://user-images.githubusercontent.com/1469350/77245409-4e7b3880-6c16-11ea-8b8a-d7a735aff41a.png)

are these extra commands needed in grub.cfg or does grubfm always run them anyway?

**Comment by steve6375** [comment]
I have added some modules and my /boot/grub/grub.cfg is now...
```
# fde_ld.efi: https://habr.com/ru/post/446072/
# sbpolicy.mod: https://github.com/a1ive/grub/blob/master/grub-core/commands/efi/sbpolicy.c
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

insmod /boot/grub/sbpolicy.mod

#use standard grub modules (not agFM modules)
insmod /boot/grub/read.mod
insmod /boot/grub/echo.mod
insmod /boot/grub/sleep.mod

echo Patch UEFI64 firmware for Secure Boot?
echo -e ======================================
echo
echo WARNING: This patch may permanently corrupt the firmware on some older UEFI systems!
echo
echo You can install this patch at your own risk, 
echo or else disable Secure Boot in the BIOS setup menu and reboot.
echo
echo Serious UEFI BIOS corruption has been observed on:
echo   Lenovo B40 30 Notebook
echo
echo Type 1 + ENTER to install the UEFI Secure Boot patch.
read ask
echo
if [ "${ask}" = "1" ]; then sbpolicy --install ; sleep 3 ; fi
clear
echo
chainloader /grubfmx64.efi
boot
echo ERROR: Failed to load agFM!
sleep 5
exit
```
Is there a way to only prompt the user if they have booted in Secure Boot mode?

**Comment by a1ive** [comment]
> He has a Lenovo B40 30 laptop (not PC). After UEFI64 booting from an E2B+agFM flash drive, he now cannot get into the BIOS Setup menu. It also will not boot to grubfmx64.efi. It will still boot to Windows from the hard disk however.
> 
> Is it possible that some UEFI patching in sbpolicy or agFM has caused this?

I'm sure that sbpolicy will not change firmware permanently.
I think it's Kaspersky's loader.

**Comment by steve6375** [comment]
Not much I can do about that then as its the first EFI file to be loaded...

**Comment by a1ive** [comment]
use [Super-UEFIinSecureBoot-Disk](https://github.com/ValdikSS/Super-UEFIinSecureBoot-Disk) to bypass sb. This method is "legal" and won't banned by M$. besides it uses Red Hat's shim which is open source software.

**Comment by steve6375** [comment]
It uses Mok Manager which doesn't work on a lot of systems.

**Comment by a1ive** [comment]
Upgrade it to latest version or try "enroll hash" instead of "enroll key".

**Comment by steve6375** [comment]
P.S. Did you see I said 'he now **cannot get into the BIOS Setup menu**.'

That it - he cannot now use the BIOS Setup menu at all - he just gets a black screen and it won't go to the BIOS menu.  i.e. The firmware has been corrupted somehow (probably UEFI NVRAM??).

**Comment by a1ive** [comment]
> P.S. Did you see I said 'he now **cannot get into the BIOS Setup menu**.'
> 
> That is - he cannot now use the BIOS Setup menu at all - he just gets a black screen and it won't go to the BIOS menu. i.e. The firmware has been corrupted somehow (probably UEFI NVRAM??).

Yes. shim / mokmanager or other sb loaders will write to NVRAM (UEFI Variables / Mok keys are stored in NVRAM).grub2 NEVER write to NVRAM unless you use "setenv" command.

**Comment by a1ive** [comment]
> Is there a way to only prompt the user if they have booted in Secure Boot mode?

You can use "getenv" module, but I'm not sure if it works under Kaspersky's GRUB v2.02.
See init.sh
```
getenv -t uint8 SecureBoot grub_secureboot;
if [ "${grub_secureboot}" = "0" ];
then
    export grub_secureboot="Disabled";
else
    export grub_secureboot="Enabled";
fi;
```

**Comment by steve6375** [comment]
If you are sure that sbpolicy cannot update the UEFI firmware then I do not need to ask the user. The damage will already have been done by the BOOTX64.EFI shim, won't it?

**Comment by a1ive** [comment]
> If you are sure that sbpolicy cannot update the UEFI firmware then I do not need to ask the user. The damage will already have been done by the BOOTX64.EFI shim, won't it?

Yes. but Kaspersky's BOOTX64.EFI shim is closed source, so we can't report it to Fedora :cry: .
Maybe he could clean the NVRAM under windows?

**Comment by steve6375** [comment]
The user with the corrupted BIOS got back to me:
` It was an issue with the linux kernel. If you remember during release of Ubuntu 17.10 there was an issue of bios corruption ? it was a similar issue. Though it happened with the latest linux kernel 5.3.0.40`

So not a problem with grub2/grubfm !
