### ISSUE TITLE
Add user-defined hotkeys

### ISSUE THREAD

**Issue by steve6375** [a1ive/grub2-filemanager#141]
I would like to add user-defined hotkeys into the agFM menu system.

For instance
F8 to reload agFM and config file
F9 to reboot
F10 to Power off

so it works in the main agFM File Manager menu.

e.g. add a hiddentry with a --hotkey defined ?

How can I do this?

**Comment by a1ive** [comment]
not supported.

**Comment by steve6375** [comment]
Could you not add a 

`source (${user})/boot/grubfg/config_fm`

line to the main grubfm menu ?

One main issue if that if a user selects a file which does not boot correctly - the theme is lost and the menu is shown in text mode.

It would be nice to have a hotkey which would reload the main file (grubfmx64.efi or bootiax64.efi or grubfm.iso) - e.g. F8 same as in Easy2Boot. Also add other hiddenmenu entries using the config_fm file too.

**Comment by a1ive** [comment]
> if a user selects a file which does not boot correctly - the theme is lost and the menu is shown in text mode.

and then you should reboot to boot another file.otherwise will cause memory leak.

**Comment by steve6375** [comment]
but quicker to just reload grub2 and try that first.
Some systems (servers) take many minutes to reboot.

**Comment by a1ive** [comment]
may not boot correctly.

**Comment by steve6375** [comment]
It also might boot correctly and save having to reboot and wait 3 minutes for POST on a server.... ;-)

**Comment by a1ive** [comment]
Why not press [F4] and [R]?

**Comment by steve6375** [comment]
Sometimes works - but how is the use to know?
An F8 hotkey to 'reload' menu system would be useful?
maybe  chainloader (memdisk)/boot/grubfm/init.sh ???
or facility for user to add a config_fm file so it is up to the user to add hotkeys using hiddenentry menu ?

**Comment by a1ive** [comment]
> An F8 hotkey to 'reload' menu system would be useful?
maybe chainloader (memdisk)/boot/grubfm/init.sh ???
or facility for user to add a config_fm file so it is up to the user to add hotkeys using hiddenentry menu ?

no.I won't add support for user-defined hotkeys.

**Comment by steve6375** [comment]
OK, thanks for your help anyway.
I have made donation.
Thanks for a great project 💯

**Comment by a1ive** [comment]
Thanks for your donation.
