### ISSUE TITLE
UEFI32 hexdump not working?

### ISSUE THREAD

**Issue by steve6375** [a1ive/grub2-filemanager#143]
![image](https://user-images.githubusercontent.com/1469350/77647901-2580dd80-6f5f-11ea-9f2f-f2a93bbc02df.png)

**Comment by steve6375** [comment]
Using VBox to test.

**Comment by steve6375** [comment]
I am not sure that dd works either???

**Comment by a1ive** [comment]
![深度截图_选择区域_20200327101548](https://user-images.githubusercontent.com/10670106/77714420-f4161980-7013-11ea-925b-312f7ea77d80.png)

**Comment by steve6375** [comment]
![image](https://user-images.githubusercontent.com/1469350/77739171-fc1c8c00-7008-11ea-8626-8779596ca438.png)
![image](https://user-images.githubusercontent.com/1469350/77739240-16ef0080-7009-11ea-90dd-dd34a80a5bc0.png)
![image](https://user-images.githubusercontent.com/1469350/77739322-37b75600-7009-11ea-99d8-2e9191fd71ca.png)

????

**Comment by steve6375** [comment]
Any ideas? Maybe the cause is also why some people report hexdump is not working on some real UEFI64 systems too?
I am using VBox5+VMUB to test (I do not have a UEFI32 system).

**Comment by steve6375** [comment]
If I boot to Clover UEFI32 from MBR boot
Then hexdump works
![image](https://user-images.githubusercontent.com/1469350/77750642-14e26d00-701c-11ea-81d7-0dbd11e4617c.png)

So issue with VBox 5 ??

**Comment by a1ive** [comment]
> So issue with VBox 5 ??

but it works on my vbox?

**Comment by steve6375** [comment]
What VBox do you have and what settings?

**Comment by a1ive** [comment]
Host: Manjaro 19.0 (kernel 4.19)
VBox: v6.1.4
VM: Windows 10 (32-bit)
![深度截图_plasmashell_20200327192437](https://user-images.githubusercontent.com/10670106/77751418-9fe55680-7060-11ea-8f58-c5118f5b91d8.png)

**Comment by steve6375** [comment]
doh! Sorry. My mistake!! I had  hd0 as empty disk vdi.
Sorry to bother you.
