### ISSUE TITLE
F4 - Install override security policy

### ISSUE THREAD

**Issue by steve6375** [a1ive/grub2-filemanager#144]
Hi
If I secure UEFI64 boot - F1 shows Secure Boot is enabled. (I can boot to MS Windows).
But the 'Install override security policy' option in the F4 menu is displayed.
If I run this, it says it is enabling secure boot - after this the 'install override security policy' entry is no longer present.

Please can you explain what this option does?
Is it run by default when grubfm boots?
Why is it listed in the F4 options when it is already in Secure Boot mode?
Is the fucksb command documented anywhere?
When and how should this 'Install override security policy' be used?
Thanks, Steve.

**Comment by a1ive** [comment]
1) shim -> MokManager (enroll hash/key) -> preloader (from Super UEFIinSecureBoot Disk) ->
    grubfmx64.efi -> chainloader xxx.unsigned.efi (**ok**)
preloader will install custom sb policy to allow loading unsigned efi, no need to run this entry in grubfm.
2) Kaspersky's shim -> Kaspersky's grub2 -> insmod sbpolicy ->
    grubfmx64.efi -> chainloader xxx.unsigned.efi (ok)
sbpolicy.mod (in /boot/grub/) will install custom sb policy to allow loading unsigned efi, no need to run this entry in grubfm.
3) shim -> MokManager (enroll hash/key) -> grubfmx64.efi -> chainloader xxx.unsigned.efi (**fail**)
Booting unsigned efi will be **blocked** by firmware, you have to run this entry and then you can boot unsigned efi.

**Comment by a1ive** [comment]
"SecureBoot" is a UEFI variable, it will be set to "1" by firmware when secure booting.
bootmgfw.efi will check this UEFI variable and will refuse booting from wimboot virtual disk if sb enabled.
This variable is read-only, and we have to lie to bootmgfw.efi (or other efi loader) make it believe that secure boot is not enabled.
in patch https://github.com/a1ive/grub/commit/729aebb4fd72143bc5603b123917602514fdacc5 ,this trick will be executed automatically during wimboot ,but if you want to lie to other efi loaders, you need to run `fucksb --install` and `fucksb --off`.

**Comment by steve6375** [comment]
Thanks for the explanation

So F1 shows
Secure Boot: Enabled
![image](https://user-images.githubusercontent.com/1469350/77749390-dc419400-7019-11ea-8831-60ee29881b02.png)

(even if booting from VBox which is not in Secure Boot mode??)

Then I use F4 - Install override security policy

But F1 still shows
Secure Boot: Enabled

but the 'Install override security policy' entry is no longer displayed ???

```
if [ "${grub_platform}" = "efi" ];
then
  getenv -t uint8 SecureBoot secureboot;
  if [ "${secureboot}" != "0" ];
  then
    menuentry $"Install override security policy" --class uefi {
      sbpolicy --install;
      fucksb -i -b;
      fucksb --off;
      sleep 2;
      configfile ${prefix}/settings.sh;
    }
  fi;
fi;
```

**Comment by a1ive** [comment]
> (even if booting from VBox which is not in Secure Boot mode??)

should be fixed (https://github.com/a1ive/grub2-filemanager/commit/b875326222ca28e35ea3b2e152df60caec71f26f)

**Comment by steve6375** [comment]
thanks
