### ISSUE TITLE
Invalid partition table After partnew

### ISSUE THREAD

**Issue by wimbrts** [a1ive/grub2-filemanager#145]
After using partnew for Linux ISO then Reboot from USB in BIOS mode results in Invalid partition table.

Inspection of the partition table in TinyHexer shows that 4th entry is not empty
and the MBR Boot Code has changed in 4 bytes at offset 0x1c that were originally FB B9 04 00

![Invalid_PT-2020-03-29_065634](https://user-images.githubusercontent.com/38395846/77842567-0ae37a00-7194-11ea-97b3-9a811b6c7f6d.jpg)

**Comment by steve6375** [comment]
Yes. 0x1c-0x1ff are getting written to when MBR partnew is run.
BUG!
![image](https://user-images.githubusercontent.com/1469350/77844247-08d1e900-719d-11ea-8206-98a10ce3eee1.png)

**Comment by wimbrts** [comment]
Thanks Steve for confirming the issue.

**Comment by steve6375** [comment]
Also partnew in UEFI64
![image](https://user-images.githubusercontent.com/1469350/77844519-649d7180-719f-11ea-8671-3da6e698e7c1.png)

**Comment by steve6375** [comment]
4th table entry seems OK?
partnew in agFM will add entry #4 with type of 0.

**Comment by wimbrts** [comment]
In my case also 4 bytes at offset 0x1C are equal to 4 bytes at offset 0x1F6 in 4th entry of partition table 
See TinyHexer screenshot of Invalid partition table as given above.

**Comment by steve6375** [comment]
Yes - but why is partition 4  table (16 bytes) invalid?

**Comment by steve6375** [comment]
I think corruption of 0x1c is causing the boot code to report invalid partition.  Ptn #4 is actually OK.
http://starman.vertcomp.com/asm/mbr/W7MBR.htm

**Comment by wimbrts** [comment]
Sure I agree that the 4 byte patch at 0x1c is most likely causing the Invalid partition table error

**Comment by steve6375** [comment]
@a1ve - is the partnew code trying to change the BPB Reserved Sectors value?

**Comment by a1ive** [comment]
yes. code are taken from grub4dos.

**Comment by steve6375** [comment]
It needs to change the VBR/PBR sector, not the MBR sector?

**Comment by wimbrts** [comment]
Indeed the MBR Boot code should not change.
Patch is applied to wrong sector .....

**Comment by steve6375** [comment]
But 0x1c-0x1f needs to be written to PBR (which has same LBA address)???

**Comment by steve6375** [comment]
e.g. if  VBR is at  LBA1122344
then bytes 0x1c to 0x1F at LBA11223344 needs to be changed to 44 33 22 11.

**Comment by steve6375** [comment]
Grub4dos code
Get start of partition
Check filesystem type
If FAT then update reserved sectors,



```
    
      /* Read the first sector.  */
      if (! rawread (current_drive, new_start, 0, SECTOR_SIZE, (unsigned long long)(unsigned int)mbr, 0xedde0d90))
        return 0;

#define	BS	((struct master_and_dos_boot_sector *)mbr)
      /* try to find out the filesystem type */
      if (BS->boot_signature == 0xAA55 && ! probe_bpb(BS))
      {
	if ((new_type & 0xFFFFFFEF) == 0)	/* auto filesystem type */
	{
		new_type |= 
			filesystem_type == 1 ? 0x0E /* FAT12 */ :
			filesystem_type == 2 ? 0x0E /* FAT16 */ :
			filesystem_type == 3 ? 0x0C /* FAT32 */ :
			filesystem_type == 4 ? 0x07 /* NTFS */  :
			filesystem_type == 6 ? 0x07 /* exFAT */ :
			/*filesystem_type == 5 ?*/ 0x83 /* EXT2 */;
		if (filesystem_type == 5)
			new_type = 0x83; /* EXT2 */
	}
	printf_debug0 ("%s BPB found %s the leading 0xEB (jmp). Hidden sectors=0x%X\n",
		(filesystem_type == 1 ? "FAT12" :
		filesystem_type == 2 ? "FAT16" :
		filesystem_type == 3 ? "FAT32" :
		filesystem_type == 4 ? "NTFS"  :
		filesystem_type == 6 ? "exFAT" :
		/*filesystem_type == 5 ?*/ "EXT2 GRLDR"),
		(BS->dummy1[0] == (char)0xEB ? "with" : "but WITHOUT"),
		BS->hidden_sectors);
	if (BS->hidden_sectors != new_start)
	{
	    printf_debug0 ("Changing hidden sectors 0x%X to 0x%lX... ", BS->hidden_sectors, (unsigned long long)new_start);
	    BS->hidden_sectors = new_start;
	    /* Write back/update the boot sector.  */
	    if (! rawwrite (current_drive, new_start, (unsigned long long)(unsigned int)mbr))
	    {
		printf_debug0 ("failure.\n");
	        return 0;
	    } else {
		printf_debug0 ("success.\n");
	    }
	}
      }
```

**Comment by steve6375** [comment]
Maybe add command option to update BPB 0x1c-0x1f

e.g.
partnew --update-hidden

?

**Comment by steve6375** [comment]
Reserved Sectors must be updated so a partition is bootable when added using partnew.

Maybe a test could be used to detect type?

loopback tst "${grubfm_file}"
probe --set=fs --fs (tst)
loopback -d tst

**Comment by steve6375** [comment]
Any fix yet please?

**Comment by a1ive** [comment]
> Grub4dos code
> Get start of partition
> Check filesystem type
> If FAT then update reserved sectors,
> 
> ```
>     
>       /* Read the first sector.  */
>       if (! rawread (current_drive, new_start, 0, SECTOR_SIZE, (unsigned long long)(unsigned int)mbr, 0xedde0d90))
>         return 0;
> 
> #define	BS	((struct master_and_dos_boot_sector *)mbr)
>       /* try to find out the filesystem type */
>       if (BS->boot_signature == 0xAA55 && ! probe_bpb(BS))
>       {
> 	if ((new_type & 0xFFFFFFEF) == 0)	/* auto filesystem type */
> 	{
> 		new_type |= 
> 			filesystem_type == 1 ? 0x0E /* FAT12 */ :
> 			filesystem_type == 2 ? 0x0E /* FAT16 */ :
> 			filesystem_type == 3 ? 0x0C /* FAT32 */ :
> 			filesystem_type == 4 ? 0x07 /* NTFS */  :
> 			filesystem_type == 6 ? 0x07 /* exFAT */ :
> 			/*filesystem_type == 5 ?*/ 0x83 /* EXT2 */;
> 		if (filesystem_type == 5)
> 			new_type = 0x83; /* EXT2 */
> 	}
> 	printf_debug0 ("%s BPB found %s the leading 0xEB (jmp). Hidden sectors=0x%X\n",
> 		(filesystem_type == 1 ? "FAT12" :
> 		filesystem_type == 2 ? "FAT16" :
> 		filesystem_type == 3 ? "FAT32" :
> 		filesystem_type == 4 ? "NTFS"  :
> 		filesystem_type == 6 ? "exFAT" :
> 		/*filesystem_type == 5 ?*/ "EXT2 GRLDR"),
> 		(BS->dummy1[0] == (char)0xEB ? "with" : "but WITHOUT"),
> 		BS->hidden_sectors);
> 	if (BS->hidden_sectors != new_start)
> 	{
> 	    printf_debug0 ("Changing hidden sectors 0x%X to 0x%lX... ", BS->hidden_sectors, (unsigned long long)new_start);
> 	    BS->hidden_sectors = new_start;
> 	    /* Write back/update the boot sector.  */
> 	    if (! rawwrite (current_drive, new_start, (unsigned long long)(unsigned int)mbr))
> 	    {
> 		printf_debug0 ("failure.\n");
> 	        return 0;
> 	    } else {
> 		printf_debug0 ("success.\n");
> 	    }
> 	}
>       }
> ```

should we also update BPB if exFAT?

**Comment by steve6375** [comment]
I don't think exFAT uses it. Also the sectors are checksummed.
http://shullich.blogspot.com/2009/12/vbr.html
There seems to be a Partition Offfset at 0x40.
Sector 11 is filled with the checksum
https://www.sans.org/reading-room/whitepapers/forensics/reverse-engineering-microsoft-exfat-file-system-33274

```
UINT32 VBRChecksum(const unsigned char octets[], long NumberOfBytes)
{
 UINT32 Checksum = 0;
 long Index;

 for (Index = 0; Index < NumberOfBytes; Index++)
 {
 if (Index == 106 || Index == 107 || Index == 112)
 {
 continue;
 }
 Checksum = ((Checksum <<31) | (Checksum>> 1)) + (UINT32) octets[Index];
 }
 return Checksum;
```

As far as I can see - grub4dos does add the bytes into VBR at 1c-1f but this seems wrong??? Also it does not change the Partition Offset field or recalculate the checksum and re-write sector 11???

**Comment by a1ive** [comment]
```
#define	BS	((struct master_and_dos_boot_sector *)mbr)
...
if (BS->hidden_sectors != new_start)
{
    printf_debug0 ("Changing hidden sectors 0x%X to 0x%lX... ", BS->hidden_sectors, (unsigned long long)new_start);
    BS->hidden_sectors = new_start;
...
```
grub4dos writes to mbr?

**Comment by steve6375** [comment]
no - BS is Boot Sector - VBR.
new_start is the start of the new partition = VBR

**Comment by steve6375** [comment]
/* Read the first sector.  */
      if (! rawread (current_drive, new_start, 0, SECTOR_SIZE, (unsigned long long)(unsigned int)mbr, 0xedde0d90))
        return 0;
read VBR into buffer

**Comment by steve6375** [comment]
P.S. Personally I have never tested exFAT with partnew - and no one else has either or else they would have noticed that it doesn't work!
I don't mind if exFAT is not supported with partnew for my purposes...

**Comment by steve6375** [comment]
If 0x40-47 is changed or if Sector 11 is changed
![image](https://user-images.githubusercontent.com/1469350/78146578-3e3f3680-742a-11ea-9443-97a4f82b2c66.png)
Then get Invalid partition
So if udpate 0x40-0x47 then must also update checksum sector,

**Comment by steve6375** [comment]
Setting  --type=0 will set the partition type automatically - e.g. ext3 = type 0x83
In grub4dos, we have the parttype command. This allows me to use partnew to set a ext3 partition and then use partype to set a type of 0. This prevents Windows from seeing the ext3 partition but it sill works with Linux.
How can this be done using grubfm? Need parttype command?

partnew --type=0x00 --file="${file2}" (${grubfm_disk}) 3
**parttype --type=0x00 (${grubfm_disk}) 3**  ????

**Comment by a1ive** [comment]
> Setting --type=0 will set the partition type automatically - e.g. ext3 = type 0x83
> In grub4dos, we have the parttype command. This allows me to use partnew to set a ext3 partition and then use partype to set a type of 0. This prevents Windows from seeing the ext3 partition but it sill works with Linux.
> How can this be done using grubfm? Need parttype command?
> 
> partnew --type=0x00 --file="${file2}" (${grubfm_disk}) 3
> **parttype --type=0x00 (${grubfm_disk}) 3** ????

use `dd --hex=00 --of=...`?

**Comment by steve6375** [comment]
parttype also returns the partition type.
It is quite useful.
![image](https://user-images.githubusercontent.com/1469350/78236550-0b507d80-74d2-11ea-9320-78cd27f7553d.png)
;-)

**Comment by a1ive** [comment]
> parttype also returns the partition type.
> It is quite useful.
> ![image](https://user-images.githubusercontent.com/1469350/78236550-0b507d80-74d2-11ea-9320-78cd27f7553d.png)
> ;-)

We already have `probe` command.
Does it work on logical partition or gpt?

**Comment by steve6375** [comment]
Logical or Primary - yes
GPT - I don't think so (I think works on LBA0 if it has dummy partition table).
![image](https://user-images.githubusercontent.com/1469350/78238219-3c31b200-74d4-11ea-9bce-0545f90394a1.png)

**Comment by a1ive** [comment]
> Setting --type=0 will set the partition type automatically - e.g. ext3 = type 0x83
> In grub4dos, we have the parttype command. This allows me to use partnew to set a ext3 partition and then use partype to set a type of 0. This prevents Windows from seeing the ext3 partition but it still works with Linux.
> How can this be done using grubfm? Need parttype command?
> 
> partnew --type=0x00 --file="${file2}" (${grubfm_disk}) 3
> **parttype --type=0x00 (${grubfm_disk}) 3** ????

`parttool hd0,4 type=0x00`

**Comment by steve6375** [comment]
![image](https://user-images.githubusercontent.com/1469350/78356870-54730100-75a8-11ea-8107-f2231b0c87b2.png)

**Comment by a1ive** [comment]
> ![image](https://user-images.githubusercontent.com/1469350/78356870-54730100-75a8-11ea-8107-f2231b0c87b2.png)

upgrade source code and grub2 to latest.

**Comment by steve6375** [comment]
OK
How to get current partition type using parttool ?

**Comment by a1ive** [comment]
> OK
> How to get current partition type using parttool ?

no,you can't. use `probe` to get filesystem type.

**Comment by steve6375** [comment]
Not same - e.g. 1B for hidden FAT partition.
Could you add function please?

**Comment by a1ive** [comment]
No. I don't think it is useful.You can use `hexdump` to get it.

**Comment by a1ive** [comment]
@steve6375 @wimbrts Does the latest grub2 build fix this bug?If so, I will close this issue.

**Comment by wimbrts** [comment]
Until now I only used grub2-filemanager
Can you make a new release of grub2-filemanager ?

**Comment by wimbrts** [comment]
Thanks for making new version of grub2-filemanager.
I have done sone some testing using partnew and can confirm that the issue is solved.
After partnew the MBR Bootcode is still the same and reboot in BIOS mode is OK.
