### ISSUE TITLE
Wrong Distro Detection

### ISSUE THREAD

**Issue by chromer030** [a1ive/grub2-filemanager#156]
Hi , Thanks very much for this great project.
I tried to boot latest OpenSuse Tumbleweed via E2B UEFI File Manager v1.35 (2020-04-01).zip in UEFI mode but detected as Fedora !

![2020-04-02-11-36-55-534](https://user-images.githubusercontent.com/13361552/78221152-19090180-74d8-11ea-8a42-450025769a95.jpg)

![2020-04-02-11-39-19-859](https://user-images.githubusercontent.com/13361552/78221284-566d8f00-74d8-11ea-866f-8907626725b0.jpg)

**Comment by a1ive** [comment]
But you can still boot it with this menu entry.

**Comment by chromer030** [comment]
Yes , it's booting successfully , but bootloader treat it as Fedora.
