### ISSUE TITLE
F4 - Settings - Resolution changes language back to English

### ISSUE THREAD

**Issue by steve6375** [a1ive/grub2-filemanager#159]
If the user has set a language - e.g. de_DE and then uses
F4- Resolution - (change resolution)
The language reverts back to English.

**Comment by steve6375** [comment]
Same with Disable graphics mode - English is set.

**Comment by steve6375** [comment]
![image](https://user-images.githubusercontent.com/1469350/78422431-1c76c700-7657-11ea-9fa4-2e0d6247f916.png)
![image](https://user-images.githubusercontent.com/1469350/78422447-403a0d00-7657-11ea-8674-bb545f47812f.png)

**Comment by steve6375** [comment]
![image](https://user-images.githubusercontent.com/1469350/78422520-ba6a9180-7657-11ea-920c-fae98a8ee69e.png)

**Comment by a1ive** [comment]
non-ascii characters are not supported if `terminal_output console`

**Comment by steve6375** [comment]
OK - maybe menu should say
'Disable graphics mode (English only)'

but what about changing resolution?
Why not set language back if non-text mode?
