### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by sergianto** [a1ive/grub2-filemanager#16]
I'm sorry A1ive for my english.Can I add from the menu grubfmx64 Static item or button to download BOOTMGR menu on the path /EFI/Microsoft/boot/BCD to boot the WindowsPe.And the same item in the grubfmx32 to boot BOOTMGR menu on the path /EFI/Microsoft/boot/B32

**Comment by a1ive** [comment]
Custom menus are supported.
You can add the menu entries to /boot/grub/external_menu.cfg.
<img width="512" alt="1" src="https://user-images.githubusercontent.com/10670106/36127828-53198cf4-109a-11e8-84af-4ae4bdae0194.png">
<img width="512" alt="2" src="https://user-images.githubusercontent.com/10670106/36127833-58e7c5e2-109a-11e8-8eec-d191405ac200.png">
