### ISSUE TITLE
Boot Failure for Knoppix Runtime Live CD

### ISSUE THREAD

**Issue by wimbrts** [a1ive/grub2-filemanager#167]
[Knoppix Runtime Live CD](https://www.runtime.org/data-recovery-live-cd.htm) fails to boot in case of Boot From ISO and in case of ISO map method.
In case of partnew then booting with a1live Grub2 File Manager is working OK.

I have a working Grub2 menuentry that might be helpful to you to solve the issue.
The critical part that can solve it is the asterisk in bootfrom=/dev/*$iso_path

`if [ -e "$isopath/knoppix/runtimelivecd.iso" ]; then
menuentry "ISO Knoppix - $isopath/knoppix/runtimelivecd.iso" {
  set iso_path=$isopath/knoppix/runtimelivecd.iso
  loopback loop $iso_path
  linux (loop)/boot/isolinux/linux bootfrom=/dev/*$iso_path lang=en apm=power-off nomce libata.force=noncq hpsa.hpsa_allow_any=1 loglevel=1 noswap tz=localtime
  initrd (loop)/boot/isolinux/minirt.gz
  loopback --delete loop
}
fi
`

**Comment by a1ive** [comment]
I can't boot this iso both on vm(vmware and virtualbox) and laptop.

**Comment by wimbrts** [comment]
I can boot this iso from USB made with [USB_FORMAT](https://github.com/wimbrts/USB_FORMAT/releases) Or [UEFI_MULTI](https://github.com/wimbrts/UEFI_MULTI/releases)

**Comment by a1ive** [comment]
I can't even boot the ISO directly in the vm.
![深度截图_选择区域_20200406143542](https://user-images.githubusercontent.com/10670106/78529581-78d31580-7814-11ea-9499-1b5f4b69c7ed.png)

**Comment by wimbrts** [comment]
Yes it is not so easy to boot Knoppix Runtime Live CD,
but the asterisk in bootfrom=/dev/*$iso_path solved the issue

**Comment by steve6375** [comment]
When using VBox it works OK for MBR\Legacy.
UEFI64 boots OK for me - I just can't see it!!!
The audio works and I can hear it say 'Initiating startup sequence' when it gets to the Desktop or when you do a Ctrl-Alt-Del and it shuts down.
![image](https://user-images.githubusercontent.com/1469350/78562547-791de180-7811-11ea-9709-69b0dc19eeae.png)
![image](https://user-images.githubusercontent.com/1469350/78562606-95218300-7811-11ea-8ecb-629fc5bb5d6e.png)

**Comment by steve6375** [comment]
UEFI64 is but OK on real system (except no usb kbd/mouse!)

**Comment by wimbrts** [comment]
kbd/mouse for Knoppix runtimelivece are OK when booting in UEFI 64 Secure Or BIOS mode

**Comment by a1ive** [comment]
> UEFI64 boots OK for me - I just can't see it!!!
The audio works and I can hear it say 'Initiating startup sequence' when it gets to the Desktop or when you do a Ctrl-Alt-Del and it shuts down.

I encountered the same situation. The linux kernel should setup video display automatically, strange.

**Comment by wimbrts** [comment]
In Grub2 Live ISO Multiboot as Added to SuperUEFIinSecure Boot Disk  I see in main.cfg some video settings that might be helpful to you

`# GLIM USB GRUB2 Configuration
insmod regexp

# Required for GUI and to prevent "No video mode set" error
insmod all_video

# Keep the same graphic mode for kernel booting (passed as vga=)
# other values are "text" or any gfxmode value
set gfxpayload=keep

# Enable GUI
terminal_output gfxterm

loadfont unicode

insmod png
set theme=${prefix}/themes/invader/theme.txt

set isopath=/EFI/iso
export isopath
probe --set rootuuid --fs-uuid $root
# Required to have these available in other configfile files
export theme
export isopath
export rootuuid
set prefix=($root)/EFI/grub
`

**Comment by a1ive** [comment]
`set gfxpayload=keep` `set gfxpayload=text` `set gfxpayload=auto` or `vga=791` don't work...

**Comment by wimbrts** [comment]
insmod all_video

does that has effect ?

bootfrom=/dev/*$iso_path
the asteriks I know is critical for booting Knoppix Runtime Live CD
I think it is missing in your grub2 entry ....

**Comment by a1ive** [comment]
https://github.com/a1ive/grub2-filemanager/commit/c98e8b58b36b0e852ed7d432ac19259146ae4a87
https://github.com/a1ive/grub2-filemanager/blob/1009f880306f7d31fca674d7856d2fed2f7b51e8/boot/grubfm/rules/iso/loop_detect.sh#L342
I think this is the same as `bootfrom=/dev/*$iso_path`

**Comment by wimbrts** [comment]
Ok, so the Knoppix boot problem is solved ?
Or do you still have some problem with the video in UEFI mode ?

**Comment by a1ive** [comment]
> Or do you still have some problem with the video in UEFI mode ?

yes.

**Comment by wimbrts** [comment]
I have no idea how to solve it,
but as described above in my two ways of booting Knoppix ISO there is not such video problem.

**Comment by wimbrts** [comment]
In a1ive Grub2 File Manager there is Option F4 - Disable graphics mode.
Can this be used to overcome the Knoppix video problem ?

**Comment by a1ive** [comment]
> In a1ive Grub2 File Manager there is Option F4 - Disable graphics mode.
> Can this be used to overcome the Knoppix video problem ?

I've tried. no.

**Comment by a1ive** [comment]
@wimbrts Please try if it works on your computer.
[grubfm.tar.gz](https://github.com/a1ive/grub2-filemanager/files/4464258/grubfm.tar.gz)

**Comment by wimbrts** [comment]
New version of grubfm was tested for booting Knoppix Runtime Live CD in BIOS and in UEFI mode each for 3 methods of booting.
UEFI mode - 3x Failure (always)
BIOS mode - From ISO fails (always)
BIOS mode - map is booting but stops at Waiting USB - dev not found
BIOS mode - partnew is booting OK
BIOS mode - map after partnew is booting OK

**Comment by a1ive** [comment]
[grub2-filemanager.tar.gz](https://github.com/a1ive/grub2-filemanager/files/4468810/grub2-filemanager.tar.gz)
BIOS mode should work. (use `linux16` command instead of `linux` command) But doesn't work under UEFI.

**Comment by wimbrts** [comment]
BIOS mode Boot From ISO and map method fail - dev Not found
UEFI mode Boot from ISO fail and video problem still exists

In my working menu I am using linux command and not linux16
BTW: the Grub2 File Manager has for me unreadable Chinese Chars

**Comment by a1ive** [comment]
Strange. For me, BIOS Boot from ISO -- OK, UEFI fail (video problem).

**Comment by wimbrts** [comment]
The path is critical, but for simple path then both UEFI Secure and BIOS mode are booting OK in case of Boot From ISO

**Comment by a1ive** [comment]
[grub2-filemanager.tar.gz](https://github.com/a1ive/grub2-filemanager/files/4474931/grub2-filemanager.tar.gz)
now BIOS OK and UEFI OK. (path: /extra/livecd/knoppix/iso/runtimelivecd.iso)
 But the kernel still has video problem before X11 starts under UEFI.

> but fail in case of map ISO.

"map ISO" is for Windows PE or other ISOs, not for Linux.

**Comment by wimbrts** [comment]
Boot From ISO tested:
UEFI and BIOS Fail - path: /EFI/iso/knoppix/runtimelivecd.iso
UEFI and BIOS OK - path: /images/runtimelivecd.iso

**Comment by a1ive** [comment]
It's kernel and init scripts have bugs.

**Comment by wimbrts** [comment]
OK, but booting straight with Grub2 and Grub4dos menu entries is working OK and very fast in all cases.
Also Grub2 Live Multiboot that uses path: /EFI/iso/knoppix/runtimelivecd.iso is booting OK in BIOS and UEFI mode.

**Comment by a1ive** [comment]
rename 'EFI' to 'efi'

**Comment by wimbrts** [comment]
It works OK 🥇 
EFI is generated by bcdboot.exe of Windows 10x64 in making bootable drive.
Renaming to efi solves the Knoppix Boot problem.
I will take care in my programs to Rename EFI in efi
Thanks for your help to slve the problem 👍

**Comment by wimbrts** [comment]
Thanks for new Release v7.0.0 🥇 

Everything is working OK now 👍 and I will add this v7 version to [USB_FORMAT](https://github.com/wimbrts/USB_FORMAT/releases) and [UEFI_MULTI](https://github.com/wimbrts/UEFI_MULTI/releases) in the addon-glim-agFM files
