### ISSUE TITLE
Parrot OS requires F4 'Install override security policy'

### ISSUE THREAD

**Issue by steve6375** [a1ive/grub2-filemanager#173]
I was just wondering why you don't just install this on every Secure UEFI64 boot by default?
https://rmprepusb.blogspot.com/2020/04/agfm-v138-is-now-available.html
Also, does 'sbpolicy --install' and 'fucksb' work for UEFI32 too?

**Comment by a1ive** [comment]
> I was just wondering why you don't just install this on every Secure UEFI64 boot by default?

If installed, even grubfm cannot get the exact secure boot status by itself.

> Also, does 'sbpolicy --install' and 'fucksb' work for UEFI32 too?

yes. but the problem is that we don't have Kaspersky's shim for i386-efi.

**Comment by steve6375** [comment]
> If installed, even grubfm cannot get the exact secure boot status by itself.
I don't understand..

set original_secureboot_status=$secureboot_status
sbpolicy --install
fucksb, etc.
grubfm
???

why does grubfm need to know after that?

**Comment by a1ive** [comment]
plz try.

**Comment by steve6375** [comment]
looks good. 👍
