### ISSUE TITLE
Config Not Found

### ISSUE THREAD

**Issue by chromer030** [a1ive/grub2-filemanager#175]
Hi , I devided my USB to 2 partition , first EFI for E2B UEFI file manager and second for operating systems , but from version 1.35 , i get this error :

![2020-04-09-18-04-37-356](https://user-images.githubusercontent.com/13361552/78901401-87783180-7a8d-11ea-940f-fdbb9c5a5fbd.jpg)

even tried E2B UEFI File Manager v1.37 (2020-04-05).zip , but same error , 
everything is ok with 1.35 and prior.

**Comment by steve6375** [comment]
You are confusing Easy2Boot's version of agFM with this version!
The Easy2Boot version is modified.
Please do not post Easy2Boot issues here as they may be nothing to do with this project.
As for this issue. Easy2Boot agFM expects PTN1 to be for files and PTN2 for agFM files.
If you do not make the USB drive correctly then it will not work correctly!

**Comment by chromer030** [comment]
Even with agFM_download_files.zip same error !

Downloaded here : 
https://easy2boot.webnode.com/_files/200003811-7d94f7d951/agFM_download_files.zip

**Comment by steve6375** [comment]
That is the easy2boot version of agFM
It is NOT the same files that you get if you compile this project.
