### ISSUE TITLE
Linux Distros Support issues

### ISSUE THREAD

**Issue by chromer030** [a1ive/grub2-filemanager#176]
I tried to boot some linux distros via E2B UEFI File Manager but got no support :

1- ALT Linux Live Cinnamon :

After a lot of errors reached here  :

![2020-04-09-18-27-35-060](https://user-images.githubusercontent.com/13361552/78903741-d5daff80-7a90-11ea-926d-62acb0e0b7eb.jpg)

2- Austrumi 4.1.8 :

When Enter on Boot ISO (map / WinPE) nothing happen :

![2020-04-09-18-29-23-962](https://user-images.githubusercontent.com/13361552/78904098-513cb100-7a91-11ea-8cb2-e54a7d5f65e3.jpg)

3- Porteus 5 KDE :

and also when Enter on Boot ISO (map / WinPE) nothing happen :

![2020-04-09-18-30-04-027](https://user-images.githubusercontent.com/13361552/78904212-73363380-7a91-11ea-8775-bc2357483123.jpg)

i will test some other Top distros and will report here.

**Comment by steve6375** [comment]
To report true agFM issues (and not E2B issues) you should delete the \boot\grubfm\config file.
Then you will get true a1ive grub2 files without E2B additions\modifications.
Secondly, you need to specify how you are booting - MBR\Legacy, UEFI32, UEFI64, Secure Boot.
Thirdly, you need to give EXACT filename of the ISO or payload file (and if possible, download URL).
Fourth, if you are attempting to UEFI64 boot, you need to make sure that the ISO has the required UEFI64 boot files (i.e. \EFI\BOOT\BOOTX64.efi). If it doesn't support UEFI64 then it obviously won't UEFI-boot (e.g. austrumi-2.2.9.iso).
Lastly, please specify what you are booting from. Make, Model, graphics card, etc.

**Comment by a1ive** [comment]
> 2- Austrumi 4.1.8 :

ftp://austrumi.ru.lv/ too slow, is there any faster mirrors?

**Comment by a1ive** [comment]
Porteus:
![深度截图_选择区域_20200410120517](https://user-images.githubusercontent.com/10670106/78961334-ae814280-7b23-11ea-899d-7caecf82b5c7.png)

**Comment by a1ive** [comment]
> 1- ALT Linux Live Cinnamon :

ALT Linux ISO is larger than 4GB, however it doesn't support NTFS.
You need to ensure the iso is contiguous, and boot with "Boot ISO (partnew)".
> 2- Austrumi 4.1.8 :

this distro doesn't support loopback-booting or UEFI-booting.

**Comment by chromer030** [comment]
@steve6375 Thank you for your guide i will test and report.
@a1ive ALT linux has Regular version with a lot of favours and all under 2 GB :
https://en.altlinux.org/Regular

**Comment by a1ive** [comment]
Now ALT Linux should work. (regular ISO, FAT32)

![深度截图_选择区域_20200410153655](https://user-images.githubusercontent.com/10670106/78972991-90c2d600-7b41-11ea-9607-b656521f701d.png)
