### ISSUE TITLE
Ubuntu18.04 安装失败

### ISSUE THREAD

**Issue by lizhaoda** [a1ive/grub2-filemanager#18]
如题，grub文件管理器可以引导Ubuntu18.04进入安装界面，但是安装过程中会卡在某一个环节，具体忘了

**Comment by a1ive** [comment]
Ubuntu的ISO支持Loopback，应该首选Loopback方式启动。

**Comment by zdaiot** [comment]
您好，我最近又试了一下，按照您说的Loopback方式启动，报错如下：

我的启动方式为Uefi

![image](https://user-images.githubusercontent.com/40540467/58631008-bd984100-8313-11e9-994d-65702391f1e8.png)

**Comment by a1ive** [comment]
> 您好，我也遇到了这个问题，按照您说的Loopback方式启动，报错如下：
> 
> 我的启动方式为Uefi
> 
> ![image](https://user-images.githubusercontent.com/40540467/58631008-bd984100-8313-11e9-994d-65702391f1e8.png)

这应该是 Ubuntu 的一个 bug : https://bugs.launchpad.net/ubuntu/+source/ubiquity/+bug/1155216

**Comment by zdaiot** [comment]
按照上面论文的说法，我在出现这个界面的时候，进入tty，输入`sudo umount -l -r -f / isodevice`。但是还是不行。请问您有什么建议么？

**Comment by a1ive** [comment]
那只能把ISO解压到u盘上安装了吧。

**Comment by a1ive** [comment]
> 按照上面论坛的说法，我在出现这个界面的时候，进入tty，输入`sudo umount -l -r -f / isodevice`。但是还是不行。请问您有什么建议么？
貌似应该是 `sudo umount -l -r -f /isodevice`
你输的命令多了一个空格 .

**Comment by zdaiot** [comment]
您好，我实际敲命令的时候是没有那个空格的。我在这打的时候不小心多打了一个空格
