### ISSUE TITLE
if -f /* not working when folder beginning with $ is present?

### ISSUE THREAD

**Issue by steve6375** [a1ive/grub2-filemanager#181]
issue caused by $$$$CONFIG folder.

![image](https://user-images.githubusercontent.com/1469350/79110575-ab2fc600-7d72-11ea-8721-4814ae78d091.png)

**Comment by a1ive** [comment]
`[ -f xxx/* ]` doesn't work on linux either.
![1](https://user-images.githubusercontent.com/10670106/79114325-94f72980-7db5-11ea-8851-20615d9a358c.png)

**Comment by steve6375** [comment]
so we have to use *.*  ??

**Comment by a1ive** [comment]
maybe.
