### ISSUE TITLE
Enhancement: add condition test to types file

### ISSUE THREAD

**Issue by steve6375** [a1ive/grub2-filemanager#183]
I would like certain files to not be listed under certain conditions.
For instance,  Ubuntu.iso64 would only be listed if the CPU was a 64-bit CPU.
This could be done if the [type] list would accept a conditional test

```
[type]
icon = iso
display = 1
boot = iso/e2b.sh
condition = iso/test64.sh
```

and test64.sh could check CPU and then set grubfm_test=0 or 1 ??

i.e. I don't want the file to be listed at all when the test fails.

Could this be done?

**Comment by a1ive** [comment]
1) `grubfm_set --hide 1` to enable 'hide files' feature.
2) `display = 1` is conflict with `condition = iso/test64.sh`.
    `display = 1` OR `condition = iso/test64.sh (grubfm_test == 1)` --> display

**Comment by steve6375** [comment]
Looks great! thanks. Will close after more testing.

**Comment by steve6375** [comment]
works great. thanks 🥇
