### ISSUE TITLE
Enhancement: Add global * for types files

### ISSUE THREAD

**Issue by steve6375** [a1ive/grub2-filemanager#185]
Currently I have to add all possible combinations of type extensions into the types folder:
![image](https://user-images.githubusercontent.com/1469350/79628291-afbffa00-8137-11ea-99b3-444d9d602fa0.png)

This slows down file enumeration.

Is it possible to have say:
types/iso*
types/imgptn*

So any extension beginning with .iso or .imgptn uses the same types file.

P.S. I haven't tested this but I assume it doesn't currently work...

**Comment by a1ive** [comment]
> Is it possible to have say:
types/iso*
types/imgptn*

no.
take a look at [boot/grubfm/rules/generic.ini](https://github.com/a1ive/grub2-filemanager/blob/master/boot/grubfm/rules/generic.ini)

**Comment by steve6375** [comment]
OK
sorry, I don't understand how generic.ini could be useful? Could you explain?

**Comment by a1ive** [comment]
use regexp in "condition" menu in generic.ini?
