### ISSUE TITLE
Different icons for usb memory and hdd

### ISSUE THREAD

**Issue by farukgkc** [a1ive/grub2-filemanager#186]
Hello there,
As an icon, can there be an improvement in the different icons for different HDDs for USB devices?

![g2fm](https://user-images.githubusercontent.com/16747993/79961764-d8c1f100-848f-11ea-95ce-4ba217e09a6f.jpg)

**Comment by a1ive** [comment]
GRUB2 doesn't distinguish between usb, SATA or other drives.
Disk drivers are provided by firmware (bios/uefi).
