### ISSUE TITLE
Allow to run custom 'USB:/e2b/INSTALL.cmd' 'after mounting Win ISO and before running x:/setup.exe command

### ISSUE THREAD

**Issue by devdevadev** [a1ive/grub2-filemanager#189]
Hello Sir,

First lots of thanks for providing Grub2 File Manager which allow us to UEFI/MBR boot wih E2B...

I have a **'%E2BDRIVE%:/_ISO/WINDOWS/INSTALL/CONFIGS/INSTALL.cmd'** which I normally call within from x:/Windows/System32/start.bat so that automatically Backup User Data , modifying USERNAME and PCNAME in XML before formatting or re-partitioning of Disk 0. and then run following command to start installation.

**x:\sources\setup.exe /unattend:%E2BDRIVE%\AutoUnattend.xml**

It's looking x:/Windows/system32/start.bat file is within grubfmx64.efi (install.gz) so I am unable to modify them as per my requirement so It will be very useful if you provide a simple way to call a INSTALL.cmd file just after Mounting Win ISO so that we will be able to do some extra work within WinPE environment by using **%E2BDRIVE%:/_ISO/WINDOWS/INSTALL/CONFIGS/INSTALL.cmd** and then continue Windows Installation process as usual. 

Please help.....

Thanks & Regards....

**Comment by a1ive** [comment]
If you are using Easy2Boot's version of agFM, please ask @steve6375 for help.
The e2b version of file manager is modified.

**Comment by devdevadev** [comment]
agFM:\grubfmx64.efi\mods\boot\grubfm\distro\win.sh copy the 'start.bat' within from 'install.gz' to the x:/wndows/system32 folder. Steve said win.sh and start.bat is compiled by you and any files within grubfmx64.efi package are written by you....So I have to ask you after asking Steve.....

will be nice if win.sh also look for 'start.bat' file in the agFM Partition and if found a 'start.bat' in the agFM partition then copy that file into x:/windows/system32 folder and replace the official one...

Please suggest the best way to use my own 'start.bat' located in the root/directory of agFM Partition ?

Regards...

**Comment by a1ive** [comment]
![1](https://user-images.githubusercontent.com/10670106/80324910-97518d00-8865-11ea-9d3b-f75a089be1f7.png)
In E2B UEFI a1ive grub2 File Manager.zip:\boot\grubfm\rules\iso, steve has written an example script to load 'start.bat' from local disk?

**Comment by devdevadev** [comment]
I had already asked Steve about 'start_pe.bat' file. Steve said it is old file and is useless and does not utilize in the process of Windows Installation. It's why I had to ask you for help....
May be Steve also uses the official method for Win ISO booting ?

 set start="(${user})/boot/grubfm/rules/iso/start_pe.bat"

**Comment by devdevadev** [comment]
May be you can use following codes within  \grubfmx64.efi\mods\boot\grubfm\distro\win.sh

set start="(install)/start.bat"

if exist "(${user})/boot/grubfm/rules/iso/start.bat" , then run 

set start="(${user})/boot/grubfm/rules/iso/start.bat"

Is it possible to hope something like this ?

Regards..

**Comment by devdevadev** [comment]
Thanks you so much sir for your great help and support....
Regards...

**Comment by a1ive** [comment]
You can use `export grubfm_startbat=(hd0,1)/xxx.bat` to replace the default start.bat
https://rmprepusb.blogspot.com/2020/04/agfm-v146-released.html
