### ISSUE TITLE
ext3 or ext4 is identified as ext2

### ISSUE THREAD

**Issue by steve6375** [a1ive/grub2-filemanager#194]
Not sure if this can be fixed, but it is a bit confusing to the user if they know that the partition is an ext3 partition and it shows as ext2!
If grub2 cannot distinguish between ext2/3/4, can it be shown as just 'ext'  or  maybe as  'ext2/3/4'?
![image](https://user-images.githubusercontent.com/1469350/80708215-32a36600-8ae3-11ea-8fe3-ac5e30b41f0c.png)

**Comment by a1ive** [comment]
grub2 cannot distinguish between ext2/3/4.

I think 'ext2' cames from 'e2fs '
https://en.wikipedia.org/wiki/E2fsprogs

**Comment by steve6375** [comment]
OK, maybe grubfm can modify the menu entry to show just 'ext' ?

**Comment by a1ive** [comment]
No. This may cause incompatibility with gnu grub.

**Comment by steve6375** [comment]
Isn't this just a menuentry?
![image](https://user-images.githubusercontent.com/1469350/80709558-5d8eb980-8ae5-11ea-9482-174e9e5de987.png)

Why can't you just change the string  ext2 to ext?
Only the display to the user is affected.

**Comment by a1ive** [comment]
Is it really important to display "ext"? I don't like an additional 'if' condition.

**Comment by steve6375** [comment]
It confuses the user and is incorrect. 
They know it is ext3 but is is shown as ext2.
It should not say ext2 if it is not ext2!
It is the same as displaying a partition as fat12 when it is fat32.
