### ISSUE TITLE
build.sh fails to make grubfm_multiarch.iso

### ISSUE THREAD

**Issue by steve6375** [a1ive/grub2-filemanager#195]
![image](https://user-images.githubusercontent.com/1469350/80713194-f8d65d80-8aea-11ea-9980-74714a3a0c0b.png)
Is this because my Mint Linux is Legacy booted and not UEFI-booted?

**Comment by a1ive** [comment]
http://bbs.wuyou.net/forum.php?mod=redirect&goto=findpost&ptid=420085&pid=4049040&fromuid=487838
