### ISSUE TITLE
add ventoy support

### ISSUE THREAD

**Issue by a1ive** [a1ive/grub2-filemanager#197]
https://github.com/ventoy/Ventoy

**Comment by a1ive** [comment]
已知问题:

- [ ] 若磁盘只有一个分区，无法启动该分区上的 Linux LiveCD
- [ ] 启动 Windows 7 ISO 时不能正常加载 imdisk 驱动
- [ ] 不支持逻辑分区 (起始扇区计算错误)
- [ ] 不支持 RAW 以及 MEMDISK 方式
- [ ] 可能不支持碎片数超过1024的文件

**Comment by a1ive** [comment]
@steve6375 you can select "Boot ISO (Ventoy)" option to try ventoy on grubfm.
It patches the ISO to modify the initrd, but save the modified part to memory.

**Comment by farukgkc** [comment]
Hi,

Can it be ensured that "Boot ISO (Ventoy)" option does not appear when iso file is selected from HDD? Or, when ISO is selected from USB memory, can the option "Boot ISO (Ventoy)" appear?

**Comment by a1ive** [comment]
> Hi,
> 
> Can it be ensured that "Boot ISO (Ventoy)" option does not appear when iso file is selected from HDD? Or, when ISO is selected from USB memory, can the option "Boot ISO (Ventoy)" appear?

No. From the perspective of grub, there is no difference between a local hard drive and a USB drive.
The "Ventoy" option should also work on hard drive.

**Comment by a1ive** [comment]
已知问题:

- [ ] 若磁盘只有一个分区，无法启动该分区上的 Linux Live CD
- [ ] 启动旧版本 MSDN Windows ISO 时不能正常加载 imdisk 驱动
- [ ] 不支持 RAW 以及 MEMDISK 方式
- [ ] 启动 GPT 本地硬盘上的 Linux Live CD 时会死机 (存疑) 
- [ ] 尚未测试无人值守脚本能否正常工作
