### ISSUE TITLE
Enhancement: Display grubfm help files

### ISSUE THREAD

**Issue by steve6375** [a1ive/grub2-filemanager#198]
A special extension could be recognised - e.g. **.grubfm_help** or **.aghlp** ?

When selected the text inside is displayed to the user.
It would be nice if coloured text was also supported.
This could be used for help files to present nice formatted text to the user.

We could have various .grubfm_help files for different ISOs or folders which could explain to the user how to boot the payloads.
e.g.
\Ubuntu.iso
\Ubuntu.grubfm_help

If the user selects Ubuntu.iso then an extra Help item is **listed in the secondary menu** which runs the .grubfm_help file and displays instructions to the user.

If the user selects the Ubuntu.grubfm_help file directly from the folder, then help is immediately displayed. i.e. grubfm_help files are always listed in the file manager.
e.g.
\Help and Information.grubfm_help
\How to use agFM.grubfm_help
etc.

The user could write their own help files to support the ISOs\VHDs etc. that they have added.
e.g.
Index.grubfm_help      - contains brief list of utilities in the folder and what they do

**Comment by a1ive** [comment]
> When selected the text inside is displayed to the user.
It would be nice if coloured text was also supported.
This could be used for help files to present nice formatted text to the user.

Where to display these texts?
It's difficult to implement these under grub2 gfx theme or console mode.

**Comment by steve6375** [comment]
The main problem is that it is not easy to use the echo command to write coloured text.
It is possible to use echo and set color like this using a UTF-8 text file  - e.g. text.cfg
![image](https://user-images.githubusercontent.com/1469350/80946460-03903b80-8de6-11ea-852a-287b19ad9527.png)
```
echo ãngastrom Ètude Ánti
set color_normal=yellow/black
echo ãngastrom Ètude Ánti
set color_normal=red/black
echo -n ãngastrom Ètude Ánti
echo ãngastrom Ètude Ánti
set color_normal=blue/black
read
```
but it is not very user friendly.

I was thinking of perhaps a lua script that would interpret this file and also special rgb colors
e.g.
[theme_off]
[clear]
[setmode 1024x768]
ãngastrom Ètude Ánti [0xCCCC00] hello [0xFF0000] world!
This is the second line.
[pause]
Please visit [0x00FF00] www.easy2boot.com[] for more details.


where [theme_off] will remove the theme but keep the current resolution
[clear] will clear the current text space (optional)
[setmode nnnxnnn] will set the screen resolution
[0xrrggbb] sets the current text color and [0xRRGGBB00rrggbb] sets both foreground and background
[] sets the text colour back to the default colour
On exit, the current resolution, default text color and theme are restored.

Or another (easier/better?) solution perhaps , would be for the user to just write the file in grub2 commands, but enhance the grub2 **echo** command to recognise some special 'escape sequences' like **$[0x**RRGGBB00rrggbb] and **$[]** to change and restore the text colour.

In this way a Help menu could be made
menuentry "Help - Intro" --class=nt6 {
echo ãngastrom Ètude Ánti blah blah blah blah $[0xFF0000] ãngastrom Ètude Ánti$[]
echo ãngastrom Ètude Ánti blah blah blah blah $[0xFF0000] ãngastrom Ètude Ánti$[]
echo Press a key to continue...
read
}
menuentry "Help - Getting started" --class=nt6 {
echo ãngastrom Ètude Ánti blah blah blah blah $[0xFF0000] ãngastrom Ètude Ánti$[]
echo ãngastrom Ètude Ánti blah blah blah blah $[0xFF0000] ãngastrom Ètude Ánti$[]
echo Press a key to continue...
read
}

The idea is to be able to easily make help files such as:
![image](https://user-images.githubusercontent.com/1469350/80947529-3b987e00-8de8-11ea-98a9-14346a5a20e5.png)

grub4dos can use escape sequences to position the text at any XY position on the display using -P:YYXX and in any colour. It can restore the original text colour using $[].
```
title About Easy2Boot\nIntroduction to E2B
clear
echo -e -n $[0xFF0000]EASY2BOOT$[] (E2B) INTRODUCTION
echo -e -P:0082 $[0xFFFF00]www.easy2boot.com
echo -e \n
echo Easy2Boot is based on grub4dos - it is open source and free.
echo
```

One other alternative is for the user to write the help text in Powerpoint or Word or LibreOffice and then take a screenshot of it and save it as a .jpg. Then use menuentry in a .cfg file to display a help menu.

**Comment by steve6375** [comment]
Here is an example of a help menu and screens.
You can see how awkward it is to write coloured text

```
set yellow="set color_normal=yellow/black"
set red="set color_normal=red/black"
set blue="set color_normal=blue/black"
set white="set color_normal=white/black"
set hlite="set color_normal=red/white"

menuentry "Help" --class=info {
echo -n "ãngastrom Ètude Ánti ";${yellow};echo -n "This is yellow";${red};echo -n " This is red";${blue};echo -n " This is blue"
$white
echo
echo This is an example of how to write help text
echo -n "You can use colours like ";${red};echo -n "red";${white}; echo -n " or " ;$yellow; echo -n " yellow or " ;$blue; echo -n "blue"
echo
$hlite
echo ãngastrom Ètude Ánti
$white
echo Press a key to continue
read
}

menuentry "Help " --class=png {
set bmp_path="(hd0,1)/_ISO/jolene 800.bmp";
lua ${prefix}/view.lua;

}
menuentry "Back" --class=info {
grubfm "${grubfm_current_path}"
}

```
![image](https://user-images.githubusercontent.com/1469350/80962042-27fb1080-8e04-11ea-9c51-0043fad2f0ca.png)
![image](https://user-images.githubusercontent.com/1469350/80962059-334e3c00-8e04-11ea-9e9b-e30695be1b8f.png)

**Comment by a1ive** [comment]
> I was thinking of perhaps a lua script that would interpret this file and also special rgb colors

I don't want to 'invent' a new document format...

>  would be for the user to just write the file in grub2 commands, but enhance the grub2 echo command to recognise some special 'escape sequences' like $[0xRRGGBB00rrggbb] and $[] to change and restore the text colour.

then we should enhance the grub2 script parser instead of echo command, but I don't think it's easy.
I also don't want to 'invent' a new 'grammar', I prefer "bash-style" (https://misc.flogisoft.com/bash/tip_colors_and_formatting)

**Comment by steve6375** [comment]
> (https://misc.flogisoft.com/bash/tip_colors_and_formatting)

Ugh! That is so bad! Not at all user-friendly! If you implemented that, I don't think anyone would use it! I certainly would not use it!

I think enhancing the **echo**  command to recognise color (and cursor) commands would be the best compromise? If it was compatible with grub4dos echo -e command then it would not be a 'new' grammar. echo -e **-P:**YYXX **$[0x**rrggbb00RRGGBB**]** message **$[]**  are all that are required.
If you don't like the thought of using -e, add a new switch (-f ?) to recognise the new escape sequences?

**Comment by a1ive** [comment]
> > (https://misc.flogisoft.com/bash/tip_colors_and_formatting)
> 
> Ugh! That is so bad! Not at all user-friendly! If you implemented that, I don't think anyone would use it! I certainly would not use it!
> 
> I think enhancing the **echo** command to recognise color (and cursor) commands would be the best compromise? If it was compatible with grub4dos echo -e command then it would not be a 'new' grammar. echo -e **-P:**YYXX **$[0x**rrggbb00RRGGBB**]** message **$[]** are all that are required.
> If you don't like the thought of using -e, add a new switch (-f ?) to recognise the new escape sequences?

![深度截图_选择区域_20200504201804](https://user-images.githubusercontent.com/10670106/80965009-6adcd880-8e44-11ea-8259-e0da54f36b04.png)
It's not user-friendly, but '*linux*-user-friendly'.
Isn't it strange if we use grub4dos-like syntax instead of bash-like syntax?
Moreover, `\e` is more convenient to parse than `$[]` (conflict with variables)!

**Comment by steve6375** [comment]
I don't mind what it is, but it has to be user friendly and that Bash escape sequence stuff is in no way user friendly (do linux users deliberately make things difficult for themselves?)!

**Comment by a1ive** [comment]
RGB colors are not supported in text mode `terminal_output console`!
See UEFI Spec.
![深度截图_选择区域_20200504204617](https://user-images.githubusercontent.com/10670106/80967109-661a2380-8e48-11ea-8fda-2ef009e6edac.png)
![深度截图_选择区域_20200504204631](https://user-images.githubusercontent.com/10670106/80967116-6a464100-8e48-11ea-8fd5-bf9e85e3c09c.png)

**Comment by steve6375** [comment]
OK
so background value 0-7, foreground value 0-F.
0x00 - 07F

**Comment by steve6375** [comment]
According to that, we cannot have yellow as a background colour?
But UEFI64 does give yellow as a background colour.
???

![image](https://user-images.githubusercontent.com/1469350/80980605-bd0c0280-8e20-11ea-89d6-b6f76c29fd1a.png)
```
set yellow="set color_normal=yellow/black"
set red="set color_normal=red/black"
set blue="set color_normal=light-blue/yellow"
set white="set color_normal=light-gray/brown"
set hlite="set color_normal=red/white"

menuentry "Help" --class=info {
echo -n "ãngstrom Ètude Ánti ";${yellow};echo -n "This is yellow";${red};echo -n " This is red ";${blue};echo -n "This is blue"
$white
echo
echo This is an example of how to write help text
echo -n "You can use colours like ";${red};echo -n "red";${white}; echo -n " or " ;$yellow; echo -n "yellow or " ;$blue; echo -n "blue"
echo
$hlite
echo ãngstrom Ètude Ánti
$white
echo Press a key to continue
read
}
```

**Comment by steve6375** [comment]
terminal_output console
![image](https://user-images.githubusercontent.com/1469350/80988173-019c9b80-8e2b-11ea-9d86-3ffc2d81516d.png)
so top colours are not supported in console mode but are in other modes.

**Comment by steve6375** [comment]
P.S. When in console mode, if the color_normal is set to non-black, the menu is not too pretty and has artifacts. Is this a grub2 bug?
![image](https://user-images.githubusercontent.com/1469350/80991236-9acdb100-8e2f-11ea-80d7-3d1446a9f84b.png)

**Comment by steve6375** [comment]
With black background, two characters on right are correct.
![image](https://user-images.githubusercontent.com/1469350/80993002-41b34c80-8e32-11ea-8f95-5254010c85de.png)

**Comment by a1ive** [comment]
> P.S. When in console mode, if the color_normal is set to non-black background, then the menu is not too pretty and has artifacts. Is this a grub2 bug?
> ![image](https://user-images.githubusercontent.com/1469350/80991236-9acdb100-8e2f-11ea-80d7-3d1446a9f84b.png)

I don't know how to fix it.just use the black background.

**Comment by a1ive** [comment]
![深度截图_选择区域_20200505200607](https://user-images.githubusercontent.com/10670106/81064297-084f0f80-8f0c-11ea-9bc3-2f2c2e4ffca4.png)
[grubfmx64.efi.tar.gz](https://github.com/a1ive/grub2-filemanager/files/4580627/grubfmx64.efi.tar.gz)
please try.
Use `\e0xab` format to set color, e.g.
echo -e "The quick \0x06brown\0x07 fox jumps over the lazy dog"
must add double quote between strings otherwise won't work.
```
static const char *color_list[16] =
{
  "black",
  "blue",
  "green",
  "cyan",
  "red",
  "magenta",
  "brown",
  "light-gray",
  "dark-gray",
  "light-blue",
  "light-green",
  "light-cyan",
  "light-red",
  "light-magenta",
  "yellow",
  "white"
};
```
"0" means black, "f" means white, the first num is background color, the second is foreground color.

**Comment by steve6375** [comment]
looks good!
![image](https://user-images.githubusercontent.com/1469350/81067627-d8394980-8ed6-11ea-8324-95bba5c2e843.png)

1. It does change the console colour though - it should restore the original console text colour. The user may have changed the console colour, so we cannot assume it is 0x07.
2. Secondly, we need a value for the original console colour - e.g. perhaps 0xFF which is unlikely to be used? This can also be used before a \n so it matches any other console background colour used before.

e.g. 
`echo -e "This text is in whatever console colour was chosen by the user \e0x17this isn't\e0xff and this is"`

`echo -e "This text is in whatever console colour was chosen by the user \e0x17this isn't\e0xff\nand this is"`

**Comment by steve6375** [comment]
Something is not quite right with the test version in console mode,
This is without using \e0x - just standard commands

here is \boot\grub\config  echo display
![image](https://user-images.githubusercontent.com/1469350/81124105-84594f80-8f2c-11ea-98fb-e2b28fe45423.png)

and this is the test version
![image](https://user-images.githubusercontent.com/1469350/81124032-57a53800-8f2c-11ea-8369-aacb60b5e1b3.png)

**Comment by a1ive** [comment]
> Something is not quite right with the test version of grubfmx64.efi in console mode,
> This is without using \e0x - just standard commands
> 
> here is \boot\grub\config echo display
> 
> ```
> if [ "$grub_secureboot" = "Enabled" ]; then set color_normal=white/red; fi
> echo Secure Boot: $grub_secureboot
> set color_normal=yellow/black
> echo Boot drive: $bootdev
> echo RAM: ${RAM} MB
> ```
> 
> ![image](https://user-images.githubusercontent.com/1469350/81124105-84594f80-8f2c-11ea-98fb-e2b28fe45423.png)
> 
> and this is the test version
> ![image](https://user-images.githubusercontent.com/1469350/81124032-57a53800-8f2c-11ea-8369-aacb60b5e1b3.png)

![深度截图_选择区域_20200506171627](https://user-images.githubusercontent.com/10670106/81160945-5b34cf80-8fbd-11ea-9dd7-b60ccfefc52c.png)
can't reproduce ???

**Comment by steve6375** [comment]
[config.zip](https://github.com/a1ive/grub2-filemanager/files/4585872/config.zip)

**Comment by steve6375** [comment]
test version:
![image](https://user-images.githubusercontent.com/1469350/81162368-fb223700-8f84-11ea-94ce-b4904df4e935.png)
Release version:
![image](https://user-images.githubusercontent.com/1469350/81162388-04ab9f00-8f85-11ea-99e0-b16dd065f466.png)

**Comment by a1ive** [comment]
please try.
[grubfmx64.efi.tar.gz](https://github.com/a1ive/grub2-filemanager/files/4586347/grubfmx64.efi.tar.gz)

**Comment by a1ive** [comment]
> * It does change the console colour though - it should restore the original console text colour. The user may have changed the console colour, so we cannot assume it is 0x07.
> * Secondly, we need a value for the original console colour - e.g. perhaps 0xFF which is unlikely to be used? This can also be used before a \n so it matches any other console background colour used before.

Actually, I noticed some strange things.
enter `echo $color_normal`, it says "white/black". But this is not true, it should be "light-gray/black".

**Comment by steve6375** [comment]
New version is better.

**Comment by steve6375** [comment]
Did you solve the problem you found? I can reproduce it too with new build.
![image](https://user-images.githubusercontent.com/1469350/81172984-2f065800-8f97-11ea-9342-169905fd4ead.png)

**Comment by steve6375** [comment]
P.S. why is date as signature 084a0deff same ???

**Comment by a1ive** [comment]
same for old version
![深度截图_选择区域_20200506194503](https://user-images.githubusercontent.com/10670106/81173162-30a14180-8fd2-11ea-896e-4c0503e410ba.png)

**Comment by a1ive** [comment]
> P.S. why is date and signature 084a0deff same ???

date won't change if not configured (`./configure`)

**Comment by steve6375** [comment]
No way to restore current colour?

```
echo TEST
set n="set color_normal=$color_normal"
echo -e "\e0x04This is red";$n;echo -e "This is previous colour"
echo $n
read
```

![image](https://user-images.githubusercontent.com/1469350/81177816-2ade3880-8f9f-11ea-8d11-103811281236.png)

**Comment by a1ive** [comment]
> No way to restore current colour?
> 
> ```
> echo TEST
> set n="set color_normal=$color_normal"
> echo -e "\e0x04This is red";$n;echo -e "This is previous colour"
> echo $n
> read
> ```
> 
> ![image](https://user-images.githubusercontent.com/1469350/81177816-2ade3880-8f9f-11ea-8d11-103811281236.png)

We can't do it unless fix that bug.

**Comment by steve6375** [comment]
re. bug
You could set colour to light-gray/black in  your init.sh ?

![image](https://user-images.githubusercontent.com/1469350/81178264-dd160000-8f9f-11ea-9f8a-4e6263cc8cc5.png)

Some help for -e would be nice
e.g.
`-e   Enable interpretation of backslash escapes, e.g. \t=tab,\n=new line,\e0x1f=white text on blue background.`

**Comment by steve6375** [comment]
is 
[-e | -n] correct???  Should it be [-e] [-n] ???

**Comment by a1ive** [comment]
> re. bug
You could set colour to light-gray/black in your init.sh ?

Yes, but it is still a bug.

**Comment by steve6375** [comment]
Thanks
