### ISSUE TITLE
F4 - disable alphabetical sorting no longer works

### ISSUE THREAD

**Issue by steve6375** [a1ive/grub2-filemanager#199]
Variable is set, but files are still in alphabetical order

**Comment by steve6375** [comment]
![image](https://user-images.githubusercontent.com/1469350/80861662-de75be80-8c67-11ea-9b4d-006816de1065.png)

**Comment by a1ive** [comment]
if nobody uses this option, I will delete this menu.

**Comment by steve6375** [comment]
well one user found the problem, so he must have used it. He was probably just trying it out though...

**Comment by a1ive** [comment]
> Variable is set, but files are still in alphabetical order

???
![深度截图_选择区域_20200503110346](https://user-images.githubusercontent.com/10670106/80897665-ce281700-8d2d-11ea-921e-9f47fd06479e.png)

**Comment by steve6375** [comment]
I think user was mistaken - also my files seem to be in alphabetical order anyway!
Sorry. Will close.
