### ISSUE TITLE
approx 15 second delay on UEFI64 boot (Gigabyte B450)

### ISSUE THREAD

**Issue by steve6375** [a1ive/grub2-filemanager#200]
Report from user using 'B450 AORUS ELITE with 16gb ram + ryzen 2600'
"I have noted that when I boot to UEFI64 it seems to stall on boot. When it starts to move it says 'Driver installed'."
![image](https://user-images.githubusercontent.com/1469350/80862255-80e37100-8c6b-11ea-843d-fb368a24213c.png)

**Comment by steve6375** [comment]
He says earlier versions around  2020-03-27 only took 3-4 seconds.

**Comment by a1ive** [comment]
https://github.com/a1ive/grub2-filemanager/blob/cd215da77fade6cafaaf2891fa43e8643450a888/boot/grubfm/init.sh#L34
remove this line

**Comment by steve6375** [comment]
What does CrScreenshotDxe.efi do and why is it needed?

**Comment by a1ive** [comment]
a uefi driver to take screenshots. (LCtrl+LAlt+F12)

**Comment by a1ive** [comment]
> https://github.com/a1ive/grub2-filemanager/blob/cd215da77fade6cafaaf2891fa43e8643450a888/boot/grubfm/init.sh#L34
> 
> 
> remove this line

or
```
efiload --nc ${prefix}/CrScreenshotDxe.efi;
```

**Comment by steve6375** [comment]
I commented out that line and sent him the new grubfmx64.efi file.
Now booting is very fast!

**Comment by steve6375** [comment]
tested --nc - also works fast too.

**Comment by a1ive** [comment]
http://bbs.wuyou.net/forum.php?mod=redirect&goto=findpost&ptid=417233&pid=4022474
someone reported that add --nc and then ntboot won't work, strange.

**Comment by steve6375** [comment]
Why not make it an F4 option to load the screenshot efi.
That way the user will also be aware of Ctrl+Alt+F12 option but they will only load it when needed.

**Comment by steve6375** [comment]
P.S. F4 - load AHCI Driver recently? Is it OK for you?

**Comment by a1ive** [comment]
> P.S. Have you tested F4 - load AHCI Driver recently? Is it OK for you?
> Is it OK for you?

I tested it on my surface pro 3 about 2 years ago.
once it is loaded, bios/uefi drivers can no longer be used, and you can only boot to linux.
I saw supergrubdisk has this option, so I added it.
It doesn't work on many PCs, so remove it?

**Comment by steve6375** [comment]
Under VBOX it now seems to crash VBOX.
I had tested it before and it didnt crash but just gave the existsing drives funny names (ahci1, ahci2) etc..
Now it crashes grub2 though...

**Comment by a1ive** [comment]
> but just gave the existing drives funny names (ahci1, ahci2

yes, it will REPLACE the disk drivers provided by bios.

**Comment by steve6375** [comment]
sure - it used to do this - but now it crashes (for last few weeks at least).

**Comment by steve6375** [comment]
what is best solution for CrScreenshotDxe.efi ???

**Comment by a1ive** [comment]
I will remove it when I have time.
and maybe write a grub module to take screenshots...

**Comment by steve6375** [comment]
yes, reboot.pro is down (again) since yesterday.

**Comment by a1ive** [comment]
Now you can download grub2 latest build and try it.
Extract crscreenshot.mod from grub2-latest.tar.gz/x86_64-efi and copy it to usb disk.
Enter `insmod /crscreenshot.mod` (use full path) in terminal to load it, then you can press "LCtrl+LAlt+F12" to capture screen.
