### ISSUE TITLE
Winpe.lua resolution

### ISSUE THREAD

**Issue by farukgkc** [a1ive/grub2-filemanager#202]
Hi,
https://github.com/a1ive/grub2-filemanager/blob/master/boot/grubfm/rules/iso/winpe.lua#L85

> "set gfxmode=1920x1080,1366x768,1024x768,800x600,auto\n" ..
"terminal_output gfxterm\n" ..
 "boot\n"

These commands don't work. Would you check?

**Comment by a1ive** [comment]
#122

**Comment by a1ive** [comment]
remove `boot`?

**Comment by a1ive** [comment]
![深度截图_选择区域_20200512153523](https://user-images.githubusercontent.com/10670106/81652499-69c03280-9466-11ea-8963-1fca027b23a8.png)
Any further information? @farukgkc

**Comment by crasadure** [comment]
hi a1live;
@serhat100 from TNCTR asking and suggest this changing in open.lua:

[@serhat100 ](https://www.tnctr.com/profile/220094-serhat100/)said that:

_If we change the Winpe.lua codes like this, "terminal_output console \ n" .. 
I changed the order of the code "efi" and "pc" to the top. If you ask a1ive, I couldn't test but I think it should be_


local function gen_wimboot (wim)
local platform = grub.getenv ("grub_platform")
local iso_path = string.match (grub.getenv ("grubfm_file"), "^%([%w,]+%)(.*)$")
local cmd = "set installiso=\"" .. iso_path .. "\"\n" ..
**"terminal_output console\n" ..**
"tr --set=installiso \"/\" \"\\\\\"\n" ..
"loopback -m envblk ${prefix}/null.cpio\n" ..
"save_env -s -f (envblk)/null.cfg installiso\n" ..
"cat (envblk)/null.cfg\n" ..
"loopback wimboot ${prefix}/wimboot.gz\n" ..
"loopback install ${prefix}/install.gz\n"
if platform == "pc" then
cmd = cmd .. "set enable_progress_indicator=1\n" ..
"linux16 (wimboot)/wimboot\n" ..
"initrd16 newc:bootmgr:(wimboot)/bootmgr" ..
" newc:bootmgr.exe:(wimboot)/bootmgr.exe" ..
" newc:bcd:(wimboot)/bcd newc:boot.sdi:(wimboot)/boot.sdi" ..
" newc:null.cfg:(envblk)/null.cfg" ..
" newc:mount_x64.exe:(install)/mount_x64.exe" ..
" newc:mount_x86.exe:(install)/mount_x64.exe" ..
" newc:start.bat:(install)/silent.bat" ..
" newc:winpeshl.ini:(install)/winpeshl.ini" ..
" newc:boot.wim:\"" .. wim .. "\"\n" ..
"set gfxmode=1920x1080,1366x768,1024x768,800x600,auto\n" ..
"terminal_output gfxterm\n" ..
"boot\n"
else
cmd = cmd .. "set lang=en_US\n" ..
"wimboot @:bootmgfw.efi:(wimboot)/bootmgfw.efi" ..
" @:bcd:(wimboot)/bcd @:boot.sdi:(wimboot)/boot.sdi" ..
" @:null.cfg:(envblk)/null.cfg" ..
" @:mount_x64.exe:(install)/mount_x64.exe" ..
" @:mount_x86.exe:(install)/mount_x64.exe" ..
" @:start.bat:(install)/silent.bat" ..
" @:winpeshl.ini:(install)/winpeshl.ini" ..
" @:boot.wim:\"" .. wim .. "\"\n"

**Comment by farukgkc** [comment]
Thanks
