### ISSUE TITLE
G2FM Search&Find with Extension Files

### ISSUE THREAD

**Issue by crasadure** [a1ive/grub2-filemanager#203]
hi a1live;
can we add G2FM for search and files with extensions like vhd,iso,wim,img,..e.g 

can you add this property to G2FM for general using... these files are necassary files

**Search and Find Files(English)** : [Search_Find_File_with_extension_module(English).zip](https://github.com/a1ive/grub2-filemanager/files/4599746/Search_Find_File_with_extension_module.English.zip)

**Search and Find Files(Turkish)**: [Search_Find_File_with_extension_module(Turkish).zip](https://github.com/a1ive/grub2-filemanager/files/4599751/Search_Find_File_with_extension_module.Turkish.zip)

Captured Video Link: https://vimeo.com/416357039

**Comment by a1ive** [comment]
added.

**Comment by crasadure** [comment]
Thanks guy :)
