### ISSUE TITLE
Opening LUKS partition fails

### ISSUE THREAD

**Issue by thht** [a1ive/grub2-filemanager#208]
hi,
thanks for this great program!

I built the latest version from git and also tried the latest release. I am on UEFI amd64, so i chainload into grubfmx64.efi from grub.

It shows my non-encrypted partition just fine. However, when I go to the settings menu and tell it to open LUKS/GELI partitions, just nothing happens.

Any hint would be appreciated!
Thomas

**Comment by a1ive** [comment]
It seems that I forgot to addsome modules, now it should work. (but decryption is very slow). Please build from git.

**Comment by thht** [comment]
yes, that works now. thanks!
