### ISSUE TITLE
F2 and other function keys don't work after F (search)

### ISSUE THREAD

**Issue by steve6375** [a1ive/grub2-filemanager#214]
![image](https://user-images.githubusercontent.com/1469350/81981280-febe5980-9627-11ea-9bc4-ae53180fef85.png)
At this point, there is no Back menu entry and F2 does not work.
No choice but to switch off system or run one of the files.

**Comment by steve6375** [comment]
P.S. Feature would be more useful if we could type the start of the filename - e.g. win or ubu.

**Comment by steve6375** [comment]
Any chance to add a 'Back' entry to search.sh?
Also add a menu entry for user to type in first few letters of file name?
My USB drive has 50 .iso files - searching for .iso is useless.
If I search for .wim I get a list of 5 files - but I cannot then go back to main menu - I have to run select one of the .wim files which then runs immediately (because I have disabled secondary menu) so there is no way to go back.

**Comment by a1ive** [comment]
I will add it.
> P.S. Feature would be more useful if we could type the start of the filename - e.g. win or ubu.

Or we could search custom file extensions?

**Comment by steve6375** [comment]
I think start of name would be more useful. User probably won't remember exact filename extension anyway?
A search for 'ub' - could return
Ubuntu.iso
Ubuntux64.iso64
Ubuntu2_x64.cfg

Search would need to be case insensitive.
Preferably not show .grubfm files as these would not work using grubfm_open?

**Comment by steve6375** [comment]
is *ub*.* possible in grub2? Could then search for partial string in filename?

**Comment by a1ive** [comment]
> Search would need to be case insensitive.

this would be difficult. `regexp` command is case sensitive.

**Comment by steve6375** [comment]
so current search does not work for .ISO ?

**Comment by steve6375** [comment]
If user enters  string 'ub' - could you translate this into [Uu][Bb]' for regexp?

**Comment by a1ive** [comment]
then how to translate into wildcard?
ub*
UB*
uB*
Ub*

**Comment by steve6375** [comment]
*[Uu][Bb]*
???

**Comment by a1ive** [comment]
> `.*[Uu][Bb].*`
> ???

doesn't work.grub only supports '*' and '?' wildcard.

**Comment by steve6375** [comment]
Sorry - I thought this was regexp issue?

**Comment by a1ive** [comment]
both regexp and wildcard, I think.

**Comment by steve6375** [comment]
`  for file in ${srcdir}*.* ${srcdir}*/*.* ${srcdir}*/*/*.*;`

then use regexp to get files with  .*$searchstring.*
where $searchstring is  [Uu][Bb]
???

**Comment by a1ive** [comment]
> `for file in ${srcdir}*.* ${srcdir}*/*.* ${srcdir}*/*/*.*;`
> 
> then use regexp to get files with `.*$searchstring.*`
> where $searchstring is [Uu][Bb]
> ???

this looks good.but list *.* would be slow.

**Comment by steve6375** [comment]
current search.sh works from the current directory.
So it would depend on if user was currently at \  or  \_ISO folder.
P.S. Maybe useful to show current folder in 'Back' menu ??? This would show the user where the search is being started from too?

**Comment by steve6375** [comment]
For .iso search  and other extensions, could it search for `${srcdir}*.${ext}* `instead of `${srcdir}*.${ext}`

**Comment by a1ive** [comment]
I think we could re-write search function and interface with lua.
lua is more customizable and we could let users press a special key to stop searching if it takes too much time.

**Comment by steve6375** [comment]
OK
or alternative may be to ask user for extension type first - e.g. .iso
then search for `*.iso* `to get list
then ask user for partial string where default is * - e.g. ub
then search for [Uu][Bb] etc. to get final menuentry list?

**Comment by steve6375** [comment]
![image](https://user-images.githubusercontent.com/1469350/98236268-fc93e280-1f5a-11eb-96ba-4783f56a1a8b.png)
It is still annoying that when using F Search iso/wim/img/vhd/efi menu, there is no way to return to grubfm menu system when you get to the final menu. 
We canoot go back from here and have to press Ctrl-Alt-Del and reboot!

**Comment by a1ive** [comment]
I have rewritten the search function.
![深度截图_选择区域_20201130192821](https://user-images.githubusercontent.com/10670106/100605088-5d3bf280-3342-11eb-8f15-85cbfd0c0776.png)
![深度截图_选择区域_20201130192839](https://user-images.githubusercontent.com/10670106/100605093-5f9e4c80-3342-11eb-8ced-36624493de0e.png)
Now only the current directory and subdirectories are searched, and search is disabled to prevent crashing when no disk is selected.

**Comment by steve6375** [comment]
Can it look for .iso* instead of .iso ?
E2B uses file extension such as .isodef, .isomem, etc.

**Comment by a1ive** [comment]
now you can write your own search.sh, put it on usb stick (/boot/grubfm/search.sh)
![深度截图_选择区域_20201130195335](https://user-images.githubusercontent.com/10670106/100607312-bfe2bd80-3345-11eb-83f0-de3a3f9d6ab5.png)

**Comment by steve6375** [comment]
thanks :-)
