### ISSUE TITLE
blocklist的问题

### ISSUE THREAD

**Issue by ventoy** [a1ive/grub2-filemanager#215]
测试了下 v7.2.0 版本的 grubfm_multiarch.iso， 在命令行下执行 blocklist 好像有点问题。
下面两个图，一个是原始的blocklist命令打出来的，一个是 grubfm_multiarch 起来后命令行中blocklist 打出来的。
文件对应的是  rhel-8.0-x86_64-dvd.iso  大小是  7103053824   legacy BIOS模式

![11](https://user-images.githubusercontent.com/59477474/82115206-fdaa3b00-9793-11ea-8074-172ce6b332cc.PNG)
![22](https://user-images.githubusercontent.com/59477474/82115208-ff73fe80-9793-11ea-9d9e-5a87d82fc717.PNG)

**Comment by a1ive** [comment]
4800511[0-511] 这样是表示没有占满一个扇区，实际上是一样的。

**Comment by a1ive** [comment]
[0-511] [511-0] 这种情况应该是32位下文件大小超过 INT32_MAX，分多次读取造成的重复。
用 blocklist --set=aaa /file; echo $aaa 这样获得的 blocklist 是没有问题的。
![深度截图_选择区域_20200516170834](https://user-images.githubusercontent.com/10670106/82115850-e8371000-9797-11ea-8eb3-cff6e2d0dc6f.png)

**Comment by steve6375** [comment]
![image](https://user-images.githubusercontent.com/1469350/82115982-392a1280-975e-11ea-8421-d7f52dd5f3fe.png)

**Comment by ventoy** [comment]
blocklist --set=aaa /file; echo $aaa  这样是KO的。
不过大文件速度确实还是有点慢的。

![33](https://user-images.githubusercontent.com/59477474/82116348-b758da00-979b-11ea-93de-eb9d18366494.PNG)

**Comment by a1ive** [comment]
我看到你在获取 blocklist 时只获取前 1 GB 的数据，这样不会出问题吗？
https://github.com/ventoy/Ventoy/blob/84c500666addc8378fb03c3844bf6d25faf54a87/GRUB2/grub-2.04/grub-core/ventoy/ventoy.c#L1300

**Comment by ventoy** [comment]
那个是在一个循环里做的，每次1G，一直到最后读完。
在非exFAT的那几个系统中，还没来得及做底层优化，现在的方案和你当前的blocklist最终效果是一样的，但是现在测试看来，对于一些大文件，时间确实还是有点长。像这个镜像就需要将近10秒时间。

**Comment by a1ive** [comment]
用 `grub-mount` 直接挂载设备不知道是不是比 `dmsetup`  blocklist 更靠谱？
看文档好像 grub-mount 可以只读挂载任意 GRUB 支持的文件系统？
https://www.gnu.org/software/grub/manual/grub/html_node/Invoking-grub_002dmount.html

**Comment by ventoy** [comment]
因为文件系统挂载说到底是一个内核行为，必须内核支持才可以，光一个用户态程序是做不到的。
当前对于exfat/ntfs这种不是内核原生支持的系统，只有两种方法：一种是device-mapper，另外一种就是借助fuse

ventoy其实两者都可以用，但是默认是选择的前者，这是因为首先device-mapper是内核级别的，不损失效率。fuse是在用户态虚拟的文件系统，效率会损失不少。这个从正常使用时在Linux下挂载完exfat分区然后往里面拷贝ISO文件就能看出来，比如我测试的虚拟机环境，同样的硬盘
格式化为ext4文件系统，往里拷贝ISO文件，速度有 100MB/s 而exFat只能到30MB/s左右。

另一点，device-mapper的用户态程序很简单，便于静态编译，而fuse的用户态程序一般比较复杂，需要连接c库、pthread库等，
有很多linux发行版本的initramfs的环境极其简单，都没有c库。

grub-mount 也是基于 fuse 的，而且只能只读挂载。

之前也有好几个人邮件或者issue提到想要在启动Live系统后能往U盘里持久化保存一些配置信息，所以我正在考虑做一个模式，默认是device-mapper模式，启动后U盘只读；
切换之后，可以选择使用fuse，启动后U盘可正常读写。
