### ISSUE TITLE
Cygwin build in no commands error

### ISSUE THREAD

**Issue by farukgkc** [a1ive/grub2-filemanager#216]
Hi,
When I want to build via Cygwin, the following lines give no command error. What do I have to do to get over them? I ask for help.

> $ bash ./build.sh
> checking for gettext ... ok
> checking for xorriso ... ok
> checking for grub ... ok
> checking for mtools ... ok
> common files
> Language
> 1. Simplified Chinese
> 2. Traditional Chinese
> 3. English (United States)
> 4. Turkish
> 5. German
> 6. Vietnamese
> 7. Russian
> 8. Hebrew
> 9. Spanish
> 10. Polish
> 11. Ukrainian
> 12. French
> Please make a choice: 4
> tr_TR
> x86_64-efi
> copying afsplitter.mod
> copying crypto.mod
> copying cryptodisk.mod
> copying gcry_sha256.mod
> copying gcry_sha512.mod
> copying geli.mod
> copying json.mod
> copying luks.mod
> copying luks2.mod
> copying pbkdf2.mod
> 9909 blok
> i386-efi
> copying afsplitter.mod
> copying crypto.mod
> copying cryptodisk.mod
> copying gcry_sha256.mod
> copying gcry_sha512.mod
> copying geli.mod
> copying json.mod
> copying luks.mod
> copying luks2.mod
> copying pbkdf2.mod
> 7089 blok
> i386-pc
> copying acpi.mod
> copying affs.mod
> copying afs.mod
> copying all_video.mod
> copying aout.mod
> copying at_keyboard.mod
> copying bfs.mod
> copying bitmap.mod
> copying bitmap_scale.mod
> copying blocklist.mod
> copying bmp.mod
> copying bsd.mod
> copying btrfs.mod
> copying cat.mod
> copying cmp.mod
> copying commandline.mod
> copying conv.mod
> copying cpuid.mod
> copying crc.mod
> copying date.mod
> copying datehook.mod
> copying datetime.mod
> copying dd.mod
> copying disk.mod
> copying diskfilter.mod
> copying dm_nv.mod
> copying drivemap.mod
> copying elf.mod
> copying eval.mod
> copying expr.mod
> copying f2fs.mod
> copying fatfs.mod
> copying fdlibm.mod
> copying file.mod
> copying freedos.mod
> copying functional_test.mod
> copying gcry_md5.mod
> copying gcry_sha1.mod
> copying getkey.mod
> copying gfxmenu.mod
> copying gfxterm.mod
> copying gfxterm_background.mod
> copying gfxterm_menu.mod
> copying gptsync.mod
> copying grubfm.mod
> copying hashsum.mod
> copying hexdump.mod
> copying hfs.mod
> copying hfsplus.mod
> copying ini.mod
> copying jfs.mod
> copying jpeg.mod
> copying keylayouts.mod
> copying keystatus.mod
> copying legacycfg.mod
> copying loadenv.mod
> copying lsacpi.mod
> copying lsapm.mod
> copying lua.mod
> copying lvm.mod
> copying macho.mod
> copying mmap.mod
> copying mdraid09.mod
> copying mdraid09_be.mod
> copying msdospart.mod
> copying multiboot.mod
> copying multiboot2.mod
> copying nes.mod
> copying ntfscomp.mod
> copying offsetio.mod
> copying part_apple.mod
> copying part_bsd.mod
> copying partnew.mod
> copying parttool.mod
> copying password.mod
> copying pci.mod
> copying png.mod
> copying priority_queue.mod
> copying probe.mod
> copying procfs.mod
> copying progress.mod
> copying raid5rec.mod
> copying raid6rec.mod
> copying random.mod
> copying read.mod
> copying reboot.mod
> copying regexp.mod
> copying reiserfs.mod
> copying search_fs_uuid.mod
> copying search_label.mod
> copying sendkey.mod
> copying serial.mod
> copying setjmp.mod
> copying setkey.mod
> copying sleep.mod
> copying sortlib.mod
> copying squash4.mod
> copying stat.mod
> copying syslinuxcfg.mod
> copying terminfo.mod
> copying tga.mod
> copying time.mod
> copying tr.mod
> copying trig.mod
> copying true.mod
> copying vbe.mod
> copying vboot.mod
> copying ventoy.mod
> copying version.mod
> copying vga.mod
> copying vhd.mod
> copying video.mod
> copying video_bochs.mod
> copying video_cirrus.mod
> copying video_colors.mod
> copying video_fb.mod
> copying videoinfo.mod
> copying wimboot.mod
> copying xfs.mod
> copying xnu.mod
> copying zfs.mod
> copying zstd.mod
> copying afsplitter.mod
> copying crypto.mod
> copying cryptodisk.mod
> copying gcry_sha256.mod
> copying gcry_sha512.mod
> copying geli.mod
> copying json.mod
> copying luks.mod
> copying luks2.mod
> copying pbkdf2.mod
> copying pci.mod
> 15881 blok
> GNU xorriso 1.5.2 : RockRidge filesystem manipulator, libburnia project.
> 
> Drive current: -outdev 'stdio:grubfm.iso'
> Media current: stdio file, overwriteable
> Media status : is blank
> Media summary: 0 sessions, 0 data blocks, 0 data, 20.3g free
> Added to ISO image: directory '/'='/home/grub2-filemanager-ventoy/build'
> xorriso : UPDATE :      12 files added in 1 seconds
> xorriso : UPDATE :      12 files added in 1 seconds
> xorriso : UPDATE : Thank you for being patient. Working since 0 seconds.
> ISO image produced: 3885 sectors
> Written to medium : 3885 sectors at LBA 0
> Writing to 'stdio:grubfm.iso' completed successfully.
> 
> 16+0 kayıt girdi
> 16+0 kayıt çıktı
> 16777216 bytes (17 MB, 16 MiB) copied, 0,0210503 s, 797 MB/s
> **./build.sh: satır 180: mkfs.vfat: komut yok
> ./build.sh: satır 181: mmd: komut yok
> ./build.sh: satır 182: mmd: komut yok
> ./build.sh: satır 183: mcopy: komut yok
> ./build.sh: satır 184: mcopy: komut yok**
> GNU xorriso 1.5.2 : RockRidge filesystem manipulator, libburnia project.
> 
> Drive current: -outdev 'stdio:grubfm_multiarch.iso'
> Media current: stdio file, overwriteable
> Media status : is blank
> Media summary: 0 sessions, 0 data blocks, 0 data, 20.3g free
> Added to ISO image: directory '/'='/home/grub2-filemanager-ventoy/build'
> xorriso : UPDATE :      13 files added in 1 seconds
> xorriso : UPDATE :      13 files added in 1 seconds
> xorriso : UPDATE :  0.12% done
> ISO image produced: 12077 sectors
> Written to medium : 12077 sectors at LBA 0
> Writing to 'stdio:grubfm_multiarch.iso' completed successfully.

**Comment by a1ive** [comment]
Please build it under Linux. (Cygwin and msys2 is not Linux!)
You could install WSL on Win10.

**Comment by farukgkc** [comment]
Thanks.
