### ISSUE TITLE
No Danish DA-DK language

### ISSUE THREAD

**Issue by steve6375** [a1ive/grub2-filemanager#218]
Please create entry for Danish.
User Torben (tskalshoej) wishes to add translation for it.

**Comment by a1ive** [comment]
added.

**Comment by steve6375** [comment]
Please can you add a Danish keyboard scan code file.
keys are the same as Swedish keyboard file - just may need a few edits to name inside the file.

**Comment by steve6375** [comment]
[KBD_DANISH.zip](https://github.com/a1ive/grub2-filemanager/files/4640125/KBD_DANISH.zip)
