### ISSUE TITLE
It is possible to add Ventoy to main build with a setting to enable/disable it?

### ISSUE THREAD

**Issue by steve6375** [a1ive/grub2-filemanager#220]
Now ventoy 1.0.10 can support first partition as fat/ext/ntfs/exfat etc. it would be nice to add it to the release build but maybe add a switch to enable it so that the /boot/grubfm/config file can enable it in menus? Does it alter the way grubfm functions a lot (too much) to make it not compatible?

**Comment by a1ive** [comment]
Why we have to add a switch?
Why not just enable it by default?
It doesn't affect anything.

**Comment by steve6375** [comment]
No extra  Boot ISO (ventoy) option added to Secondary Menu?

**Comment by steve6375** [comment]
If you think it is stable enough to have it always enabled then it's OK.

**Comment by a1ive** [comment]
> No extra Boot ISO (ventoy) option added to Secondary Menu?

We need to add an extra menu.ventoy is not stable enough,and it doesn' work on many isos.

**Comment by steve6375** [comment]
yes - that is why I suggested that the entry can be enabled or disabled by using a setting in config file perhaps? So it is easy for users to test ventoy or disable it.
