### ISSUE TITLE
If attempt to UEFI64 boot a non-EFI ISO with Ventoy cannot return to menu

### ISSUE THREAD

**Issue by steve6375** [a1ive/grub2-filemanager#223]
![image](https://user-images.githubusercontent.com/1469350/82724477-629eed00-9cce-11ea-8b8a-42394c55c595.png)
You need to reboot the system.
Should we test for correct \EFI\BOOT\ .EFI file  (or MAC EFI file) in vt_test.sh ?

**Comment by a1ive** [comment]
> Should we test for correct \EFI\BOOT\ .EFI file (or MAC EFI file) in vt_test.sh ?
Ventoy is not stable enough.Sometimes it can't found the boot file on some hardware.
