### ISSUE TITLE
WinPE ISO fails to UEFI64-boot using map -t CD

### ISSUE THREAD

**Issue by steve6375** [a1ive/grub2-filemanager#224]
Download
https://we.tl/t-NlKqgJqtbw
This ISO uses winpeshl.ini to launch the app directly, so it does not work if we change winpeshl.ini.
So we must use normal EFI boot (partnew\Easy2Boot) but

map -t CD   does not work (vdisk error)

![image](https://user-images.githubusercontent.com/1469350/82791812-4f268a00-9e66-11ea-8296-91b21bf9a0c3.png)

This works.
set grubfm_file=(loop)/Sources/Boot.wim
	      wimboot @:bootmgfw.efi:(wimboot)/bootmgfw.efi \
              @:bcd:(wimboot)/bcd \
              @:boot.sdi:(wimboot)/boot.sdi \
              @:boot.wim:"${grubfm_file}";

MBR booting is OK

**Comment by a1ive** [comment]
> map -t CD does not work (vdisk error)

This ISO doesn't support UEFI.

> This ISO uses winpeshl.ini to launch the app directly, so it does not work if we change winpeshl.ini.

But how can we know which WinPE use winpeshl.ini and which not?

**Comment by steve6375** [comment]
It doesn't support UEFI boot even though there are UEFI boot files present - the ISO does not UEFI boot from VBox either!

Since the ISO does not UEFI boot, then the user could extract the wim file and just boot from that.
