### ISSUE TITLE
Acronis TrueImage ISO 2020 PE UEFI64 fails to boot using Ventoy option

### ISSUE THREAD

**Issue by steve6375** [a1ive/grub2-filemanager#225]
You can download free trial from https://www.acronis.com/en-gb/homecomputing/thanks/acronis-true-image-2020/

2019 17750 version has same issue (PE based).

If add ISO to a Ventoy drive (on exFAT partition or NTFS partition) then MBR and UEFI boot OK.

But if add to an a1ive grubfm drive (on NTFS partition) then Ventoy option does not work.

I have created a USB flash drive with agFM v1.51v beta and E2B v2.04c beta.
For testing: Acronis_TrueImage_2020_25700_PE_x64.iso on real system.
On old Legacy BIOS PC: E2B > agFM > Acronis > Boot ISO (Ventoy) works OK.
On **UEFI** PC, Secureboot disabled, CSM disabled:
**agFM > Acronis > Boot ISO (Ventoy) > Blue Screen! In VMware also Blue Screen.**
agFM > Acronis > Boot ISO (partnew) works OK.
With original Ventoy USB Flash drive, Acronis ISO works OK on real system and VMware ( legacy and UEFI).

**Comment by a1ive** [comment]
I removed ventoy from project.
It doesn't have better compatibility than partnew/map/loopback.

**Comment by steve6375** [comment]
BUT is has two big advantages
1. Contiguous files are not required
2. Can be used from a write-protected USB drive
so it is a valuable asset.
