### ISSUE TITLE
Help with string compare please

### ISSUE THREAD

**Issue by steve6375** [a1ive/grub2-filemanager#226]
![image](https://user-images.githubusercontent.com/1469350/82836612-bc660980-9ebe-11ea-9178-e23356deb385.png)
```
	echo ${grubfm_disk} (current)
	hexdump -s 0x1be -n 0x40 (${grubfm_disk})0+1 xx
	hexdump -s 0x1fe -n 2    (${grubfm_disk})0+1
	echo ${grubfm_disk} (new)
	hexdump -s 0x1be -n 0x40 (${grubfm_disk})$myLBA+1 yy
	hexdump -s 0x1fe -n 2    (${grubfm_disk})$myLBA+1
	echo
	echo $xx
	echo $yy
	if [ "${xx}" = "${yy}" ]; then echo SAME; fi
	read
```

if run from a .cfg file it reports 'SAME' when the strings are different!

**Comment by steve6375** [comment]
I think /x00 is being interpreted as End of String maybe>

Found a fix by using
`	if test ( @${xx} == @${yy} ); then echo SAME;fi`

**Comment by a1ive** [comment]
> Found a fix by using
> ` if test ( @${xx} == @${yy} ); then echo SAME;fi`

I don't think this will work.
The GRUB interpreter can't handle raw data.
This is not a bug, but a limitation.
Why not use Lua?
![Screenshot_20200526_162120](https://user-images.githubusercontent.com/10670106/82877662-102f2c00-9f6d-11ea-88f7-06911e5f6a9c.png)

**Comment by steve6375** [comment]
`if test ( @${xx} == @${yy} ); then echo SAME;fi`
this seems to work.

Ideally I would like to compare two sectors. Is this possible using cmp?
cmp (hd0)0+1 (hd0)30+1   ????
How do I use this in an if test ?

**Comment by steve6375** [comment]
I need to get the start sector and position of each of the four partition tables from the MBR (LBA0).
Then perform a test to see if there are any gaps between each partition of more than 8MB.

e.g. If ptn1 starts > 8MB then fail
if ptn2 starts > 8MB after end of ptn1 then fail
if ptn3 starts > 8MB after end of ptn2 then fail
if ptn4 starts > 8MB after end of ptn3 then fail
Can you give me some pointers on how to get these values with lua and how to do maths needed?
(sorry to be a nuisance!).

**Comment by steve6375** [comment]
OK - managed it! Thanks.

**Comment by steve6375** [comment]
P.S. As far as I can tell
if test ( @${xx} == @${yy} ); then echo SAME;fi
works OK, but
if test ( "@${xx}" == "@${yy}" ); then echo SAME;fi
does not work correctly.
Same for using [ "${xx}" = "${yy} ]; then echo SAME;fi      >> FAILS
if you put in double-quotes then it doesn't work, but if you don't use double-quotes then the comparison works correctly.

**Comment by a1ive** [comment]
> I need to get the start sector and position of each of the four partition tables from the MBR (LBA0).
Then perform a test to see if there are any gaps between each partition of more than 8MB.

e.g. If ptn1 starts > 8MB then fail
if ptn2 starts > 8MB after end of ptn1 then fail
if ptn3 starts > 8MB after end of ptn2 then fail
if ptn4 starts > 8MB after end of ptn3 then fail
Can you give me some pointers on how to get these values with lua and how to do maths needed?
(sorry to be a nuisance!).

I think the best way is writing a new module using c.

**Comment by steve6375** [comment]
I have done it using lua now. thanks.
