### ISSUE TITLE
Boot esd file directly

### ISSUE THREAD

**Issue by KaMyKaSii** [a1ive/grub2-filemanager#228]
Is there a way to load Windows installation setup using .esd files without converting to .iso first? Linux file command returns that the esd file is a common "Windows imaging (WIM) image"

**Comment by a1ive** [comment]
install.esd and install.wim are not bootable.

**Comment by KaMyKaSii** [comment]
> install.esd and install.wim are not bootable.

Is there no way even if they have bootable files inside?
![Capturar](https://user-images.githubusercontent.com/17092335/83145807-c3159c00-a0cb-11ea-9a72-b3cdfc52a63c.PNG)

**Comment by a1ive** [comment]
Yes. if you create a zip with these files, you can't boot the zip either.
Windows boot manager only supports wim and vhd.

**Comment by KaMyKaSii** [comment]
> Yes. if you create a zip with these files, you can't boot the zip either.
> Windows boot manager only supports wim and vhd.

I understand. Thanks for clarifying
