### ISSUE TITLE
Ventoy boot option + Windows 10 ISO not using XML file

### ISSUE THREAD

**Issue by steve6375** [a1ive/grub2-filemanager#230]
I can pick an XML file after using the ventoy boot option but the XML file is not found by ventoy in WinPE (even if no spaces in XML file).
[ventoy.log](https://github.com/a1ive/grub2-filemanager/files/4715948/ventoy.log)
Log file attached.
`[2020/06/02 09:42:46.591] auto install script D:(hd0,msdos1)/_ISO/WINDOWS/WIN10/NOKEYTEST.xml not exist`

**Comment by a1ive** [comment]
Ventoy module will be removed.
