### ISSUE TITLE
pfsense v2.4.5 ISO load_install error

### ISSUE THREAD

**Issue by crasadure** [a1ive/grub2-filemanager#232]
hi a1live;
some user our forum are asking that how can boot and install **pfsence linux firewall program** with G2FM

pfsence download link :
https://nyifiles.pfsense.org/mirror/downloads/pfSense-CE-2.4.5-RELEASE-amd64.iso.gz

ı captured a video about the problem: https://vimeo.com/425218620
can you help about this issue?

**Comment by a1ive** [comment]
UEFI or BIOS?
grub2 can't boot FreeBSD in UEFI.

**Comment by crasadure** [comment]
On BIOS system...

**Comment by a1ive** [comment]
I have no idea ...
partnew doesn't work either.

**Comment by crasadure** [comment]
Hi a1live;
If there is no improvement in booting the pfsense iso application, I can close this topic...

**Comment by a1ive** [comment]
we can still keep this open.maybe ventoy project could find a solution.

**Comment by crasadure** [comment]
Hi a1live;
I think ventoy had solved pfsense installation problem at ventoy v1.0.18
Did you test it?
May be you can add ventoy solution to your project...
**New iso support (total 450+)**
*pfSense-CE-2.5.0-DEVELOPMENT-amd64-latest.iso (Legacy + UEFI) 
*pfSense-CE-2.4.5-RELEASE-p1-amd64.iso (Legacy + UEFI) 
*pfSense-CE-2.3.5-RELEASE-amd64.iso (Legacy) *pfSense-CE-2.3.4-RELEASE-amd64.iso (Legacy) *pfSense-CE-2.3.5-RELEASE-i386.iso (Legacy)

**Comment by steve6375** [comment]
If it helps, Easy2Boot can boot it by changing the file extension to .isoBSD. It does it by using a special partition image and patching it in to the MBR partition table together with another small partition image.
![image](https://user-images.githubusercontent.com/1469350/93013697-c19cb080-f5a2-11ea-9103-18b8a3095d10.png)
![image](https://user-images.githubusercontent.com/1469350/93013704-e09b4280-f5a2-11ea-8514-c9e11b611ae8.png)
It can also be done by using a MemStick partition image.
https://www.easy2boot.com/add-payload-files/freebsd/

**Comment by steve6375** [comment]
Ventoy can also boot it direct from the ISO. Ventoy can be added to a E2B+agFM USB drive.

**Comment by crasadure** [comment]
Ventoy test result
https://www.vimeo.com/458315723
Ventoy solved this problem  🙂

I think, I can close this ISSUE.
