### ISSUE TITLE
[QUESTION] Are sparse .img files bootable?

### ISSUE THREAD

**Issue by KaMyKaSii** [a1ive/grub2-filemanager#235]
I tried to boot a img file of a 4GB USB stick and it booted normally. Now I'm trying to boot a 64GB USB stick sparse image (just 23GB is actually real data) and the screen is stucked in "Start image: 0xca568a18". Maybe I just need to wait it load, I don't know
![IMG_20200614_180422_1](https://user-images.githubusercontent.com/17092335/84604174-8509cd80-ae6a-11ea-8f9c-ac70b48463a3.jpg)

**Comment by a1ive** [comment]
> Are sparse .img files bootable?
No. Only "raw image" ISO/img/vhd are supported.
> Now I'm trying to boot a 64GB USB
The virtual disk created by grub2 is on UEFI firmware level, and it will disappear when an OS exits BootServices, so if you are trying to load OS from img, you need to write a virtual disk driver.

**Comment by KaMyKaSii** [comment]
> No. Only "raw image" ISO/img/vhd are supported.
>
But the file is a raw copy of a disk, just [sparse](https://en.wikipedia.org/wiki/Sparse_file) written to the output file

> The virtual disk created by grub2 is on UEFI firmware level, and it will disappear when an OS exits BootServices, so if you are trying to load OS from img, you need to write a virtual disk driver.
>
I'm not a developer, I was just playing around with the features

**Comment by a1ive** [comment]
> A raw disk image is a file containing the raw data from a disk, which might be a floppy disk, hard disk, or optical disc. The data is simply a dump of the binary content (sequence of bytes) contained in each track and sector of the disk, **with no additional metadata (except what may be part of the physical or logical format of the disk, such as control headers that are part of a physical disk format or metadata that is built into the filesystem, present on the original disk)**.
