### ISSUE TITLE
New install.gz via imdisk

### ISSUE THREAD

**Issue by abdullah-erturk** [a1ive/grub2-filemanager#240]
The imgdrive application was not very healthy, so I edited the imdisk application unattended.

Thanks to this file, both Windows installation iso files and WinPE iso files will be directly mounted to the Y:\ drive.

Master a1ive, please add this work to your project.

[install.gz](https://github.com/a1ive/grub2-filemanager/files/4850496/install.gz)

**Comment by steve6375** [comment]
Does this run Setup Repair so that the user can repair a Windows OS?
To run Repair you need  to run X:\Setup.exe.

**Comment by abdullah-erturk** [comment]
It does not run direct repair, if Windows iso file is selected, it connects to Y: \ drive and goes directly to the setup screen. If WinPE iso file is selected, it connects WinPE iso file to Y: \ drive.

Thanks to any WinPE (eg Sergei etc) Repairs can be run.

**Comment by a1ive** [comment]
Thanks, but I don't think it's a good idea to mount ISO to Y:\.
see #101

**Comment by abdullah-erturk** [comment]
The drive letter Y: \ must be universal, at least because it is a letter used in the most common WinPE studies :)

**Comment by a1ive** [comment]
It's not universal. I've found many Chinese WinPE won't load programs if we mount ISO to Y:\.

**Comment by abdullah-erturk** [comment]
I understand I'm already making a joke :)

**Comment by abdullah-erturk** [comment]
I can edit it as A:\ or B:\ if you want.

My preference is A:\

Because in my WinPE work, all programs run from the drive B:\  :)
