### ISSUE TITLE
How do I start WinPE using Grub2

### ISSUE THREAD

**Issue by Fffdmin** [a1ive/grub2-filemanager#244]
WinPE is supported on the latest version of GrubFM, does it mean that Grub2 also supports starting WinPE (without external programs). Based on this question, there are two questions

1. How does GrubFm do this
2. Can I do this using grub.cfg？

**Comment by a1ive** [comment]
You need to use my modified version of grub2 (https://github.com/a1ive/grub)
Boot ISO:
Use map module (See https://github.com/a1ive/grub2-filemanager/blob/master/boot/grubfm/rules/iso/map.sh)
```
map --type=CD /path/to/winpe.iso
boot
```
Boot WIM:
Extract `bootmgfw.efi` from WIM file or ESP partition and copy it to your pendrive.
1. Use wimboot module (See https://github.com/a1ive/grub2-filemanager/blob/master/boot/grubfm/rules/wim/ntboot.sh)
`wimboot --rawbcd @:bootmgfw.efi:/path/to/bootmgfw.efi @:boot.wim:/path/to/winpe.wim`
2. Use ntboot module (See https://github.com/a1ive/grub2-filemanager/blob/master/boot/grubfm/rules/wim/ntboot.sh)
`ntboot --wim --efi=/path/to/bootmgfw.efi /path/to/winpe.wim`

看起来你应该是国人，可以参考这两篇帖子：
http://bbs.wuyou.net/forum.php?mod=viewthread&tid=417233
http://bbs.wuyou.net/forum.php?mod=viewthread&tid=417545
