### ISSUE TITLE
Translation, localization to Arabic and suggestions for improvement ترجمة وتعريب للعربية واقتراحات للتحسين

### ISSUE THREAD

**Issue by thamermousa** [a1ive/grub2-filemanager#246]
Translation, localization to Arabic and suggestions for improvement ترجمة وتعريب للعربية واقتراحات للتحسين

شكرا على الاسطوانة الرائعة grubfm_multiarch.iso
Thanks for the great CD grubfm_multiarch.iso

أفضل طريقة لعمل التمهيد
The best way to make a boot

وسيتم الاستغناء عن خدمات البرامج الاخرى
The services of other programs will be dispensed with

> ------------------------------ translate this file to arabic ----------------------------------------

ترجمة هذا الملف الى العربية
translate this file to arabic
"C:\Users\toandto\Downloads\grub2-filemanager-7.3.3\lang\fm.pot"

لكني لا أعرف كيف أضيفه إلى grubfm_multiarch.iso
But I don't know how to add to grubfm_multiarch.iso

هل أترجم هذا الملف أم لا fm.pot
Do I translate this file or not fm.pot

صور دعم اللغة العربية موجود
Arabic language support pictures are present

Like these pictures

![2020-08-13_012131](https://user-images.githubusercontent.com/3912594/90074864-bdac1300-dd04-11ea-847e-cee151e0fb4a.jpg)

![555](https://user-images.githubusercontent.com/3912594/90074870-c56bb780-dd04-11ea-8a8f-9db963110e85.jpg)

> -------------------------------- proposal --------------------------------------

Is it possible to customize the program of work of the cylinder as we want

Font change and enlargement
Change the background
Add clock and date, analog or digital
First item is to boot to Windows
and Partition Magic minimized
Windows xp minimized With these tools , 7-Zip , qemu , BOOTICE , rufus , windirstat

شكرا لكم
thank you

**Comment by a1ive** [comment]
Hi, I've added Arabic to crowdin, you can now translate it online.
https://crowdin.com/translate/grub2-filemanager/16/en-ar
But grub2 doesnt have good support for RTL languages.

**Comment by thamermousa** [comment]
**Thank you @a1ive A1ive**

And thanks for adding the Arabic language

RTL support , There is no problem with it since the letters are not broken

Translate the file fm.pot to Arabic 97% ar_AR

[ar_AR.zip](https://github.com/a1ive/grub2-filemanager/files/5069189/ar_AR.zip)
