### ISSUE TITLE
error wimboot

### ISSUE THREAD

**Issue by thamermousa** [a1ive/grub2-filemanager#250]
I downloaded the latest version grubfm_multiarch.iso

And I tried to boot from
WinPE10_8_Sergei_Strelec_x86_x64_2020.06.09_English.iso
and
PE10x64.wim

Gives me this error
![2020-08-22_215604](https://user-images.githubusercontent.com/3912594/90963734-f8f7d000-e4c2-11ea-8559-b74c12705bd1.jpg)

**Note that in the versions before it was working fine**

**Release 7.3.4**

**out of grub4dos**
title grubfm_multiarch.iso to Boot USB HDD SSD M.2 BIN VHD IMG WIM ISO all \n\n Boot grubfm_multiarch.iso to iso all ( grubfm_multiarch.iso 23.1 MB ) \n\n\t\t\t https://github.com/a1ive/grub2-filemanager/releases 
ls /grubfm_multiarch.iso || find --set-root /grubfm_multiarch.iso
map --heads=0 --sectors-per-track=0 /grubfm_multiarch.iso (0xff) || map --heads=0 --sectors-per-track=0 --mem /grubfm_multiarch.iso (0xff)
map --hook
chainloader (0xff)

title grubfm.iso  to Boot USB HDD SSD M.2 BIN VHD IMG WIM ISO all \n\n Boot grubfm.iso to iso all ( grubfm.iso 23.1 MB ) \n\n\t\t\t https://github.com/a1ive/grub2-filemanager/releases
map --mem /grubfm.iso (0xff)
map --hook
chainloader (0xff)

**Comment by a1ive** [comment]
I've already found this issue and deleted the v7.3.4 release.
