### ISSUE TITLE
Request: for Ventoy integration

### ISSUE THREAD

**Issue by steve6375** [a1ive/grub2-filemanager#256]
Could F5.sh check for \EFI\BOOT\ventoyx64.efi first please?
This would allow a user to add all the Ventoy files and folders to an existing grubfm FAT32 partition 2 (just rename ventoy \EFI\BOOT\BOOTX64.efi to ventoyx64.efi so that it does not overwrite the existing grubfm efi boot file).

Also, I cannot find a way to mbr boot the core.img of ventoy (on an Easy2Boot stick, pressing F5 in MBR mode just reloads grub4dos).
I have tried adding core.img from the Ventoy download and then using
multiboot (hd0,2)/ventoy/core.img
but it does not work. Any ideas?

**Comment by a1ive** [comment]
> This would allow a user to add all the Ventoy files and folders to an existing grubfm FAT32 partition 2 (just rename ventoy \EFI\BOOT\BOOTX64.efi to ventoyx64.efi so that it does not overwrite the existing grubfm efi boot file).

Ventoy files are not portable.You can't copy it from another disk.

**Comment by steve6375** [comment]
Hi - yes you can! - I have UEFI64 Ventoy working.

partition 1 = ISOs
partition 2 = grubfm + ventoy files

![image](https://user-images.githubusercontent.com/1469350/91633177-1dc9d700-e9de-11ea-9373-1c7b24c3e349.png)

Very simple!
Just copy partition 2 of Ventoy to grubfm partition 2  (but rename ventoy bootx64 to ventoyx64.efi first)

![image](https://user-images.githubusercontent.com/1469350/91633208-61bcdc00-e9de-11ea-963d-945155df479d.png)
![image](https://user-images.githubusercontent.com/1469350/91633217-6b464400-e9de-11ea-9e21-33179227b117.png)

**Comment by a1ive** [comment]
> I have UEFI64 Ventoy working.
> 
> partition 1 = ISOs
> partition 2 = grubfm + ventoy files
> 
> ![image](https://user-images.githubusercontent.com/1469350/91633177-1dc9d700-e9de-11ea-9373-1c7b24c3e349.png)
> 
> Very simple!
> Just copy partition 2 of Ventoy to grubfm partition 2 (but rename ventoy bootx64 to ventoyx64.efi first)
> 
> ![image](https://user-images.githubusercontent.com/1469350/91633208-61bcdc00-e9de-11ea-963d-945155df479d.png)
> ![image](https://user-images.githubusercontent.com/1469350/91633217-6b464400-e9de-11ea-9e21-33179227b117.png)

Have you tried to boot the ISO with it？(Linux ISO/ non-contiguous WinPE ISO)
https://www.ventoy.net/en/doc_disk_layout.html

**Comment by steve6375** [comment]
I tried Ubuntu and Acronis ISOs - OK.

**Comment by crasadure** [comment]
> I tried Ubuntu, Win8 and Acronis ISOs - OK.
> Partition 1 = NTFS
> Partition 2 = FAT32
hi @steve6375 ;
 @[awengers44](https://www.tnctr.com/profile/24080-awengers44/) from TNCTR has developed your project below TNCTR link.you can examine this project from this link
--> [https://www.tnctr.com/topic/766182-ventoy-boot-grubfm-modifiye/](url)
Ventoy Boot + Grubfm + Modified Project Download Link --> [https://yadi.sk/d/2TZR8Yk0-BGLog](url)

Captured Video-Turkish Language (Ventoy Boot + Grub File Manager Modified MultiBoot System Setup)
[https://youtu.be/2RP54UEiCrM](url)

**Comment by steve6375** [comment]
That is booting grubfm from Ventoy. It is not what I want.
I want to boot Ventoy from grubfm.

**Comment by steve6375** [comment]
Something like this for F5.sh would be great

```
if [ -n "${aioboot}" ];
then
  if [ "${grub_platform}" = "efi" ];
  then
    chainloader -t (${aioboot})/efi/boot/boot${EFI_ARCH}.efi;
  else
    multiboot (${aioboot})/AIO/grub/i386-pc/core.img;
  fi;
  boot;
elif [ -n "${ventoy}" ];
then
  if [ "${grub_platform}" = "efi" ];
  then
    if [ -f (${ventoy})/efi/boot/VENTOY${EFI_ARCH}.efi ]; then chainloader -t (${ventoy})/efi/boot/VENTOY${EFI_ARCH}.efi;
	else
	chainloader -t (${ventoy})/efi/boot/BOOT${EFI_ARCH}.efi;  fi
  fi
  else
    regexp --set=1:vtdisk '(hd[0-9]+)[0-9,]*' "${ventoy}";
    chainloader (${vtdisk})+1;
  fi;
  boot;
else
  configfile ${prefix}/netboot.sh;
fi;
```

**Comment by steve6375** [comment]
The core.img file at https://github.com/ventoy/Ventoy/blob/master/INSTALL/grub/i386-pc/core.img
now works!
So users could add this to the /ventoy folder on partition 2 and you could boot it using F5.sh

```
root $ventoy
multiboot /core.img
```

So now we can MBR or UEFI-boot to Ventoy from grubfm.
Could you modify F5.sh to use these two files  (core.img and ventoyx64.ef) if they exist please?
It means users can easily add Ventoy to their grubfm partition.

```
if [ -n "${aioboot}" ];
	then
	if [ "${grub_platform}" = "efi" ];
		then
		chainloader -t (${aioboot})/efi/boot/boot${EFI_ARCH}.efi;
	else
		multiboot (${aioboot})/AIO/grub/i386-pc/core.img;
	fi;
	boot;
elif [ -n "${ventoy}" ];
	then
	if [ "${grub_platform}" = "efi" ];
		then
		if [ -f (${ventoy})/efi/boot/VENTOY${EFI_ARCH}.efi ]; 
			then 
			chainloader -t (${ventoy})/efi/boot/VENTOY${EFI_ARCH}.efi;
		else
			chainloader -t (${ventoy})/efi/boot/BOOT${EFI_ARCH}.efi;  
		fi
	else
		set root=$ventoy
		if [ -f /ventoy/core.img ]; 
			then 
			multiboot /ventoy/core.img; 
		else
			regexp --set=1:vtdisk '(hd[0-9]+)[0-9,]*' "${ventoy}";
			chainloader (${vtdisk})+1;
		fi;
	fi;
	boot;
else
  configfile ${prefix}/netboot.sh;
fi;
```

**Comment by crasadure** [comment]
Hi steve6375;
@serhat100 from TNCTR  he had merged this two system on one multiboot platform. You can examine this project from below link:
**Altay Grub2fm + Ventoy Multiboot V8.4 2020**
https://www.tnctr.com/topic/370214-altay-grub2fm-ventoy-multiboot-v84-2020/


Project download link:
https://yadi.sk/d/yEb6OFFGdBfpDA
rar password :aLTay

**Comment by steve6375** [comment]
https://rmprepusb.blogspot.com/2020/09/agfm-v157-beta-with-ventoy-support.html
How to add Ventoy to Easy2Boot USB drive.

**Comment by a1ive** [comment]
Now grubfm will load /ventoy/core.img and /efi/boot/ventoyXXX.efi

**Comment by devdevadev** [comment]
Thanks a lot a1ive for providing Ventoy support in grubfm...
