### ISSUE TITLE
Ventoy2Disk ?

### ISSUE THREAD

**Issue by ero35** [a1ive/grub2-filemanager#257]
Ventoy2Disk
https://github.com/ventoy/Ventoy/releases

can similar be done?

**Comment by a1ive** [comment]
> can similar be done?

what?

**Comment by ero35** [comment]
> > can similar be done?
> 
> what?

installation and update tool for usb

**Comment by a1ive** [comment]
See https://github.com/a1ive/grub2-filemanager#usb-installers
