### ISSUE TITLE
Grub2FM New Theme

### ISSUE THREAD

**Issue by abdullah-erturk** [a1ive/grub2-filemanager#258]
I made some changes to the existing theme for Grub2 File Manager, I think it was nice :)

To use, delete the themes folder in the \boot\grubfm\ directory in the Grub2 File Manager source files, then copy the themes folder from the ZIP archive to the \boot\grubfm\ directory and compile.

[themes.zip](https://github.com/a1ive/grub2-filemanager/files/5149532/themes.zip)

![1](https://user-images.githubusercontent.com/54866587/91705372-87381a00-eb85-11ea-94b1-1ec71a57edcd.JPG)
![2](https://user-images.githubusercontent.com/54866587/91705375-87d0b080-eb85-11ea-9386-01258dd73e3f.JPG)
![3](https://user-images.githubusercontent.com/54866587/91705379-88694700-eb85-11ea-87ce-645a72e268bc.JPG)
![4](https://user-images.githubusercontent.com/54866587/91705380-8901dd80-eb85-11ea-8496-be3ce6125c58.JPG)

**Comment by steve6375** [comment]
The standard slack theme can be changed by using a \boot\grubfm\config file and copying your theme files to the \boot\grubfm\themes\abdullah folder. **You do not need to recompile.**
The new theme should contain a dock folder and icons folder.

**config file**

```
set mytheme=abdullah
	export theme_std="(${user})/boot/grubfm/themes/${mytheme}/theme.txt";
	export theme_fm="(${user})/boot/grubfm/themes/${mytheme}/fm.txt";
	export theme_info="(${user})/boot/grubfm/themes/${mytheme}/info.txt";
	export theme_help="(${user})/boot/grubfm/themes/${mytheme}/help.txt";
	export theme=$theme_std
#themes must not contain spaces - test
	if ! [ -f "$theme" ] ; then echo "ERROR: Can't find $theme" ; read ; fi
grubfm
```

**Comment by a1ive** [comment]
Thanks, but as @steve6375 said, you could change your theme and don't need to recompile.
