### ISSUE TITLE
div.mod error when Legacy booting

### ISSUE THREAD

**Issue by steve6375** [a1ive/grub2-filemanager#260]
![image](https://user-images.githubusercontent.com/1469350/92310878-273cdb80-efaa-11ea-8847-baafa34b5782.png)

**Comment by crasadure** [comment]
Hi steve6375;
Add this modüle to "**arc/legacy/insmod.lst**" file
![hata-duzeltme](https://user-images.githubusercontent.com/54566818/92312148-c374db80-efc6-11ea-9cff-4b672e127090.jpg)

And compile g2fm with source code again

**Comment by steve6375** [comment]
sure - I am just reporting the issue.

**Comment by a1ive** [comment]
I can't reproduce it on my pc.

**Comment by steve6375** [comment]
Message is very quick - try booting using QEMU as it is slower!

**Comment by a1ive** [comment]
I think this problem is related to CPU/OS. some do not support 64-bit signed integer division, so div.mod is needed.
