### ISSUE TITLE
Help: Trying to boot VHD with VeraCrypt encrypted Windows installation

### ISSUE THREAD

**Issue by justfra** [a1ive/grub2-filemanager#262]
Hello,

I'm using grubfm_multiarch.iso with Ventoy and I'm able to properly boot Windows within a VHD.
I've been struggling for 2 days trying to boot the same Windows installation after having encrypted the Windows partition with VeraCrypt.
I can boot it fine with VirtualBox and the EFI system partition is unencrypted.

I've tried mounting the VHD with "vhd -p" command and then using "grubfm_open" command as well as "ntboot" command from the grub2fm console by passing VeraCrypt BcsBoot.efi and the path to the VHD file although that doesn't seem to work.
I get the following errors:

InitFS Unsupported
Could not start bootmgfw.efi

Even when I specify my own efi file via the ntboot command it still seems like is trying to load the bootmgfw.efi

I even tried packaging the VeraCrypt efi boot files inside a zip file and modifying the ntboot.sh but that lead nowhere, too.

Any help in the right direction would be appreciated.

Thanks,
F.

**Comment by a1ive** [comment]
VeraCrypt encrypted Windows VHD/VHDX files are not supported.

**Comment by a1ive** [comment]
Maybe you need to modify 3rd-party windows nt loader (e.g. [quibble](https://github.com/maharmstone/quibble)) to implement this feature.
