### ISSUE TITLE
How can i boot grubfm at  resolution 1920*1080 with /boot/grubfm/config?

### ISSUE THREAD

**Issue by lujisheng** [a1ive/grub2-filemanager#266]
Thanks for your grubfm!

When i boot grubfm, the resolution is set to 1024*768, the default value.
I want change it  to 1920*1080, this resolution is much better for me.
I write this code in /boot/grub/config,  but nothing change.
`set gfxmode=1920x1080,1600x1200,1280x1024,1024x768,auto;`

How to write it  in /boot/grubfm/config?

**Comment by a1ive** [comment]
terminal_output console
export gfxmode=1920x1080
terminal_output gfxterm

**Comment by lujisheng** [comment]
It works!
Thank you very much.
