### ISSUE TITLE
Current build unstable?

### ISSUE THREAD

**Issue by steve6375** [a1ive/grub2-filemanager#270]
For the last few days, grubfm menu system is unstable.
e.g. navigate to a few sub-folders and then go back to root and I get a black screen (but cursor down/up moves cursor up and down invisible menu). Sometimes it will not go back to top root folder or go 'up' a level. Sometimes menu items are missing.
I am testing with grubfmx64.efi in VBOX and same on real system.
2020-09-18 ok
2020-09-22 unstable

The issue seems to disappear if I do not use a \boot\grubfm\config file. Even if I use a config file but do not load an initial  menuentry .txt file it is unstable. Some boots seem OK, other times I get problems.

2020-09-18 seems OK though - same config file, etc.
Have you had any 'weird' menu issues recently?

**Comment by steve6375** [comment]
grubfm.iso (MBR) gives same issue. - e.g. blank, all black screen, no cursor after navigating through a few folders and back again.

**Comment by nguyentumine** [comment]
Maybe you should build each commit to find the cause https://github.com/a1ive/grub/commits/master

**Comment by a1ive** [comment]
https://github.com/a1ive/grub/issues/61
https://github.com/a1ive/grub/commit/1198083e7fd759339ab8538cf050dce8a564fbe6

**Comment by Serhat-Tnctr-24** [comment]
> Son birkaç gündür grubfm menü sistemi kararsız.
> örneğin, birkaç alt klasöre gidin ve sonra köke geri döndüm ve siyah bir ekran görüyorum (ancak imleç aşağı / yukarı, imleci görünmez menü yukarı ve aşağı hareket ettirir). Bazen üst kök klasöre geri dönmez veya bir seviye 'yukarı' çıkmaz. Bazen menü öğeleri eksik olabilir.
> VBOX'ta grubfmx64.efi ile gerçek sistemde test ediyorum.
> 2020-09-18 tamam
> 2020-09-22 kararsız
> 
> Bir \ boot \ grubfm \ config dosyası kullanmazsam sorun ortadan kalkıyor gibi görünüyor. Bir yapılandırma dosyası kullansam, ancak ilk menü giriş .txt dosyasını yüklemesem bile, bu kararsız. Bazı botlar iyi görünüyor, diğer zamanlarda sorun yaşıyorum.
> 
> 2020-09-18 yine de iyi görünüyor - aynı yapılandırma dosyası, vb.
> Son zamanlarda herhangi bir 'tuhaf' menü sorununuz oldu mu?



> grubfm.iso (MBR) gives same issue. - e.g. blank, all black screen, no cursor after navigating through a few folders and back again.

Yes I faced the same problem in Legacy bios. All versions after 18.19.2020 have the same problem.

**Comment by steve6375** [comment]
> Maybe you should build each commit to find the cause https://github.com/a1ive/grub/commits/master

I am not sure how to do this? How do I download different versions?
Or I can test any grubfmx64.efi you want me to try?

**Comment by nguyentumine** [comment]
> > Maybe you should build each commit to find the cause https://github.com/a1ive/grub/commits/master
> 
> I am not sure how to do this? How do I download different versions?
> Or I can test any grubfmx64.efi you want me to try?

1. https://github.com/a1ive/grub/commit/2b957b5d99bac5b3bdd7db453ce036eaed3cbdf7
2. Browse files
3. Download ZIP

**Comment by nguyentumine** [comment]
@steve6375 I'm not sure if it breaks the other functions
[grubfmx64.efi.zip](https://github.com/a1ive/grub2-filemanager/files/5326595/grubfmx64.efi.zip)

**Comment by a1ive** [comment]
> @steve6375 I'm not sure if it breaks the other functions
> [grubfmx64.efi.zip](https://github.com/a1ive/grub2-filemanager/files/5326595/grubfmx64.efi.zip)

@nguyentumine revert this patch https://github.com/a1ive/grub/commit/1198083e7fd759339ab8538cf050dce8a564fbe6 ?

**Comment by nguyentumine** [comment]
> > @steve6375 I'm not sure if it breaks the other functions
> > [grubfmx64.efi.zip](https://github.com/a1ive/grub2-filemanager/files/5326595/grubfmx64.efi.zip)
> 
> @nguyentumine revert this patch [a1ive/grub@1198083](https://github.com/a1ive/grub/commit/1198083e7fd759339ab8538cf050dce8a564fbe6) ?

```
void
grub_normal_clear_menu (void)
{
  grub_menu_t menu = grub_env_get_menu ();

  if (!menu)
    menu = grub_zalloc (sizeof (*menu));

  menu->entry_list = NULL;
  menu->size=0;
}
```

**Comment by a1ive** [comment]
> > > @steve6375 I'm not sure if it breaks the other functions
> > > [grubfmx64.efi.zip](https://github.com/a1ive/grub2-filemanager/files/5326595/grubfmx64.efi.zip)
> > 
> > 
> > @nguyentumine revert this patch [a1ive/grub@1198083](https://github.com/a1ive/grub/commit/1198083e7fd759339ab8538cf050dce8a564fbe6) ?
> 
> ```
> void
> grub_normal_clear_menu (void)
> {
>   grub_menu_t menu = grub_env_get_menu ();
> 
>   if (!menu)
>     menu = grub_zalloc (sizeof (*menu));
> 
>   menu->entry_list = NULL;
>   menu->size=0;
> }
> ```

if (!menu)
return;

**Comment by nguyentumine** [comment]
> > > > @steve6375 I'm not sure if it breaks the other functions
> > > > [grubfmx64.efi.zip](https://github.com/a1ive/grub2-filemanager/files/5326595/grubfmx64.efi.zip)
> > > 
> > > 
> > > @nguyentumine revert this patch [a1ive/grub@1198083](https://github.com/a1ive/grub/commit/1198083e7fd759339ab8538cf050dce8a564fbe6) ?
> > 
> > 
> > ```
> > void
> > grub_normal_clear_menu (void)
> > {
> >   grub_menu_t menu = grub_env_get_menu ();
> > 
> >   if (!menu)
> >     menu = grub_zalloc (sizeof (*menu));
> > 
> >   menu->entry_list = NULL;
> >   menu->size=0;
> > }
> > ```
> 
> if (!menu)
> return;

```
void
grub_normal_clear_menu (void)
{
  grub_menu_t menu = grub_env_get_menu ();

  if (menu)
    return;

  menu = grub_zalloc (sizeof (*menu));
  menu->entry_list = NULL;
  menu->size=0;
}
```
Right?

**Comment by a1ive** [comment]
> > > > > @steve6375 I'm not sure if it breaks the other functions
> > > > > [grubfmx64.efi.zip](https://github.com/a1ive/grub2-filemanager/files/5326595/grubfmx64.efi.zip)
> > > > 
> > > > 
> > > > @nguyentumine revert this patch [a1ive/grub@1198083](https://github.com/a1ive/grub/commit/1198083e7fd759339ab8538cf050dce8a564fbe6) ?
> > > 
> > > 
> > > ```
> > > void
> > > grub_normal_clear_menu (void)
> > > {
> > >   grub_menu_t menu = grub_env_get_menu ();
> > > 
> > >   if (!menu)
> > >     menu = grub_zalloc (sizeof (*menu));
> > > 
> > >   menu->entry_list = NULL;
> > >   menu->size=0;
> > > }
> > > ```
> > 
> > 
> > if (!menu)
> > return;
> 
> ```
> void
> grub_normal_clear_menu (void)
> {
>   grub_menu_t menu = grub_env_get_menu ();
> 
>   if (!menu)
>     return;
> 
>   menu = grub_zalloc (sizeof (*menu));
>   menu->entry_list = NULL;
>   menu->size=0;
> }
> ```
> 
> Right?

remove this line:
menu = grub_zalloc (sizeof (*menu));

**Comment by nguyentumine** [comment]
@a1ive ok
@steve6375

[grubfmx64.efi.zip](https://github.com/a1ive/grub2-filemanager/files/5326886/grubfmx64.efi.zip)

**Comment by steve6375** [comment]
That seems stable so far...

**Comment by nguyentumine** [comment]
> That seems stable so far...
I have tested with E2B but there is no "sometimes" as you say
https://github.com/a1ive/grub/issues/61

**Comment by steve6375** [comment]
Is this fixed now? Can Master build be updated?

**Comment by a1ive** [comment]
> Is this fixed now? Can Master build be updated?

I'm still on vacation and don't have a computer.
@nguyentumine could create a pr and then I will merge it, and github actions will compile and release a new build.

**Comment by Serhat-Tnctr-24** [comment]
yes very nice and stable master

**Comment by steve6375** [comment]
Thanks!
