### ISSUE TITLE
how do I access files on USB from the grub2 console?

### ISSUE THREAD

**Issue by toddfraser88** [a1ive/grub2-filemanager#273]
Hi,

I'm using grub2-filemanager as a part of the Easy2boot project. I want to use grub2 because unlike grub4dos grub2 has a feature that allows you to patch ACPI table before booting the OS, so I wanted to use this feature.

When I boot into grub2-filemanager and open the grub2 console I type -

acpi /

I press Tab and I get a listing of the files located in the grub2fm.iso but I don't know how to go from here to my USB drive to start applying the ACPI tables I stored there.

So How do I navigate from the grub2fm.iso to my USB drive from the grub2 console?

**Comment by steve6375** [comment]
Just specify a path
E.g. (hd0,1)/xxx.yy if on the first partition of the usb drive.

**Comment by toddfraser88** [comment]
got it,
Thanks.
