### ISSUE TITLE
Request to edit code in gfxmenu.mod file

### ISSUE THREAD

**Issue by crasadure** [a1ive/grub2-filemanager#274]
Hi a1ive;

question and request : ( @serhat100 from TNCTR )

It makes more sense if it is embedded in **gfxmenu.mod**

`hbox{
left = 35%%
top = 16%%
label {text = "Grub2 File Manager" color = "red" }
}`

Even if the background picture is changed by adding these codes, can the text text be permanently in the menu?

**Comment by a1ive** [comment]
No, I don't like this feature.
