### ISSUE TITLE
UEFI Boot menu screen

### ISSUE THREAD

**Issue by Tnctr-altay-24** [a1ive/grub2-filemanager#277]
Hello @a1ive master, when I boot Secureboot enable windows.iso in UEFI, the loading screen slips, I wonder if there is a solution for this. The secureboot Disable screen is working properly in UEFI. Thank you

![IMG](https://user-images.githubusercontent.com/72962883/96558695-bab13e00-12c4-11eb-8347-f006cf9970a2.jpg)

**Comment by a1ive** [comment]
I have no idea ...

**Comment by steve6375** [comment]
Can you try a different monitor?

**Comment by Tnctr-altay-24** [comment]
> Farklı bir monitör deneyebilir misin?
> Ya da belki o noktada monitörü kapatıp tekrar açın.

I turned the monitor off and on a few times at that time, but nothing changed

I tested it on a different pc yes it is ok
![IMG_2](https://user-images.githubusercontent.com/72962883/96583320-328f6080-12e5-11eb-9fe1-ace9541a852c.jpg)

**Comment by steve6375** [comment]
Different PC? or same PC and different monitor?

**Comment by Tnctr-altay-24** [comment]
I have also tested a different pc.

**Comment by steve6375** [comment]
So it is a monitor problem?

**Comment by Tnctr-altay-24** [comment]
> Merhaba @ a1ive master, Secureboot'u UEFI'de windows.iso'yu etkinleştirdiğimde yükleme ekranı kayıyor, bunun için bir çözüm olup olmadığını merak ediyorum. Secureboot Disable ekranı UEFI'de düzgün çalışıyor. teşekkür ederim
> 
> ![IMG](https://user-images.githubusercontent.com/72962883/96558695-bab13e00-12c4-11eb-8347-f006cf9970a2.jpg)

If I can connect this monitor to a different pc and test it, then I guess it will be understood that the problem is caused by the monitor.

**Comment by Tnctr-altay-24** [comment]
the monitor has a resolution of 1440x900

**Comment by Tnctr-altay-24** [comment]
I wonder if resolution is added to the bcd menu.

![2020-10-20_162437](https://user-images.githubusercontent.com/72962883/96592763-68d2dd00-12f1-11eb-97e3-224b4804a796.png)

**Comment by nguyentumine** [comment]
Wimboot module forces the resolution at 1920x1080, that might be the cause

**Comment by Tnctr-altay-24** [comment]
> > ![IMG](https://user-images.githubusercontent.com/72962883/96558695-bab13e00-12c4-11eb-8347-f006cf9970a2.jpg)
> 
> If I can connect this monitor to a different pc and test it, then I guess it will be understood that the problem is caused by the monitor. the monitor has a resolution of 1440x900

Hello to the masters; I also start installing the system with a resolution of 1440x900 from grub2 file manager.
When I first select the resolution 1024x768 from the F4 settings menu, go back and set the resolution to 1440x900 and boot the iso, the screen gets better. But when I want to adjust the resolution from the F4 settings menu, it comes to the screen as mini mode.

submenu $"Resolution (R): ${mode_current}" --class screen --hotkey "r" {
  set lang=en_US;
  terminal_output gfxterm; 
# terminal_output console;                # i am changing here
  menuentry "AUTO DETECT" {
    set gfxmode=auto;
    terminal_output gfxterm;
    set lang=${grubfm_lang};
    configfile ${prefix}/settings.sh;
  }
  for item in ${mode_list};
  do
    menuentry "${item}" {
      set gfxmode=${1};
      terminal_output gfxterm;
      set lang=${grubfm_lang};
      configfile ${prefix}/settings.sh;
    }
  done;
}

When I apply the change, it leaves the mini mode, but the above operations are useless.

**Comment by Tnctr-altay-24** [comment]
hello @a1ive master,
I set the resolution to 1440x900 in the script, the resolution of the menu is set to 1440x900, but I press F1 the resolution appears to be 1024x768 videomode -c mode_current; command is set to 1024x768 please can you help with this?

**Comment by steve6375** [comment]
Same problem with both types of monitor?

**Comment by Tnctr-altay-24** [comment]
No Philips monitor too

**Comment by Tnctr-altay-24** [comment]
https://github.com/a1ive/grub2-filemanager/issues/280#issuecomment-717018659

**Comment by Tnctr-altay-24** [comment]
Dear @a1ive ;
Can you please help me fix the error on the screen.
While it does not get an error with grub2 files dated 28.07.2020, it appears in updates after this date. When I boot incorrectly, the screen of loading the iso file is average, but when I use the grub2 files dated 28.07.2020, it boots without showing an error message. In this, when loading the iso file, the bcd menu scrolls to the right of the screen. Can you please help me with this?
![grub2](https://user-images.githubusercontent.com/72962883/98218765-36fe7f00-1f5d-11eb-9385-674bdbdff75d.jpg)

**Comment by a1ive** [comment]
> error: symbol `xxx`not found.

You're mixing modules from different versions of grub2， don't do that.

**Comment by Tnctr-altay-24** [comment]
Thanks for the response
The error that occurred when I booted from Uefi with fde_ld.efi and installed sbpolicy.mod dated 05.11.2020 and grubfmx64.efi that I created with the same date, so I use the same versions.

**Comment by a1ive** [comment]
fde_ld.efi and sbpolicy.mod are from different version of grub!

**Comment by Tnctr-altay-24** [comment]
fde_ld.efi dated March 18, 2018 and grub2 modules dated 05.11.2020
