### ISSUE TITLE
Query: How to open boot files under Windows now they are compressed?

### ISSUE THREAD

**Issue by steve6375** [a1ive/grub2-filemanager#279]
I see that the latest build compresses the files.
Previously I could open grubfmx64.efi or grubfm.iso in 7zip, but now I don't seem to be able to open them to extract the files under Windows.
Is it possible to use a more compatible compression setting or can you suggest how I can extract files under Windows now?
I have the latest version of 7z which is supposed to support .xz but it does not seem to understand the compression used.

**Comment by a1ive** [comment]
![深度截图_选择区域_20201020190531](https://user-images.githubusercontent.com/10670106/96578483-d7bb3080-1307-11eb-8e1c-f5bd146a35f3.png)
7-Zip "Open Inside \#"
![深度截图_选择区域_20201020190741](https://user-images.githubusercontent.com/10670106/96578690-31235f80-1308-11eb-9f95-6196162bdaaf.png)
Just decompress this xz with 7-Zip and ignore the errors.

**Comment by steve6375** [comment]
Got it. thanks!

**Comment by a1ive** [comment]
> I have the latest version of 7z which is supposed to support .xz but it does not seem to understand the compression used.

The size of a disk should be an integer multiple of 512 bytes, grub-mkimage fills 0's to make up the size when embedding a memdisk. xz format is sensitive to file size, so use a little trickery when unzipping it. The main reason I use the xz format is that it reduces the file size.
