### ISSUE TITLE
config

### ISSUE THREAD

**Issue by Tnctr-altay-24** [a1ive/grub2-filemanager#280]
When Grub2FM is created with build.sh, the config file does not function. Is this an error please tell me?

**Comment by steve6375** [comment]
Is this a new issue? It was OK last week.

**Comment by Tnctr-altay-24** [comment]
It happened after applying compression memdisk.xz.

**Comment by steve6375** [comment]
MBR or UEFI32 or UEFI64?

**Comment by Tnctr-altay-24** [comment]
in both

**Comment by steve6375** [comment]
so if you place a command like
echo HERE
read
in /boot/grubfm/config file - then you do not see  'HERE' on screen?

**Comment by Tnctr-altay-24** [comment]
F1-F2-F3 .. & Shortcut keys remain active when I select an iso file, it becomes active.

**Comment by steve6375** [comment]
I have just rebuilt using build.sh.
config file works OK for me.
Please try with simple config file as above.

**Comment by Tnctr-altay-24** [comment]
Steve6375 master is a grub2-filemanager based multiboot that I made inspired by your E2b multiboot. I'll make a short video tomorrow

**Comment by Tnctr-altay-24** [comment]
video link https://yadi.sk/i/2jLxBcd7NMQsWQ
Hello @steve6375 master,
If attention is paid in the first seconds of the video, the shortcut keys do not appear and the keys are inactive. Shortcut keys appear when I select any iso file (I choose ventoy-1.0.25-livecd.iso) from the disc. It becomes active.
While the resolution in F1 appears to be 1024x768, the resolution is set to 1440x900 with the F4 hotkey, in this case the mini mode is shifted to the right of the screen, which is https://github.com/a1ive/grub2-filemanager/issues/277#issue-725324715 causes. With the F4 hotkey, we select the resolution as 1440x900, the mini mode is centered on the screen and the menu in the iso elevation is also centered. I am using google translation because I do not know English. Sorry for this situation please.

**Comment by steve6375** [comment]
You have modified grubfm - it is using a different theme. If you have a problem, you must use unmodified grubfm.

**Comment by Tnctr-altay-24** [comment]
The config file reports (error: no media in 'hd2'). Could you check the config file if I ask?


[config.zip](https://github.com/a1ive/grub2-filemanager/files/5444997/config.zip)

**Comment by steve6375** [comment]
looks OK
Why not add

echo HERE
read

at the bottom of it and see if the message appears before 'HERE' is printed?

**Comment by Tnctr-altay-24** [comment]
yes it seems. Thanks for your help. I close.
