### ISSUE TITLE
DLC 2019 no longer MBR-booting

### ISSUE THREAD

**Issue by steve6375** [a1ive/grub2-filemanager#281]
![image](https://user-images.githubusercontent.com/1469350/97560831-212a1080-19d7-11eb-8f4a-39c48fdaa9b5.png)

UEFI64 is OK

**Comment by steve6375** [comment]
Gandalf ISo also not booting
Strelec not booting
Win10 ISO not booting
Something broken ??

**Comment by a1ive** [comment]
out of memory?
BIOS wimboot requires 2 * size of WIM RAM

**Comment by steve6375** [comment]
Sorry _ I did have 128GB! Just DLC 2019 not booting.
![image](https://user-images.githubusercontent.com/1469350/97561854-acf06c80-19d8-11eb-8742-8b5a5aea33da.png)

**Comment by steve6375** [comment]
User reported that it used to work when using earlier version of E2B+agFM 1.55   2020-06-08

**Comment by a1ive** [comment]
ok I will download dlc2019 and test.

**Comment by steve6375** [comment]
Build 2020-08-23 fails (as screenshot above)
Build 2020-08-02 fails (as screenshot above_
Build 2020-08-01 fails (different msg - bootmgr not found)
Build 2020-06-21 OK
Build 2020-06-08 OK

**Comment by a1ive** [comment]
plz try.
[grubfm.iso.gz](https://github.com/a1ive/grub2-filemanager/files/5462955/grubfm.iso.gz)

**Comment by steve6375** [comment]
![image](https://user-images.githubusercontent.com/1469350/97688516-226c4380-1a92-11eb-892f-0c3167e03306.png)
Looks good.
Will test some more. It has now been reported that even some Win8/10 ISOs did not MBR boot before.

**Comment by a1ive** [comment]
> It has now been reported that even some Win8/10 ISOs did not MBR boot before.

uing this test grubfm.iso?

**Comment by steve6375** [comment]
no. I will ask user to test.

**Comment by a1ive** [comment]
I did find some bugs in the code, but I don't know why it works under uefi and not under bios.

**Comment by steve6375** [comment]
The user reports new version is OK on both DLC and a AIO_win10 ISO which failed before.
My testing also all OK. :-)

**Comment by steve6375** [comment]
great work!

**Comment by nguyenhathaitrong** [comment]
since grubfm.iso v7.3.3 updated boot, i can no longer boot grubfm.iso v7.2, point to black screen and go to grub shell Why grubfm.iso v7.3.3 always load winiso instead of installiso

**Comment by nguyenhathaitrong** [comment]
I load grubfm.iso from hdd

**Comment by nguyenhathaitrong** [comment]
When booting grubfm.iso from hdd to install windows.iso, after boot.wim has loaded, windows.iso cannot mount due to the error no iso / wim / imdisk

**Comment by steve6375** [comment]
How can this be reproduced? How was USB prepared? What ISO are you booting? Where is ISO located? etc.
