### ISSUE TITLE
F3 Boot menu showing 'Boot Windows NT'  wimboot entries

### ISSUE THREAD

**Issue by steve6375** [a1ive/grub2-filemanager#282]
![image](https://user-images.githubusercontent.com/1469350/97792714-9f560500-1bd9-11eb-84c4-083fb4168914.png)
All these try to boot wimboot

MBR boot to grubfm - trying to boot efi file???
![image](https://user-images.githubusercontent.com/1469350/97792722-cad8ef80-1bd9-11eb-942d-83e5ea436063.png)

Previous version identified Windows version, etc.

**Comment by a1ive** [comment]
> MBR boot to grubfm - trying to boot efi file???

It's bootmgr.exe renamed to bootmgfw.efi, to avoid using `if $grub_platform = efi ...`.

**Comment by steve6375** [comment]
But why is it showing Windows NT for all partitions even ext2 or empty partitions?
Previous versions identified windows version, etc. Please test yourself.

**Comment by a1ive** [comment]
> But why is it showing Windows NT for all partitions even ext2 or empty partitions?
> Previous versions identified windows version, etc. Please test yourself.

It's a bug.
grubfm uses `ntversion` to detect whether windows exists.
https://github.com/a1ive/grub2-filemanager/blob/5c60e2e727106ed62280702646d7b759827ac4f8/boot/grubfm/osdetect.sh#L117
latest grub commit moved this command to another module and I forgot to add it.

**Comment by a1ive** [comment]
If multiple different versions of Windows are installed (e.g. win7 &
win10), will there be multiple winre.wim?

**Comment by steve6375** [comment]
Yes - if a recovery partition or folder was created during install. There is also a 'backup' copy at \Windows\System32\Recovery folder

```
When you install Windows by using Windows Setup, WinRE is configured like this:

During Windows Setup, Windows prepares the hard drive partitions to support WinRE.
Windows initially places the WinRE image file (winre.wim) in the Windows partition, in the \Windows\System32\Recovery folder.
Before delivering the PC to your customer, you can modify or replace the WinRE image file to include additional languages, drivers, or packages.

During the specialize configuration pass, the WinRE image file is copied into the recovery tools partition, so that the device can boot to the recovery tools even if there's a problem with the Windows partition.
When you deploy Windows by applying images, you must manually configure the hard drive partitions. When WinRE is installed on a hard drive, the partition must be formatted as NTFS.

Add the baseline WinRE tools image (winre.wim) to a separate partition from the Windows and data partitions. This enables your users to use WinRE even if the Windows partition is encrypted with Windows BitLocker Drive Encryption. It also prevents your users from accidentally modifying or removing the WinRE tools.

We recommend that you store the recovery tools in a dedicated partition, directly after the Windows partition.

For more info about configuring hard drive partitions, see Configure UEFI/GPT-Based Hard Drive Partitions or Configure BIOS/MBR-Based Hard Drive Partitions.
```

**Comment by steve6375** [comment]
The backup copy may not be fully operational however as it should be in a Recovery partition or folder and also there should be the 'tools' in the same folder\volume.

**Comment by steve6375** [comment]
![image](https://user-images.githubusercontent.com/1469350/97798999-f502cf80-1c22-11eb-80e3-4a2c0af54775.png)
The file could also be in C:\Recovery if there is no recovery partition (some OEMS use different folder names!).

**Comment by steve6375** [comment]
Nice! thanks.
