### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by skulldealer** [a1ive/grub2-filemanager#284]
Can your tool be used to extract an iso file contents into a folder in a usb in grub? 

翻译
可以使用您的工具将iso文件内容提取到grub的usb文件夹中吗？

**Comment by a1ive** [comment]
这个东西本来就是单文件的,也不需要安装器。
直接用其他bootloader启动对应架构的efi文件或者iso文件就行。

**Comment by skulldealer** [comment]
我想要一些可以在grub的iso文件中提取文件的工具，用于ventoy。

**Comment by skulldealer** [comment]
我想要一个可以在grub引导期间从iso文件中提取数据的工具吗？

**Comment by a1ive** [comment]
提取到哪里？

**Comment by skulldealer** [comment]
在以iso格式存储的位置

**Comment by a1ive** [comment]
grub2的文件系统驱动都是只读的, 一般不能进行写入。
如果iso位于fat或exfat分区, 是可以利用fatfs写入的。
https://a1ive.github.io/grub2_fatfs_zh.html
但是我不建议这样做。固件提供的磁盘写入功能可能不稳定, 而且速度比较慢。

**Comment by skulldealer** [comment]
可以在grub中将文件从exfat移到fatfs。

**Comment by skulldealer** [comment]
我很快就会需要您的帮助。继续检查ventoy github页面。你对grub有很好的了解。您将需要尽快帮助ventoy作者开发ventoy的新代码。它很紧急。请保持更新

**Comment by skulldealer** [comment]
Please check new issue thread on ventoy. 

请检查通风管上的新发行螺纹。
