### ISSUE TITLE
No such command: /MAP

### ISSUE THREAD

**Issue by SScrew** [a1ive/grub2-filemanager#287]
Legacy-BIOS grub4dos booted grubfm.iso
Then grubfm boot other ISO in map mode, and the following error will appear:
**No such command: /MAP**

![iso-map.jpg](https://i.loli.net/2020/11/08/uPrD2FyqVOahJMX.jpg)

**Comment by a1ive** [comment]
can't reproduce.

type `ls` and press 'enter'
type `ls (` then press 'tab'

and see what happens.
![深度截图_选择区域_20201107194537](https://user-images.githubusercontent.com/10670106/98440157-0a4f9080-2132-11eb-8cdb-2889889f17bf.png)

**Comment by SScrew** [comment]
ls shows the contents of the UD partition of my udisk
my udisk has three partitions: UD, normal and EFI

![ls.jpg](https://i.loli.net/2020/11/08/2Ejr65SuJxlsQTM.jpg)

**Comment by a1ive** [comment]
Looks like you're supposed to be Chinese.
> Legacy-BIOS grub4dos booted grubfm.iso

磁盘列表里没有grub4dos启动grubfm.iso时生成的虚拟光驱(cd)啊，这是为什么？你是怎么启动grubfm.iso的？

**Comment by SScrew** [comment]
发几张图给你看下：
1、UD分区文件结构
![1.png](https://i.loli.net/2020/11/08/G3jYUxncvCmK4Ru.png)
2、menu.lst 中引导grubfm.iso的写法
我写的是 0xff，不知道为什么没有cd，grub显示的还是ud的 0x23
![2.png](https://i.loli.net/2020/11/08/A9vYWT6d2zGL4qQ.png)
3、U盘启动后的界面
![3.JPG](https://i.loli.net/2020/11/08/DeTpbB9KkM2w1Wg.jpg)
4、成功引导 grubfm.iso
![4.JPG](https://i.loli.net/2020/11/08/87m6wVIdkySpei2.jpg)

**Comment by a1ive** [comment]
我重现不了你的情况。
`ls (0xff)/`试试

**Comment by SScrew** [comment]
![](http://img2.krsjyy.com/uploads/2011/6b0c727f2a556623.jpg)

**Comment by a1ive** [comment]
好，应该是grub4dos的bug，不过在一般的电脑上不会出现。我想想有没有解决办法。

**Comment by a1ive** [comment]
[grubfm_pc.zip](https://github.com/a1ive/grub2-filemanager/files/5553776/grubfm_pc.zip)
请测试。

**Comment by SScrew** [comment]
It's working, Thanks!
