### ISSUE TITLE
Ventoy and aioboot

### ISSUE THREAD

**Issue by nguyenhathaitrong** [a1ive/grub2-filemanager#289]
How to chainloader from Ventoy to Aioboot and vice versa in efi Platform and PC Platform

**Comment by a1ive** [comment]
The question you are asking is not relevant to this project.
You should look for help under AIO-Boot or Ventoy's project.
https://www.ventoy.net/en/plugin_grubmenu.html

**Comment by nguyenhathaitrong** [comment]
Sorry. Thank you very much
