### ISSUE TITLE
grubfm.iso now boots to grub2 console - no menu

### ISSUE THREAD

**Issue by steve6375** [a1ive/grub2-filemanager#292]
Latest build.sh produces  grubfm.iso and grubfm_pc.iso  - what are these two files???
grubfm.iso no longer booting to menu?

grubfm.iso
![image](https://user-images.githubusercontent.com/1469350/99876016-e7ba7e80-2beb-11eb-8aba-8a581de879f8.png)

**Comment by a1ive** [comment]
multiboot /grubfm.elf

**Comment by steve6375** [comment]
grubfm_pc.iso seems to work. So has the name of the ISO changed?
![image](https://user-images.githubusercontent.com/1469350/99879080-0592de00-2c02-11eb-82d1-1033a63338af.png)

![image](https://user-images.githubusercontent.com/1469350/99879093-44c12f00-2c02-11eb-9359-ca182920ea09.png)

**Comment by a1ive** [comment]
You didn't upgrade grub to latest

**Comment by a1ive** [comment]
grubfm.iso (grubfm.elf) is i386-multiboot build to replace old i386-pc build.
grubfm_pc.iso is i386-pc build.

**Comment by steve6375** [comment]
![image](https://user-images.githubusercontent.com/1469350/99879233-5bb45100-2c03-11eb-9426-4774adc57d3b.png)
???

**Comment by a1ive** [comment]
plz upgrade grub to 2.04.

**Comment by steve6375** [comment]
![image](https://user-images.githubusercontent.com/1469350/99879284-c6fe2300-2c03-11eb-9689-82f9b0168bf1.png)
I am just running build script

**Comment by a1ive** [comment]
I mean grub-mkimage in your host os.

**Comment by steve6375** [comment]
sorry - I dont understand. I am not very experienced with grub2 compilation.

I just run a script which runs 
update_grub2.sh
build.sh

This what has always worked before.
What command do I need to type? Why does the host need to be updated? How?

**Comment by steve6375** [comment]
build.sh seems to work now. thanks!

**Comment by steve6375** [comment]
![image](https://user-images.githubusercontent.com/1469350/99884121-8f9f6e80-2c23-11eb-9eb1-2670571e2e45.png)
grubfm.iso now does not boot correctly?
I am using config file and it gives errors now

Should I be using grubfm_pc.iso instead with E2B and config file?

**Comment by steve6375** [comment]
$bootdev is showing as S?
![image](https://user-images.githubusercontent.com/1469350/99884207-4a2f7100-2c24-11eb-9c50-07ce0a7172d3.png)

**Comment by steve6375** [comment]
P.S. I still don't understand the difference between  grubfm.iso and grubfm_pc.iso?
When is grubfm.iso used and when is grubfm_pc.iso used?

**Comment by a1ive** [comment]
The bootdev issue should be fixed.
> I still don't understand the difference between grubfm.iso and grubfm_pc.iso?

grubfm_pc.iso is the old grubfm.iso from the i386-pc platform.
grubfm.iso/grubfm.elf is the experimental boot file for the i386-multiboot platform.
> When is grubfm.iso used and when is grubfm_pc.iso used?

You can still use grubfm_pc.iso, because the i386-multiboot platform is **experimental**.

The i386-multiboot platform has a number of advantages over the i386-pc platform.
(1) i386-pc core.img has size limit, while i386-multiboot does not.
(2) You can boot grubfm.elf either under legacy BIOS, or under IA32 UEFI and X64 UEFI (although many features are not yet implemented or are not available).
Legacy BIOS:
```
multiboot /grubfm.elf
multiboot2 /grubfm.elf # not recommended
```
UEFI:
```
multiboot --fake-bios /grubfm.elf # not recommended
multiboot2 /grubfm.elf
```

**Comment by steve6375** [comment]
thanks. :-)
So previously  grubfm.iso was the legacy bootable ISO, but now it has been renamed to grubfm_pc.iso (!) and grubfm.iso is now a different thing which is a Beta? Why did you change the name? Why not keep the name the same and have a grubfm_multi.iso for the new ISO?
Boot examples in README.md show to use grubfm.iso not grubfm_pc.iso. Also no mention is made of multiarch or other isos and efi files or elf or which ones are Beta status or the multiboot command?
Is https://github.com/a1ive/grub/blob/master/docs/grub.texi the best reference for your grub?

**Comment by a1ive** [comment]
> So previously grubfm.iso was the legacy bootable ISO, but now it has been renamed to grubfm_pc.iso (!) and grubfm.iso is now a different thing which is a Beta?

Yes.
> Boot examples in README.md show to use grubfm.iso not grubfm_pc.iso.

Same usage. The difference between the two is not noticeable to the average user.
> Why not keep the name the same and have a grubfm_multi.iso for the new ISO?

Users may confuse grubfm_multi.iso with grubfm_multiarch.iso.

**Comment by a1ive** [comment]
> Is https://github.com/a1ive/grub/blob/master/docs/grub.texi the best reference for your grub?

I couldn't find any documentation or articles about i386-multiboot, and all research was done by reading the source code.
Currently i386-multiboot already does 99% of the functionality of the original i386-pc version in BIOS and is almost indistinguishable in use, so documentation is not needed.
My ultimate goal is to unify the BIOS/UEFI with one file: grubfm.elf.

**Comment by Tnctr-altay-24** [comment]
https://github.com/a1ive/grub2-filemanager/issues/292#issuecomment-731614042
https://github.com/a1ive/grub2-filemanager/issues/280#issuecomment-717187153

![Resim](https://user-images.githubusercontent.com/72962883/100315260-6a1ab800-2fc9-11eb-9501-b329e982415b.jpg)

hello @ steve6375 master, I get an error like this in config file how can I fix it please help.
