### ISSUE TITLE
search.sh not in latest build?

### ISSUE THREAD

**Issue by steve6375** [a1ive/grub2-filemanager#294]
F10 not working. /boot/grubfm/search.sh missing?

**Comment by a1ive** [comment]
https://github.com/a1ive/grub2-filemanager/commit/bf4f7d2e658b535399ac9a33749690d2260866cb

**Comment by steve6375** [comment]
search.lua missing?

**Comment by a1ive** [comment]
I haven't written it yet.

**Comment by steve6375** [comment]
New search is only 2 levels deep?
e.g. start at \_ISO
it does not find files at \_ISO\WINDOWS\WIN10 folder
only searches  \_ISO and \_ISO\XXXX  
is this by design?

**Comment by a1ive** [comment]
> New search is only 2 levels deep?

Yes, to avoid crashing in some directories.

**Comment by steve6375** [comment]
Can you count the level and  stop if level = 5   say ???

**Comment by a1ive** [comment]
No, GRUB2 is fragile.

**Comment by steve6375** [comment]
bug - grubfm_open path does not have doublequotes ???
![image](https://user-images.githubusercontent.com/1469350/100740609-e8fc6000-33d0-11eb-87f6-4616e1cc0ad3.png)

**Comment by steve6375** [comment]
I added user defined search
all searches now search for  (string)*  - e.g. iso*
also improved back menu and added a few more menu items
![image](https://user-images.githubusercontent.com/1469350/100741906-05e56300-33d2-11eb-8b86-c8a010976df0.png)
![image](https://user-images.githubusercontent.com/1469350/100742091-21506e00-33d2-11eb-8313-fc7456217f95.png)

[search.zip](https://github.com/a1ive/grub2-filemanager/files/5622607/search.zip)

It would be nice if the search would go 4 or 5 levels deep?

**Comment by a1ive** [comment]
> It would be nice if the search would go 4 or 5 levels deep?

Not under consideration.

![深度截图_选择区域_20201201205801](https://user-images.githubusercontent.com/10670106/100744027-21735c80-3418-11eb-9cd9-463c8ed99171.png)
I don't think it's correct.
grubfm does not support imgptn and some other extensions. You can put your own modifications of search.sh and search.lua on a USB stick.

**Comment by steve6375** [comment]
OK. no problem. Thanks for the new functions. :-)
