### ISSUE TITLE
Suggestion - hotkey to reload menu system

### ISSUE THREAD

**Issue by steve6375** [a1ive/grub2-filemanager#295]
Sometimes, after running a bad ISO, etc.  grubfm ends up in text mode and it is difficult for a simple user to reload the menu system again without rebooting.
Maybe global.sh could set up a (e.g.) Ctrl+F10 hotkey which would load (memdisk)/boot/grubfm/init.sh to reload the menu system again?
Would this cause any issues? The F1 Help menu could list the hotkey.

**Comment by a1ive** [comment]
> Sometimes, after running a bad ISO, etc. grubfm ends up in text mode and it is difficult for a simple user to reload the menu system again without rebooting.

They **should** reboot.

**Comment by steve6375** [comment]
yes - but they would then have to press a hotkey and select the correct boot option, etc. - also rebooting on a server can take 5 minutes. Could they not first try Ctrl+F10 and then if that doesn't work they could reboot.

**Comment by a1ive** [comment]
> yes - but they would then have to press a hotkey and select the correct boot option, etc. - also rebooting on a server can take 5 minutes. Could they not first try Ctrl+F10 and then if that doesn't work they could reboot.

I'm talking about should or shouldn't. Other bootloaders **may** corrupt runtime data of GRUB2 and cause unforeseen errors!

**Comment by steve6375** [comment]
errors that could damage the USB drive or attached disks?
Since hotkeys are working enough, grubfm grub2 is still running.
Ideally I would like to reload grub without rebooting, but this would mean reloading source boot file, e.g.
/grubfmx64.efi  (in my case as loading /EFI/BOOT/BOOTx64.EFI shim causes crash)
/e2b/grubfm.iso
/EFI/BOOT/BOOTIA32.EFI
but this is not a universal case...

**Comment by a1ive** [comment]
> errors that could damage the USB drive or attached disks?

It's possible.
After chain-loading the bootloader and before executing the "boot" command, GRUB2 executes preboot hooks and prepares to commit suicide.
If you don't want to reboot, you will have to chain-load grubfm itself (grubfm.efi/grubfm.elf) immediately.

**Comment by a1ive** [comment]
> rebooting on a server can take 5 minutes

Will it be faster to perform a "warm reboot" under uefi?
`reset --warm`

**Comment by steve6375** [comment]
I am not sure. Maybe add an extra option in F6 menu for 'Warm reboot' ?

**Comment by thamermousa** [comment]
Nice suggestion
F5 OR F10

When was the latest version of 7.3.3 published?
4 Aug ؟؟؟

Thanks, everyone

**Comment by a1ive** [comment]
> When was the latest version of 7.3.3 published?
> 4 Aug ؟؟؟

I'm waiting for grub-2.06 release
