### ISSUE TITLE
date and time in the main menu

### ISSUE THREAD

**Issue by Tnctr-altay-24** [a1ive/grub2-filemanager#298]
Hi A1ive master;
Could it show the date and time in the main menu as in g4e?

**Comment by a1ive** [comment]
$YEAR
$MONTH
$DAY
$HOUR
$MINUTE
$SECOND
$WEEKDAY

**Comment by steve6375** [comment]
![image](https://user-images.githubusercontent.com/1469350/102596968-d3e23980-4111-11eb-9b85-ce4ca01ae54e.png)

My eBook maybe of use
https://payhip.com/b/bqSo
