### ISSUE TITLE
厉害！支持大神！

### ISSUE THREAD

**Issue by clh021** [a1ive/grub2-filemanager#3]
刚刚无意中发现您的这个作品，睡前测试了一下，太出乎意外的强大了！
虽然图片部分不能打开，部分显示变形，但是，几乎兼容所有流行ISO，彻底摆脱每次还要编写grub.cfg的繁琐步骤，太厉害了！
顶一下！

**Comment by a1ive** [comment]
grub2只能加载小于屏幕分辨率的图片.
与屏幕分辨率不同的图片,显示会失真.
