### ISSUE TITLE
Request: Add option to call view.lua so that it does not prompt for a key press

### ISSUE THREAD

**Issue by steve6375** [a1ive/grub2-filemanager#301]
The current view.lua always prompt to press a key Press any key to exit. in English

view.lua is useful to display graphics to a user for information or error, etc. - it would be useful to enhance  the function...

view.lua    - default action as now with English prompt
view.lua "" - does not display text or prompt user for key (or maybe a -noprompt switch ?)
view.lua "abc def jkl" - Displays this text (UTF8? Unicode?) and waits for a key press

It could then also support different languages rather than just English.

Is this possible?

**Comment by a1ive** [comment]
> The current view.lua always prompt to press a key Press any key to exit. in English

The prompt message is localized.
![1](https://user-images.githubusercontent.com/10670106/102785645-45074280-43d9-11eb-89bb-d4bedf3bb418.png)
> view.lua is useful to display graphics to a user for information or error, etc. - it would be useful to enhance the function...

It's only available in graphics mode.

**Comment by a1ive** [comment]
why not use a theme file and hidden hotkey menus?

**Comment by steve6375** [comment]
Ok, main requirement is to be able to remove the prompt so view.lua requirement to press a key can be suppressed.

**Comment by steve6375** [comment]
E.g  prompt for password on startup, if bad pad display graphics file, sleep 5, reboot or shutdown.

**Comment by a1ive** [comment]
You can remove 'video.draw_string ...' and add `grub.script ("reboot")` after 'input.getkey ()'.

**Comment by steve6375** [comment]
Sure - I can write my own lua script.  It would just be easier if view.lua was more useful...

**Comment by a1ive** [comment]
> It would just be easier if view.lua was more useful...

I'm not considering adding more features for now.
If I need to implement a more complex graphical interface one day, I may consider improvements.
