### ISSUE TITLE
has not booting with BlackArch Linux

### ISSUE THREAD

**Issue by CyberMan571** [a1ive/grub2-filemanager#303]
Hi Friends
I downloaded  grub2fm however I have see problem while it is booting and it is not booting 

Boot from iso  it's not working
boot iso (map) I see boot option screen then it is stayed  in blackscreen

Please  can you update the  grub2fm project

**Comment by CyberMan571** [comment]
Tell me, If I have wrote missing, I'll send you whatever is required with the screenshot.

**Comment by steve6375** [comment]
Exact name of ISO
Legacy boot? UEFI32 boot? UEFI64 boot? Secure Boot?
Error message?
Make\Model of all systems you have tested it on?
Have you tested on a VM?

**Comment by chromer030** [comment]
I tested with latest Arch Linux ISO and not booting , tested in UEFI , without secure boot.

**Comment by steve6375** [comment]
Which One?
BlackArch Linux 64 bit Full ISO | 2020.12.01 | Torrent | 15 GB | 9eb3b39e09e085a47d8385403389f6d57764d037
BlackArch Linux 64 bit Netinstall ISO | 2020.12.01 | Torrent | 733 MB | 945fb94f527c6c02c07bacfd7ca1fbef2f50de52

UEFI64 boot or UEFI32 boot?
What systems have you tested on? Make ? Model? Total RAM?

**Comment by steve6375** [comment]
BlackArch Linux 64 bit Netinstall ISO | 2020.12.01  - UEFI64 - partnew\easy2boot option works OK

**Comment by steve6375** [comment]
Full ISO does not work using partnew or other options - strange!

You can make a .grubfm file with the same name as the ISO and then choose the User Menu option
The ISO must be contiguous.
```

menuentry "BlackArch Linux 64-bit (partnew) " --class=tails {
partnew --type=0x00 --file="${grubfm_file}" (${grubfm_disk}) 4
loopback loop "${grubfm_file}" 
set root=loop
set "params=archisobasedir=blackarch archisolabel=BLACKARCH_202011 accessibility=on"
linux  /blackarch/boot/x86_64/vmlinuz-linux ${params}
initrd /blackarch/boot/intel-ucode.img /blackarch/boot/amd-ucode.img /blackarch/boot/x86_64/initramfs-linux.img
}

```

**Comment by steve6375** [comment]
```
menuentry "BlackArch Linux 64-bit (ISO boot) " --class=archlinux {
probe -u (hd0,1) --set=abc
set pqr="/dev/disk/by-uuid/$abc"
loopback loop "${grubfm_file}" 
set "params=archisobasedir=blackarch accessibility=on img_loop=$grubfm_path img_dev=$pqr driver=free"
echo $params; read;
linux  (loop)/blackarch/boot/x86_64/vmlinuz-linux ${params}
initrd (loop)/blackarch/boot/intel-ucode.img (loop)/blackarch/boot/amd-ucode.img (loop)/blackarch/boot/x86_64/initramfs-linux.img
}
```

Here is alternative for  non-contiguous ISO. Assumes ISO is on hd0,1 (first partition).

**Comment by steve6375** [comment]
[blackarch-linux-full-2020.12.01-x86_64.zip](https://github.com/a1ive/grub2-filemanager/files/5724037/blackarch-linux-full-2020.12.01-x86_64.zip)
This is for E2B agFM only

**Comment by steve6375** [comment]
[blackarch-linux-full-2020.12.01-x86_64.cfg.zip](https://github.com/a1ive/grub2-filemanager/files/5724109/blackarch-linux-full-2020.12.01-x86_64.cfg.zip)
This is a .cfg file - you must set the filepath.

**Comment by chromer030** [comment]
this booting issue exist via Arch linux Official image too.
http://mirrors.evowise.com/archlinux/iso/2020.12.01/archlinux-2020.12.01-x86_64.iso
and also Debian nonfree cant be recognized and booted.
https://cdimage.debian.org/cdimage/unofficial/non-free/cd-including-firmware/weekly-builds/amd64/iso-cd/firmware-testing-amd64-netinst.iso

tested in Real intel machine with i3 haswell UEFI and Qemu OVMF EFI.

**Comment by a1ive** [comment]
Arch Linux changed the location of vmlinuz and initrd in the ISO, so the loopback script in grub2-filemanager no longer works.
BTW I'm still downloading the Black Arch ISO...
> Debian nonfree cant be recognized and booted

Debian Install ISO is not supported while Debian Live is supported.

**Comment by CyberMan571** [comment]
> 
> 
> Full ISO does not work using partnew or other options on UEFI64 - strange! MBR-boot is OK.
> 
> You can make a .grubfm file with the same name as the ISO and then choose the User Menu option
> The ISO must be contiguous.
> 
> ```
> 
> menuentry "BlackArch Linux 64-bit (partnew) " --class=archlinux {
> partnew --type=0x00 --file="${grubfm_file}" (${grubfm_disk}) 4
> loopback loop "${grubfm_file}" 
> set root=loop
> set "params=archisobasedir=blackarch archisolabel=BLACKARCH_202011 accessibility=on"
> linux  /blackarch/boot/x86_64/vmlinuz-linux ${params}
> initrd /blackarch/boot/intel-ucode.img /blackarch/boot/amd-ucode.img /blackarch/boot/x86_64/initramfs-linux.img
> }
> ```

Hey Steve and a1(l)ive  Thanks  
I have using a Full BlackArch ISO! 
I use gpt partition 
I want you to consider an important point here.
When I select boot live-kali it gives a same error with Full Blackarch on mbr with ueifi computer (while no cms option) (no multiboot usb)
However
on Kali,  it has success boot when I select boot usb live with persistence
adding: Kali has a Debian kernel

I  going to(will) a planed test gpt partition kali iso  on uefi
![P_20201219_020454](https://user-images.githubusercontent.com/30759335/102806630-467f3d80-43ce-11eb-9e65-59337284f0a2.jpg)


loopback loop "${grubfm_file}" 

"grub2" will ask for this part. ISO files are in the "NTFS partition" but "AIOBOOT files" are stored in Fat32.

Can you tell me an ebook where I can learn Grub2 commands? Or how did you learn programming in Grub2!

**Comment by CyberMan571** [comment]
it's Here  the partitions on me
![Ekran görüntüsü 2020-12-21 221329](https://user-images.githubusercontent.com/30759335/102813622-30777a00-43da-11eb-834a-604ad3612a5c.png)

@steve6375  
${grubfm_file}" (${grubfm_disk})
It is necessary to specify the locations of these variables in the code! I don't know how to program grub2 right now? After developing C and Cpp myself, I think I can adapt grub2 more easily.

**Comment by CyberMan571** [comment]
![grub2 or grub2wın error](https://user-images.githubusercontent.com/30759335/102832882-b7d7e400-4400-11eb-95be-845da42a54b7.png)

Hey Dear Friends,
I see problems and it can be a bug

**Comment by steve6375** [comment]
BlackArch linux 2020-12-01 Full - UEFI64  using partnew\east2boot option DOES WORK on a real machine. I tested on IdeaPad300.
It does not seem to like Vbox for some reason but real system is OK.

**Comment by a1ive** [comment]
I've updated kernel and initramfs path for arch-based iso files.
Please download latest and use "Boot XXX From ISO".
"boot iso (map)" is mainly for small winpe-based iso files.
![深度截图_选择区域_20201222211927](https://user-images.githubusercontent.com/10670106/102893012-c7f0d180-449b-11eb-8ad2-6a16030dbcfe.png)

**Comment by CyberMan571** [comment]
I successed I have won
Please you will wait details from me at tonight
Pre info
Secureboot, no cms and improvements for a few errors ntfs partition  boot
gpt

Details are on the way, tonight

22 Ara 2020 Sal 16:27 tarihinde A1ive <notifications@github.com> şunu yazdı:

**Comment by CyberMan571** [comment]
@a1ive 
thanks for the updated 
however 
I have test to Grubfm and I found the problem
when it is boot iso-map, it is staying(crash ) in black shell-root screen, the sha1 checksum vaule is ok

in both, booted successfully when it does boot from iso
![resim](https://user-images.githubusercontent.com/30759335/103059048-00d09980-45b5-11eb-9459-08780c78bd82.png)

Perhaps(maybe) this picture can give you an idea for a fix.
I see a fs fat16 there

**Comment by a1ive** [comment]
As I said before, you need to select the entry "Boot BlackArch from ISO" instead of the "Boot ISO (map)" entry.
"Boot ISO (map)" is for winpe based ISO files.
The method steve described is only for USB flash drives which have MBR partition table.
