### ISSUE TITLE
Easier support for different user themes?

### ISSUE THREAD

**Issue by steve6375** [a1ive/grub2-filemanager#305]
With the new Info F5 menus, it is becoming quite difficult to change the theme and make the four theme .txt files.
For instance, if a large font is used in a new theme, then the new F5 menu goes wrong if we keep the original info.txt theme file.
![image](https://user-images.githubusercontent.com/1469350/103168134-87d97800-4828-11eb-8870-67f677fdeb23.png)

It would be easier for the user if they only had to use their own theme.txt and fm.txt ($theme_std and $theme_fm) but not set a theme file for info.txt and help.txt - just use the default internal theme and use only the default font for those menus. Is this possible? Could the font be defined in the internal default .txt theme files? Could a more 'generic' theme be used for the info.txt and help.txt so it works with any theme and font the user may use?

**Comment by steve6375** [comment]
P.S. No hotkey for MOTHERBOARD ?
![image](https://user-images.githubusercontent.com/1469350/103168817-86ab4980-482e-11eb-835c-f36e105229dc.png)

**Comment by a1ive** [comment]
> P.S. No hotkey for MOTHERBOARD ?
> ![image](https://user-images.githubusercontent.com/1469350/103168817-86ab4980-482e-11eb-835c-f36e105229dc.png)

Oh, I forgot to add the hotkey.

**Comment by a1ive** [comment]
> For instance, if a large font is used in a new theme, then the new F5 menu goes wrong if we keep the original info.txt theme file.

Fonts cannot be scaled like images. Any non-16px fonts are not suitable for use with the built-in theme.

> Could a more 'generic' theme be used for the info.txt and help.txt so it works with any theme and font the user may use?

I don't think this can be done.
Even a complete operating system like iOS has display problems caused by different screen sizes (e.g. iPhone and iPad).
