### ISSUE TITLE
F1 help  - info for F5 (help.sh)

### ISSUE THREAD

**Issue by steve6375** [a1ive/grub2-filemanager#307]
![image](https://user-images.githubusercontent.com/1469350/103208677-30570d00-48f9-11eb-9832-ba40c5ae7dfe.png)

help.sh
```


if [ -n "${aioboot}" ];
then
  menuentry $"F5 - AIO Boot" {
    echo;
  }
elif [ -n "${ventoy}" ];
then
  menuentry $"F5 - Ventoy" {
    echo;
  }
else
  menuentry $"F5 - PXE Boot Menu" {
    echo;
  }
fi;

```

Maybe change to   "F5 - HWINFO\Ventoy"   ???  etc.

**Comment by a1ive** [comment]
"F5 - Hardware information"?

**Comment by steve6375** [comment]
I think displaying Ventoy or AIOBoot or PXE is useful because the user may be looking for them.
Will you also need to translate 'Hardware information' into all languages :-(

**Comment by steve6375** [comment]
You could move Ventoy/AIOBoot/PXE to F6 menu?
F5 = Info
F6 = System

F4 could be 'Settings'  icon  = gear wheel
F6 could be 'System' or 'Utilities' icon  = tools
??

OR
Move the  grub\hwinfo stuff to the F1 menu and restore F5 as  Ventoy\AIOBoot\PXE as before?

**Comment by a1ive** [comment]
> restore F5 as Ventoy\AIOBoot\PXE as before?

then how to boot to aioboot/ventoy/pxe if both aioboot and ventoy are installed?

**Comment by steve6375** [comment]
F5 will load menu for them?

**Comment by a1ive** [comment]
"F5 - HWINFO & Multiboot"?

**Comment by steve6375** [comment]
To me, F1 is for displaying help and info. It already displays some info:
![image](https://user-images.githubusercontent.com/1469350/103212962-2dade500-4904-11eb-9b72-43bc46e41424.png)
So adding to F1 another entry to display System Info would be logical (grub,cpu, etc).
That leaves F5 for a menu to run PXE, AIOBoot, Ventoy or other bootable products.

Having the F5 button for info + booting to other platforms seems illogical and has also changed its purpose from before.

**Comment by a1ive** [comment]
F1 - System information (GRUB menu also shows hotkeys)
F5 - Multiboot toolkits (PXE, AIOBoot, Ventoy, UEFI Shell, UEFI DUET, grub2 cmdline)
F6 - Power off (halt, reboot, fwsetup)
?

**Comment by steve6375** [comment]
That seems more logical :-)

**Comment by a1ive** [comment]
BTW, have you tested the time taken to perform cold and warm reset (reset --cold & reset --warm) on servers?
Is there any difference between them?
Is it necessary to add menu entries for both of them?

**Comment by steve6375** [comment]
I do not have a server as I no longer work with servers (I am retired now).
I might be useful to have two menu entries anyway.

**Comment by Tnctr-altay-24** [comment]
hello a1ive master.
I need help with something. I would be grateful if you could help. Thank you from now. When I select with my config file (hd0, msdos2)/boot/grubfm/ hwinfo.sh with F5 like this, it calls netboot.sh. I guess it can't find the path to hwinfo.sh (hd0, msdos2) so I can't see the menu in hwinfo.sh. Can you help with this? I hope I explained the problem. Since I do not have English, I used the translation. Thank you.
![IMG_20201228_131218](https://user-images.githubusercontent.com/72962883/103263073-d9fcd380-49b7-11eb-98a8-8cdb7c2aedc7.jpg)

**Comment by a1ive** [comment]
> hello a1ive master.
> I need help with something. I would be grateful if you could help. Thank you from now. When I select with my config file (hd0, msdos2)/boot/grubfm/ hwinfo.sh with F5 like this, it calls netboot.sh. I guess it can't find the path to hwinfo.sh (hd0, msdos2) so I can't see the menu in hwinfo.sh. Can you help with this? I hope I explained the problem. Since I do not have English, I used the translation. Thank you.
> ![IMG_20201228_131218](https://user-images.githubusercontent.com/72962883/103263073-d9fcd380-49b7-11eb-98a8-8cdb7c2aedc7.jpg)

In most cases this error means that the theme is incorrectly configured.

**Comment by steve6375** [comment]
Thanks! So now user just has to make a theme.txt and fm.txt. They can leave theme_info and others alone.

P.S.  theme_help is no longer used?
![image](https://user-images.githubusercontent.com/1469350/103281472-c018bc00-49ca-11eb-8972-11a4657e6f07.png)
