### ISSUE TITLE
hwinfo resolution/language swapped

### ISSUE THREAD

**Issue by steve6375** [a1ive/grub2-filemanager#309]
![image](https://user-images.githubusercontent.com/1469350/103321474-b0808e00-4a31-11eb-874f-5e324498557d.png)

**Comment by steve6375** [comment]
New F1 info does not show the grub2 version string or GPLv3 License or name of product 'GrubFM' or author?

grub has a version number, but does grubfm have a version number too?

![image](https://user-images.githubusercontent.com/1469350/103346216-4694d280-4a8b-11eb-835f-44dfb822e1dd.png)

**Comment by steve6375** [comment]
P.S.  How about adding a link for github sources (grub and grubfm) and for donations?

**Comment by steve6375** [comment]
P.P.S.  change 'Time' to 'BIOS Time'   ?

**Comment by a1ive** [comment]
> P.P.S. change 'Time' to 'BIOS Time' ?

What does "BIOS Time" mean? Why?

> P.S. How about adding a link for github sources (grub and grubfm) and for donations?

Since there is no browser under GRUB2, I don't think it's useful to add links. :laughing:

> New F1 info does not show the grub2 version string or GPLv3 License or name of product 'GrubFM' or author?

This feature is no longer needed, as the F1 menu currently shows grub2 version already.
Maybe I'll add an egg to this menu in the future?

**Comment by steve6375** [comment]
A few people have said to me that the time displayed is 'wrong' because they don't realise that it is not an internet-connected operating system(!) and that the time displayed simply comes from the battery-backed Real Time Clock (and BIOS) and that it is their RTC that is wrong. Also, it does not compensate for different time zones. I think Linux sets the RTC to GMT time whereas Windows sets the RTC to local time, so depending on what OS you have on that system, the BIOS RTC reading can be 'wrong'.
Using BIOS may be more easily understood. You could use  'Real Time Clock' if you prefer or 'BIOS\RTC Time'?

**Comment by a1ive** [comment]
I prefer "Real Time Clock".
BTW, does daylight saving time also affect it?

**Comment by steve6375** [comment]
I think by default, the RTC has daylight saving enabled, but usually the OS will set the RTC each time it boots anyway.
