### ISSUE TITLE
Linux VHD Boot via Grub2FM

### ISSUE THREAD

**Issue by abdullah-erturk** [a1ive/grub2-filemanager#330]
I installed Linux Mint in UEFI mode on VHD virtual disk file via VMware. It booted on Vmware without any problems.

Then I thought of booting the Linux-installed VHD file with Grub2FM, but unfortunately it didn't boot.

Is it possible to do this?

![resim_2021-01-12_214625](https://user-images.githubusercontent.com/54866587/104358509-9cec2180-551f-11eb-92a5-fcd7a23d1ef3.png)

**Comment by a1ive** [comment]
Linux VHD files are not supported.
You need to install some drivers, or modify the init script.
Different methods are used to install different linux distributions.
http://bbs.wuyou.net/forum.php?mod=viewthread&tid=418705

**Comment by abdullah-erturk** [comment]
Is Ventoy's Vdisk plugin adaptable for Grub2FM?

https://www.ventoy.net/en/plugin_vtoyboot.html

**Comment by a1ive** [comment]
> Is Ventoy's Vdisk plugin adaptable for Grub2FM?

I think it's possible. But ventoy relies on a specific partition structure, which probably doesn't make much sense.

**Comment by a1ive** [comment]
> But ventoy relies on a specific partition structure, which probably doesn't make much sense.

Confirmed. Cluster size must be greater than or equal to 2048.

**Comment by ventoy** [comment]
@abdullah-erturk 
You can refer: https://github.com/ventoy/vdiskchain

**Comment by abdullah-erturk** [comment]
Master a1ive, vdiskchain project can most likely be integrated into Grub2FM. Just think about it :)

**Comment by a1ive** [comment]
@ventoy EDKII/edk2-edk2-stable201911/MdeModulePkg/Application/VDiskChain 目录里面是不是还有其他代码没有上传？
https://github.com/ventoy/vdiskchain/blob/9b92b11011d907b4566c0aa1d6adac2c0959e6a9/build_image.sh#L95

**Comment by ventoy** [comment]
是的。已经上传了。

**Comment by a1ive** [comment]
@ventoy 
> chainloader /vdiskchain vdisk=/MyVdiskDir/Deepin.vdi.vtoy

如果多个分区下都有 "/MyVdiskDir/Deepin.vdi.vtoy" 这个文件，如何启动指定分区下的文件？能否通过 uuid 指定磁盘？

**Comment by ventoy** [comment]
现在就是简单的grub2的  search.file 命令，所以应该是固定启动第一个找到的分区里的文件。
也可以多加个参数，比如分区文件系统的label或uuid， 使用  search.fs_label  或 search.fs_uuid 先找到分区，再拼接上文件路径也可以。下个版本可以加上。 不过一般情况下冲突的概率应该比较小，而且对于普通用户来说，可能改个文件名更简单一些。

**Comment by candrapersada** [comment]
how to boot Linux vDisk from Grub2 File Manager?
