### ISSUE TITLE
Secure Boot needs to be supported.

### ISSUE THREAD

**Issue by noxplayer2021** [a1ive/grub2-filemanager#332]
I want Grub2FM to support Secure Boot. If it supports Secure Boot, alive1 should share the certificate file so I can sign * .efi files.

**Comment by a1ive** [comment]
See https://github.com/abdullah-erturk/SecureBoot-Grub2FM-Suite and https://github.com/ValdikSS/Super-UEFIinSecureBoot-Disk

**Comment by noxplayer2021** [comment]
Can you share the Microsoft UEFI CA private key and security certificate for me?

**Comment by a1ive** [comment]
> Can you share the Microsoft UEFI CA private key and security certificate for me?

What are you talking about! Only Microsoft has the UEFI CA private key.
