### ISSUE TITLE
EFI Blocked Error !!!!  a1ive grub2 file manager with E2B (UEFI64 Secure boot Enabled) Not Working on latest Lenovo laptops. 11th generation with latest bios update

### ISSUE THREAD

**Issue by haseakash** [a1ive/grub2-filemanager#338]
I tested E2B with a1ive grub2 with many pc/laptops.

however models under 2019 boots ok with secure boot without any issue.

But today i visited lenovo store.

And i test my pendrive with latest lenovo laptops.((11th generation) Bios updated.

I got error when booting Secure Boot Enable EFI

Usb blocked /Unauthorized efi/ efi blocked

i tried over 10 different latest 2021 models.

So E2B+AGFM   Can u please update your codes to bypass it without enrolling key or disabling secure boot or going in bios for boot?????

I want solution immediately.

Model : Lenovo IP Gaming 3 82EY00L4IN

Also make agfm to works latest bios updated laptops like lenovo,dell,hp,asus,accer etc.

secure boot support without manually enroll key is most imp need.

**Comment by steve6375** [comment]
http://rmprepusb.blogspot.com/2021/01/latest-windows-update-kb4535680-blocks.html

**Comment by a1ive** [comment]
The issue you are reporting is NOT related to grubfm.
