### ISSUE TITLE
有没有Grub的签名啊？可以安全启动吗？

### ISSUE THREAD

**Issue by 1457384613gh** [a1ive/grub2-filemanager#358]
有没有Grub的签名啊？
可以安全启动吗？

**Comment by a1ive** [comment]
你要自己签名，用 `MokManager` 导入证书。

**Comment by 1457384613gh** [comment]
> 你要自己签名，用 `MokManager` 导入证书。

随便拿个EFI的证书，只要没过期，都行，是吗？

**Comment by 1457384613gh** [comment]
还有几件别的事。
## 分辨率为 1366x768时，界面排版有点问题。
![IMG_20230506_215731.jpg](https://user-images.githubusercontent.com/69227436/236628738-61c772bc-e9b5-438d-a899-4733de112b5a.jpg)

## 无法保存设置。
设置了语言和分辨率以后，下次启动，又恢复默认设置了。

## 默认分辨率
默认分辨率是 1024x768。希望可以把默认分辨率改成 auto select。这样就不用手动调。

## 【exit】按钮
类似于 refind 的【exit】按钮。
返回到 进入 grubfm 之前的界面。
假如 refind 引导 grubfm 则回到 refind。
假如 grub4dos 引导 grubfm 则回到 grub4dos。
假如 F12，通过 UEFI_BIOS 的入口进入的，则回到 UEFI_BIOS 的 F12。

**Comment by a1ive** [comment]
README 上提示了，此项目已不再维护。请使用 Ventoy 或其他项目。
> 默认分辨率是 1024x768。希望可以把默认分辨率改成 auto select。这样就不用手动调。
> 分辨率为 1366x768时，界面排版有点问题。

正是因为布局问题，所以我才把分辨率指定为 1024x768。
字体是不支持缩放的，所以在一个分辨率下正常显示的主题，在其他分辨率下可能就没有好的显示效果。
> 无法保存设置。

关于不支持保存配置的原因，请参考 Ventoy 的 FAQ。
grubfm 支持在 U 盘上放置 /boot/grubfm/config 来自定义配置，参考 https://github.com/a1ive/grub2-filemanager/issues/103
也可以参考 Easy2Boot。
> 类似于 refind 的【exit】按钮。
返回到 进入 grubfm 之前的界面。

首先 BIOS 下不可能实现。
UEFI 下，由于我的 GRUB2 有远比 refind 复杂的功能，退出到上一级 bootloader 会造成很多问题。
而且对于一个 bootloader 来说，没有什么意义。除非你喜欢在几个 bootloader 之间来回跳着玩。

**Comment by 1457384613gh** [comment]
> 此项目已不再维护。

大佬，你这项目那么精致，处处图标都精致。
不再维护？
好可惜的说。

**Comment by a1ive** [comment]
> > 你要自己签名，用 `MokManager` 导入证书。
> 
> 随便拿个EFI的证书，只要没过期，都行，是吗？

你要用自己的私钥生成证书并签名。只能在导入了这个证书的电脑上通过安全启动。
别人/其他组织是不会随便把私钥泄露给你的 (特别是微软的)

**Comment by 1457384613gh** [comment]
@a1ive 
还有件别的事情，关于编译UEFI应用，扯得有点远。
人家是个小白，实在是黔驴技穷，想找大佬您讨教讨教。

人家想 基于 GRUB4DOS UEFI 版 设计一个 UEFI 游戏集锦。


人家在Github上 发现了个特别精致的 飞扬的小鸟 UEFI版。想收进 UEFI 游戏集锦中，用 自定义主题的 GRUB4DOS 引导。
源代码如下，
https://github.com/fabianishere/boot2flappy

可是，人家按照教程编译，用的 Ubuntu，编译到 92% 就失败了，报错，提示`从输出所省略的额外重寻地址溢出`。
![image](https://user-images.githubusercontent.com/69227436/234244490-9af7d4ff-8789-4edd-82b9-c9350eba193a.png)

人家 issue 了作者。可那个外国作者不回应欸。

人家觉得，加个 UEFI 小游戏的选项，电脑不进入操作系统，也可以给亲朋好友家作客的小孩子玩，还可以防止弄乱桌面文件，或随意安装软件耶。而且，是自带防沉迷容易玩腻的小游戏。不借电脑玩，又显得小气，借了电脑玩，不想输入管理员密码，不想开通访客账户。

人家想加你QQ聊这件事，然后私底下发个小红包的，可惜你不喜欢加……

不知大佬您肯不肯看看源代码，帮帮我？
🥺🥺🥺人家会感激不尽的。

**Comment by 1457384613gh** [comment]
您应该认识其他精通编译UEFI应用的大佬的。
倘若，您特别忙，您可以推荐给其他大佬，帮忙看看，毕竟众人拾柴火焰高。

**Comment by 1457384613gh** [comment]
> 请使用 Ventoy 或其他项目。

其实，这个项目跟 Ventoy 相比，应用场所不一样。

- Ventoy 更加适合 USB 驱动器，毕竟需要调整分区。
-  grubfm 适合 内置硬盘，毕竟直接复制到 内置硬盘的 ESP 分区就行了，无需 调整分区。

**Comment by 1457384613gh** [comment]
还有件事，grubfm 作为 menuentry 的时候，有没有官方 logo 啊？
没有的话，只好设计第三方 logo 了。

**Comment by 1457384613gh** [comment]
@a1ive 大佬，我画了个这样的 Logo，你看可好？
https://github.com/M-L-P/icons/blob/main/PNGs/Boot_Tools/grubfm.png

**Comment by a1ive** [comment]
> 还有件事，grubfm 作为 menuentry 的时候，有没有官方 logo 啊？ 没有的话，只好设计第三方 logo 了。

以前随便画的：https://crowdin-static.downloads.crowdin.com/images/project-logo/310644/small/628db0ab34d6b7387cc5c14c89127fba348.png

**Comment by 1457384613gh** [comment]
> 以前随便画的：https://crowdin-static.downloads.crowdin.com/images/project-logo/310644/small/628db0ab34d6b7387cc5c14c89127fba348.png

有没有 512x512 的？
这个好小好小的说。

**Comment by 1457384613gh** [comment]
我把 grubfm 嵌套进这个里面了，顺便可以帮你引流。
https://github.com/M-L-P/Yours

## 关于分辨率和排版的问题
 常见的 显示器 比例有：
- 16:9
- 4:3
- 16:10
- 15:9
- …

排版，可以根据 显示器比例设计，分辨率 对应 显示器比例 对应 适应比例的排版。

排版 等比例放缩，不知道这样可不可以改善这个问题。

**Comment by 1457384613gh** [comment]
我把 grubfm 嵌套进这个里面了，顺便可以帮你引流。
https://github.com/M-L-P/Yours

## 关于分辨率和排版的问题
 常见的 显示器 比例有：
- 16:9
- 4:3
- 16:10
- 15:9
- …

排版，可以根据 显示器比例设计，分辨率 对应 显示器比例 对应 适应比例的排版。

排版 等比例放缩，不知道这样可不可以改善这个问题。

**Comment by a1ive** [comment]
> > 以前随便画的：https://crowdin-static.downloads.crowdin.com/images/project-logo/310644/small/628db0ab34d6b7387cc5c14c89127fba348.png
> 
> 有没有 512x512 的？ 这个好小好小的说。

没有。反正是随便画的。

**Comment by a1ive** [comment]
> 字体是不支持缩放的，所以在一个分辨率下正常显示的主题，在其他分辨率下可能就没有好的显示效果。

前面说过了。
> 字体是不支持缩放的，所以在一个分辨率下正常显示的主题，在其他分辨率下可能就没有好的显示效果。

unifont 点阵字库，英文字母是 8px\*8px，中文字母是 16px\*16px。换更高的分辨率，图标和字体之间大小的对应关系就破坏了。除非用多个不同大小的字库来适配多套主题，那样体积太大了，容易降低启动成功率。
用高分辨率主题，本身也会降低启动成功率和运行速率。

**Comment by 1457384613gh** [comment]
高分辨率显示 低分辨率的主题，会拉伸的。

- 1366/768≈1920/1080=16:9
- 1024/768=1280/960=4:3

我觉得，就弄两套分辨率的主题
- 1024x768 
- 1366x768

4:3比例的屏幕，都使用 1024x768；

16:9，15:9，16:10 的，都使用 1366x768，纵横比有一点点差距，但是差距不会特别大，排版应该不会出问题。

现在的问题是，只有 1024x768 是排版正常的，那 16:9 的屏幕，会把图像拉得很宽很宽。
大不了，就添加个 16:9 的排版，比例很接近16:9的，都使用这个分辨率，就算拉伸了，纵横比也差不多，排版应该不会 乱。

**Comment by a1ive** [comment]
> 高分辨率显示 低分辨率的主题，会拉伸的。
> 
> * 1366/768≈1920/1080=16:9
> * 1024/768=1280/960=4:3
> 
> 我觉得，就弄两套分辨率的主题
> 
> * 1024x768
> * 1366x768
> 
> 4:3比例的屏幕，都使用 1024x768；
> 
> 16:9，15:9，16:10 的，都使用 1366x768，纵横比有一点点差距，但是差距不会特别大，排版应该不会出问题。
> 
> 现在的问题是，只有 1024x768 是排版正常的，那 16:9 的屏幕，会把图像拉得很宽很宽。 大不了，就添加个 16:9 的排版，比例很接近16:9的，都使用这个分辨率，就算拉伸了，纵横比也差不多，排版应该不会 乱。

那你自己研究呗。反正已经留了自定义主题的接口了。
https://github.com/a1ive/grub2-filemanager/blob/918524dc18f08eba1ade421282b54a7b2787fa15/boot/grubfm/init.sh#L87-L93

**Comment by 1457384613gh** [comment]
> 没有。反正是随便画的。

我用 AI 放大了。
https://github.com/M-L-P/icons/blob/main/PNGs/Boot_Tools/grubfm.png
