### ISSUE TITLE
添加对 fydeOS/chromeOS Flex (cloudready) 的支持

### ISSUE THREAD

**Issue by 1457384613gh** [a1ive/grub2-filemanager#360]
添加对 fydeOS/chromeOS Flex (cloudready) 的支持。
Ventoy 支持启动 fydeOS/chromeOS Flex (cloudready) 的 .img 虚拟磁盘。

grubfm 却启动失败。

grubfm 与 ventoy 有 相互借鉴，相辅相成 之处，应该是可以做到，从 Ventoy 那里 把该功能 移植过来的。

为什么不用 Ventoy 呢？
因为啊，Ventoy 最好安装在 U盘上；grubfm 更适合 安装在 内置硬盘中。

若是支持此功能，便可以达到，无需借助 U盘 就能够 安装 fydeOS 的效果。

**Comment by a1ive** [comment]
> THIS PROJECT IS NO LONGER BEING MAINTAINED

**Comment by 1457384613gh** [comment]
不好意思，打扰了。
当我没说。
