### ISSUE TITLE
您好，太喜爱您的作品了，我发现可以更完善的几个地方如下……

### ISSUE THREAD

**Issue by clh021** [a1ive/grub2-filemanager#4]
1、默认给所有linux的ISO添加参数，比如选择中文语言编码，键盘等
```
linux (loop)/live/vmlinuz findiso=$1 noprompt quiet boot=live ro deepin-installer locales=zh_CN.UTF-8 keyboard-configuration/layoutcode=us keyboard-configuration/variantcode= --  rootflags=sync
initrd (loop)/live/initrd.lz
```
2、好像发现了一些隐藏的文件
[暂时没有截图，需要的话，稍后截图贴出]，这些文件是PE，Win7，linux都没出现的
3、一直往下选的话，能否从最后一个文件选项循环到最上面一个文件选项？
4、不想每次一有问题就麻烦到您，想请问有没有办法自建第二启动菜单呢？
我自己找了一下，没有在x86_64-efi下发现有配置文件，config.cfg也不对，后来终于根据脚本内容发现了是
boot/grub/main.sh
但是不想破坏了您本身的文件内容。所以能否像PE那样可以寻找是否存在另一个用户自定义的启动配置文件，然后读取运行？
[暂时就这些，感谢您创作出这么优秀伟大的作品！]

**Comment by clh021** [comment]
上面配置的脚本是我测试通过的配置。您可以参照[这里](https://github.com/clh021/Grub2/blob/master/neyan/grub2_bios/grub.cfg)来查看更多提示。

deepin15.3如果没有提前选择好语言，将只能安装英文版，然后输入法，QQ等本地化软件都没有了，后期安装容易出现问题。而15.4还没有发布，即使发布了也不知是否会没有问题，所以才有如此迫切的想法。

如果您没有时间完善修复以上内容，还麻烦您优先看第四个问题。谢谢您！

**Comment by a1ive** [comment]
4.
boot/grub/main.sh 35行
function main{
	if test -z "$path"; then
+		menuentry "My Menu"{
+		}

也可在 boot/grub/boot.sh 文件开始处添加菜单。boot.sh里面的菜单是按[B]键才会显示的。
寻找外置配置文件是可以实现的。

**Comment by a1ive** [comment]
3. 

> 一直往下选的话，能否从最后一个文件选项循环到最上面一个文件选项？
grub2本身暂不支持此操作。

**Comment by a1ive** [comment]
1. 不妥。
如果LiveCD本身没有中文字体或不支持中文 (例如Debian) ，就会乱码。
Deepin在进入系统后仍可以调节语言设置，注销后再登录即可。
<img width="512" alt="snipaste20170324_090650" src="https://cloud.githubusercontent.com/assets/10670106/24276387/6f46ec70-1071-11e7-828a-849aa0f80935.png">

**Comment by clh021** [comment]
您好！感谢您的热心回复！
本人亲测过，加上中文需要参数并不会有乱码，中文语言包不全会用繁体，或者英文替代显示，，即使没有语言包也会忽略这个参数用默认的英文显示，，不过不要紧，晚些时候，这个我自己添加菜单测试通过了再反馈给您。

另外 Deepin15.3 系统需要提前选择好语言包是为了内置安装好的本地化软件环境，，安装好后再修改语言，软件包依然得一个一个安装，稳定性比不上内置的配置。  不知道15.4正式版会不会是在启动之后安装之时可选择语言。

如果我想实现寻找外置配置文件以启动大致如何实现呢？如果不复杂代码量不多，您能否赐教一二？如果略微复杂我就暂时放弃这个想法。

再次感谢您的热心回复！祝幸福平安！

**Comment by a1ive** [comment]
> 如果我想实现寻找外置配置文件以启动大致如何实现呢？如果不复杂代码量不多，您能否赐教一二？如果略微复杂我就暂时放弃这个想法。

[https://github.com/a1ive/grub2-filemanager/commit/6291d4df361c45447304ca1b889de5672a398bac](url)

> 2、好像发现了一些隐藏的文件
> [暂时没有截图，需要的话，稍后截图贴出]，这些文件是PE，Win7，linux都没出现的

请提供截图

**Comment by clh021** [comment]
![img_20170324_133910](https://cloud.githubusercontent.com/assets/1754391/24282830/e90763ac-109c-11e7-8ff0-ceb709fea902.jpg)
![img_20170324_133922](https://cloud.githubusercontent.com/assets/1754391/24282831/e918bd3c-109c-11e7-97ec-5a179ec572d9.jpg)
![img_20170324_133952](https://cloud.githubusercontent.com/assets/1754391/24282832/e91e1b92-109c-11e7-93ac-be37b31fdded.jpg)
![img_20170324_133959](https://cloud.githubusercontent.com/assets/1754391/24282833/e92c7e8a-109c-11e7-8e7e-b18a4ab2b433.jpg)
![qq 20170324133803](https://cloud.githubusercontent.com/assets/1754391/24282834/e93bc7f0-109c-11e7-8092-2a3dcc19dd46.png)
![20170324133603](https://cloud.githubusercontent.com/assets/1754391/24282838/e95f696c-109c-11e7-9867-80e2a5cd2235.png)

**Comment by clh021** [comment]
此前我在windows下顺利生产了 iso 文件
但是linux下(Deepin15.3)提示没有
```shell
copying videoinfo.mod
copying xnu.mod
3305 块
build.sh:行37: mkisofs: 未找到命令
efi common files
2178 块
x86_64-efi
i386-efi

$ sudo apt install mkisofs
正在读取软件包列表... 完成
正在分析软件包的依赖关系树       
正在读取状态信息... 完成       
现在没有可用的软件包 mkisofs，但是它被其它的软件包引用了。
这可能意味着这个缺失的软件包可能已被废弃，
或者只能在其他发布源中找到
可是下列软件包取代了它：
  genisoimage:i386 genisoimage

E: 软件包 mkisofs 没有可供安装的候选者

$ sudo apt install genisoimage
正在读取软件包列表... 完成
正在分析软件包的依赖关系树       
正在读取状态信息... 完成       
genisoimage is already the newest version (9:1.1.11-3).

#修改脚本37行mkisofs  >  genisoimage 之后

copying xnu.mod
3305 块
Warning: creating filesystem that does not conform to ISO-9660.
I: -input-charset not specified, using utf-8 (detected in locale settings)
Size of boot image is 4 sectors -> No emulation
Total translation table size: 2048
Total rockridge attributes bytes: 409
Total directory bytes: 0
Path table size(bytes): 10
Max brk space used 0
1196 extents written (2 MB)
efi common files
2178 块
x86_64-efi
i386-efi

```

**Comment by a1ive** [comment]
> 此前我在windows下顺利生产了 iso 文件
但是linux下(Deepin15.3)提示没有
已修复：
[033793e](https://github.com/a1ive/grub2-filemanager/commit/033793ea99b2036430a9a71e11a2e3d3f20b1006)

**Comment by a1ive** [comment]
NTFS隐藏文件请参考：
https://zhidao.baidu.com/question/273630234.html

**Comment by a1ive** [comment]
在Deepin 15.4中，/boot/grub/grub.cfg与/isolinux/live.cfg的参数不一样
/boot/grub/grub.cfg
`menuentry "Install Deepin" {
	set gfxpayload=keep
	linux	/live/vmlinuz.efi boot=live union=overlay livecd-installer **locale=zh_CN** quiet splash --
	initrd	/live/initrd.lz
}`
/isolinux/live.cfg
`label live
	menu label ^Install Deepin
	menu default
	linux /live/vmlinuz
	initrd /live/initrd.lz
	append boot=live components quiet splash union=overlay livecd-installer **locales=zh_CN.UTF-8**`
请问这两者有何区别？是不是bug?

**Comment by a1ive** [comment]
经测试，locale=zh_CN无效， locales=zh_CN.UTF-8有效。
另外，如果ISO中没有中文字体，使用此参数会导致乱码，例如Kali Linux。

**Comment by sky5454** [comment]
根据Deepin 15.4 的grub菜单写即可，里面是官方写法
