### ISSUE TITLE
How to non-secure UEFI boot?

### ISSUE THREAD

**Issue by steve6375** [a1ive/grub2-filemanager#42]
I copied the x64 files to \EFI\BOOT folder but when I UEFI64 boot under VirtualBox, I get a black screen with 'Not a Secure Boot Platform 14' text in white.

**Comment by a1ive** [comment]
Not an error.
![1](https://user-images.githubusercontent.com/10670106/60097922-00b8c900-9787-11e9-9d73-263a42e4b1b9.gif)

**Comment by steve6375** [comment]
If I boot from a secure Boot PC, it boots to MokManager (but Mokmanager hangs on my PC).
Any ideas why I get this message under VBOX?
I get a similar message (but not same) from my PC when not in Secure UEFI mode.

**Comment by steve6375** [comment]
It turns out the version of grubfmx64.efi that I was using was the problem!
6,437,692 bytes  version  CRC32 15EBB886  gave the error (25 ‎June ‎2019)
10,922,576 bytes version CRC32 CC81AA7D works OK (27 May 2019)

P.S. Is there a way of making grubfmx64.efi automatically load a grub.cfg file?

**Comment by a1ive** [comment]
Version 2019-06-25 grubfmx64.efi 10853456 bytes (10 MiB) CRC32: 3C804F14
extraction error?

**Comment by a1ive** [comment]
> P.S. Is there a way of making grubfmx64.efi automatically load a grub.cfg file?

Why not build grubx64.efi with grub-mkimage.exe or grub-install.exe?

**Comment by steve6375** [comment]
Bad file!
