### ISSUE TITLE
如何UEFI模式启动NT6+ WinPE WIM。

### ISSUE THREAD

**Issue by clh021** [a1ive/grub2-filemanager#55]
一直使用您的作品作为U盘底层驱动，需要的时候进入电脑磁盘中的不同ISO以开展娱乐或工作。一般都是Linux。
偶然在您的[产品网页](https://a1ive.github.io/grub2-filemanager/)上，发现了即使UEFI也是可以启动WinPE的。需要 NT6 + WIM 的形式。
我找了很多ISO的PE从中提取WIM(提取后自己随机命名的)，在呈现菜单中都只能看到文本查看的选项，没有启动选项。我不清楚是会检查WIM内部以是否支持启动，还是根据文件名称来判断是否支持启动。特此请教。
如果方便的话，您能够贴出一个您测试通过的可以经过UEFI的方式正常启动的WinPE包。感谢！

再次感谢您做出了这么优秀，能大量节省使用者时间和精力的作品！

**Comment by a1ive** [comment]
只要文件扩展名是wim，就会出现启动的菜单。
![screenshot](https://user-images.githubusercontent.com/10670106/67659175-b47cd000-f996-11e9-9ec4-94848f31a34b.png)

**Comment by clh021** [comment]
那是不是我的使用方法不对？我通过MBR启动您的IOS，可以正常启动WinPE以及WIM包。
但是通过UEFI的方式，启动到您的EFI文件，则不可以。
我的使用方式如下：
1. 到 [这里](https://github.com/a1ive/grub2-filemanager/releases)下载最新发布的软件包
2. 解压下载的最新软件包
3. 必要的情况下格式化U盘，使U盘包含 `/EFI/BOOT` 目录
4. 拷贝解压出来的 `grubfmx64.efi` 为 `bootx64.efi` 到`/EFI/BOOT` 目录

**Comment by clh021** [comment]
您方便分享一下您测试通过的 WIM？或者测试通过的其它WIM。

**Comment by a1ive** [comment]
方法是对的。有可能你实际启动的是其他盘上老版本的grubfm，请排查一下。

**Comment by a1ive** [comment]
另外请在上图所示的界面按c进入控制台，依次输入
```
echo $file
echo $file_type
ls $path
```
并关注一下最上方显示的grub2版本。
(按下 左Ctrl+左Alt+F12 可将截图保存到U盘)
![screenshot](https://user-images.githubusercontent.com/10670106/67673232-8c9c6500-f9b4-11e9-906e-5e78605c8bf2.png)

**Comment by clh021** [comment]
查证了下，是我这个老用户没有更新到最新版，grub是2.03版本，现在更新了，加载WIM正常。
不过出现了另一个问题，该问题经过三次测试均稳定重现。
首次(拔掉U盘退出Win之后)启动进入UEFI的时候，加载会卡在一个地方
屏幕仅显示以下内容：
_                               [insmod.lst 103B 100%  122.61B/s]

然后就不动了，按ctrl+alt+delete电脑也无响应
按电脑的重启键或者关机键才会有响应。再重启进入U盘引导EFI文件就很顺利。可能和驱动有关系。

**Comment by a1ive** [comment]
这应该是电脑UEFI固件的问题。

**Comment by clh021** [comment]
好的，👍
现在机器是公司的老旧台式机
后续我再使用中会稍微注意，有问题再向您说明。感谢您的耐心讲解！谢谢！
