### ISSUE TITLE
有关自定义启动菜单

### ISSUE THREAD

**Issue by clh021** [a1ive/grub2-filemanager#56]
您好，使用您的作品后，就放弃使用 grub2 及 grub4dos 等相关产品了，一般都准备好wim或iso就可以进入我想要的系统，但是目前遇到了一项问题：
我在使用Slax系统时，希望系统尽可能在硬盘上使用系统还能保持数据持久化的特性(系统本来的特性)。Slax本身支持安装在硬盘上，但安装脚本会检测硬盘中的Windows为避免损坏Windows而放弃继续执行。我当然也不想删除Windows，查到Slax本身也支持硬盘启动，只要设置好参数即可。突然想到，几年前用grub2-filemanager似乎是能够支持自定义菜单的，当时好像是需要自己打包grub-fm.ios。
我查到文档中并无相关说明，想请问，有否内置的自定义菜单文件的方式可以实现自定义，而无需自己打包iso的。如果有，如何设置。

**Comment by clh021** [comment]
[Slax本身支持通过在硬盘上自定义启动参数以支持各种特性](https://www.slax.org/starting.php)

**Comment by a1ive** [comment]
> 有否内置的自定义菜单文件的方式可以实现自定义，而无需自己打包iso的。

/boot/grub/external_menu.cfg
主界面按F3
![深度截图_选择区域_20191031170602](https://user-images.githubusercontent.com/10670106/67933458-cbbef600-fc00-11e9-972d-186f0bb93168.png)

**Comment by clh021** [comment]
我尝试写了配置文件，不生效，连标题选项都没有出现，应该是我内容写的有误，求赐教，是我格式不对，还是我误解了这个配置文件的用法？
```
title Slax Graphics VESA mode
root (hd0,6)
kernel /boot/slx/vmlinuz initrd=/boot/slx/initrd.gz copy2ram ramdisk_size=6666 root=/dev/ram0 rw autoexec=telinit~4 changes=/slax/
initrd /boot/slx/initrd.gz

title Slax1
root (hd0,6)
kernel /boot/vmlinuz initrd=/boot/initrd.gz ramdisk_size=6666 root=/dev/ram0 rw copy2ram autoexec=xconf;telinit~4 changes=/slax/
initrd /boot/initrd.gz

title Slax2
root (hd0,6)
kernel /boot/vmlinuz root=/dev/ram0 rw real_root=/dev/sda7 autoexec=xconf;
telinit~4 changes=slaxchanges
initrd /boot/initrd.gz

#from=/dev/sda7/slax.iso
#root=/dev/sda7

title slax3 save
root (hd0,6)
kernel /boot/vmlinuz vga=791 initrd=/boot/initrd.gz ramdisk_size=7777 changes=/slax/save/changesave autoexec=xconf;kdm root=/dev/ram0 rw
initrd /boot/initrd.gz

title slax4 fresh
root (hd0,6)
kernel /boot/vmlinuz vga=791 initrd=/boot/initrd.gz ramdisk_size=7777 autoexec=xconf;kdm root=/dev/ram0 rw
initrd /boot/initrd.gz

title slax5 in Console Mode
root (hd0,6)
kernel /boot/vmlinuz initrd=/boot/initrd.gz ramdisk_size=7777 root=/dev/ram0 rw
initrd /boot/initrd.gz
```

**Comment by a1ive** [comment]
> 我尝试写了配置文件，不生效，连标题选项都没有出现，应该是我内容写的有误，求赐教，是我格式不对，还是我误解了这个配置文件的用法？
> 
> ```
> title Slax Graphics VESA mode
> root (hd0,6)
> kernel /boot/slx/vmlinuz initrd=/boot/slx/initrd.gz copy2ram ramdisk_size=6666 root=/dev/ram0 rw autoexec=telinit~4 changes=/slax/
> initrd /boot/slx/initrd.gz
> 
> title Slax1
> root (hd0,6)
> kernel /boot/vmlinuz initrd=/boot/initrd.gz ramdisk_size=6666 root=/dev/ram0 rw copy2ram autoexec=xconf;telinit~4 changes=/slax/
> initrd /boot/initrd.gz
> 
> title Slax2
> root (hd0,6)
> kernel /boot/vmlinuz root=/dev/ram0 rw real_root=/dev/sda7 autoexec=xconf;
> telinit~4 changes=slaxchanges
> initrd /boot/initrd.gz
> 
> #from=/dev/sda7/slax.iso
> #root=/dev/sda7
> 
> title slax3 save
> root (hd0,6)
> kernel /boot/vmlinuz vga=791 initrd=/boot/initrd.gz ramdisk_size=7777 changes=/slax/save/changesave autoexec=xconf;kdm root=/dev/ram0 rw
> initrd /boot/initrd.gz
> 
> title slax4 fresh
> root (hd0,6)
> kernel /boot/vmlinuz vga=791 initrd=/boot/initrd.gz ramdisk_size=7777 autoexec=xconf;kdm root=/dev/ram0 rw
> initrd /boot/initrd.gz
> 
> title slax5 in Console Mode
> root (hd0,6)
> kernel /boot/vmlinuz initrd=/boot/initrd.gz ramdisk_size=7777 root=/dev/ram0 rw
> initrd /boot/initrd.gz
> ```

这是 GRUB Legacy/GRUB4DOS 的配置文件。应当使用 GRUB2 的配置文件。
以下配置仅供参考
```
menuentry "Slax Graphics VESA mode" {
  set root=hd0,7
  linux /boot/slx/vmlinuz copy2ram ramdisk_size=6666 root=/dev/ram0 rw autoexec=telinit~4 changes=/slax/
  initrd /boot/slx/initrd.gz
}

menuentry "Slax1" {
  set root=hd0,7
  linux /boot/vmlinuz ramdisk_size=6666 root=/dev/ram0 rw copy2ram autoexec=xconf;telinit~4 changes=/slax/
  initrd /boot/initrd.gz
}
...
```

**Comment by a1ive** [comment]
> 抱歉麻烦您，我有一点点grub4dos,grub2菜单编写的基础，但不清楚这个菜单编写的具体模式。您方便方便就这个 [Slax自定义启动](https://www.slax.org/starting.php) 文档给予一点指导？然后我就可以尝试修改成适合我当前环境的菜单了。麻烦您了。

就是普通的 GRUB2 菜单。

**Comment by a1ive** [comment]
```
menuentry "Slax" {
  set slax_kernel=/boot/vmlinuz
  set slax_initrd=/boot/initrd.gz
  search -s -f $slax_kernel
  linux $slax_kernel slax.flags=perch
  initrd $slax_initrd
}
```

**Comment by clh021** [comment]
感谢！已经可以看到菜单了，我再研究一下启动细节。感谢！
