### ISSUE TITLE
找不到启动资源的奇怪问题

### ISSUE THREAD

**Issue by clh021** [a1ive/grub2-filemanager#61]
公司给配了一台 戴尔 Latitude 7300笔记本电脑。
经过一番折腾，终于安装上了linux并成功通过efi启动进入 grub-fm。
奇怪的地方来了：电脑中包含有 ntfs分区和ext分区。
无论external_menu.cfg放在什么文件系统的分区，grub-fm都能找到，但是对应的启动资源却找不到，总是停留在  looking for /iso/****.iso    处，然后失败。

**Comment by a1ive** [comment]
外置菜单内容？

**Comment by clh021** [comment]
刚刚又测试了一个情况，补充一下
仅在slax及类似定制iso都会出现这个情况。Ubuntu及Debian则没有这种问题。
我立刻再测试一下bionic puppy及proteus linux。

**Comment by clh021** [comment]
外置菜单内容在其它机器上长期使用，没有问题。
使用文件选择器选择 磁盘上已经看到的slax也会出现 looking for /iso .......失败。所以初步判断跟外置菜单无关，可能和slax这种系统的驱动有关，好像读不了硬盘一样。

**Comment by a1ive** [comment]
这种情况是slax自己的问题。与文件管理器无关。
一般体积比较小的linux驱动可能不足。
另外一种就是Fedora/CentOS系的ISO比较弱智，没有添加ntfs支持。

**Comment by clh021** [comment]
```
set slax_kernel=/slax/boot/vmlinuz
set slax_initrd=/slax/boot/initrfs.img
set slax_param="";
menuentry "Porteus" --class porteus {
    set kernel=/porteus/boot/syslinux/vmlinuz
    set initrd=/porteus/boot/syslinux/initrd.xz
    search -s -f $kernel
    linux $kernel changes=/porteus/changes timezone=Asia/Shanghai
    initrd $initrd
}
menuentry "Slax no" --class slax {
    search -s -f $slax_kernel
    linux $slax_kernel
    initrd $slax_initrd
}
menuentry "Slax perch" --class slax {
    search -s -f $slax_kernel
    linux $slax_kernel slax.flags=perch
    initrd $slax_initrd
}
menuentry "Reboot" --class reboot --class os{
  reboot
}
menuentry "Halt" --class halt --class os{
  halt
}

```

**Comment by clh021** [comment]
好的，我稍后再试一次，也许是电脑太新了
磁盘型号是：SSDPEMKF512G8 NVMe INTEL 512GB ( 512 GB )
也许只能在新电脑上放弃使用模块化系统了，可是真不想放弃模块化系统啊……

**Comment by a1ive** [comment]
> 好的，我稍后再试一次，也许是电脑太新了
> 磁盘型号是：SSDPEMKF512G8 NVMe INTEL 512GB ( 512 GB )
> 也许只能在新电脑上放弃使用模块化系统了，可是真不想放弃模块化系统啊……

估计是因为slax的内核编译配置把nvme驱动前面选的是"m" 而不是 "*"。
建议自己编译新版内核，磁盘驱动全部勾上，把"m"的选择全部改成"*"
选"m" 会把驱动编译成内核模块，按需加载，"*"则是直接做到内核里面。
