### ISSUE TITLE
how to decompress and compress install.gz right way?

### ISSUE THREAD

**Issue by niemtin007** [a1ive/grub2-filemanager#66]
Hello a1ive,

Thank you for your hard work to bring many awesome features to the grub2-filemanager. I have learned a lot from you.

I want to change some code from start.bat in the install.gz but I don't know how to decompress and compress it again in the right way to work well in your tool. So, can you give me a guide about this one? 

Thanks.

**Comment by a1ive** [comment]
`find ./install | cpio -o -H newc | gzip -9 > ./install.gz`

**Comment by niemtin007** [comment]
Thank you for your quick reply.

When I tried following you guide I still have meet an error:
![error](https://user-images.githubusercontent.com/12592676/71708194-fa846300-2e21-11ea-9d73-a6ddf7e4913d.jpg)

decompress:
![decompress](https://user-images.githubusercontent.com/12592676/71708205-0e2fc980-2e22-11ea-9a51-f8ee13da9237.jpg)

compress
![compress](https://user-images.githubusercontent.com/12592676/71708210-18ea5e80-2e22-11ea-92a4-6fd0b430377e.jpg)

**Comment by a1ive** [comment]
My OS is Manjaro Linux.
I can decompress it without error.
Maybe you could use 7-ZIP to decompress it.

**Comment by niemtin007** [comment]
I tried to decompress and compress it on Manjaro Linux but still have met the "bad file" error like before.

Could you help me to change the start.bat content like below and send me a new install.gz, thanks.

`
@echo off
%cd%\wpeinit.exe
ren %cd%\wpeinit.exe wpeinit.exe.old
set arch=x64
if %PROCESSOR_ARCHITECTURE% == x86 (
  set arch=x86
  )
echo Operating System is %arch% bit
echo Installing ISO Driver
mount_%arch%.exe -xi
for /f "tokens=1,2 delims==" %%a in ('find "installiso=" null.cfg') do set "isopath=%%b"
echo ISO Path: %isopath%

for %%I in (C D E F G H I J K L M N O P Q R S T U V W X Y Z) do if exist "%%I:%isopath%" set isodrive=%%I:
if "%isodrive%"=="" (
echo ERROR - COULD NOT FIND ISO!

goto :EOF
)
echo ISO Full Path: %isodrive%%isopath%

mount_%arch%.exe -m:r "%isodrive%%isopath%"

MODE CON COLS=30 LINES=4
cls
echo DO NOT CLOSE THIS WINDOW
echo Please wait ...
ping -n 6 127.0.0.1 >nul
for %%i in (A B C D E F G H I J K L M N O P Q R S T U V W X Y Z) do (
if exist %%i:\sources\install.wim call :wim %%i 
if exist %%i:\sources\install.esd call :esd %%i
if exist %%i:\%arch%\sources\install.* %%i:\%arch%\setup.exe 
if exist %%i:\%arch%\ call :End 
)
:wim
X:\setup.exe /installfrom:"%1:\sources\install.wim" 
goto :End
:esd
X:\setup.exe /installfrom:"%1:\sources\install.esd" 
goto :End
:End
echo.
echo Press any key to exit...
pause >nul
exit

`

**Comment by a1ive** [comment]
> compress:
> 
> ```
> find ./install | cpio -o -H newc | gzip -9 > ./install.gz
> ```
> 
> decompress:
> 
> ```
> gzip -d install.gz
> cpio -idm < install
> ```

sorry, I made a mistake.
compress:
cd install
**find .** | cpio -o -H newc | gzip -9 > ../install.gz

**Comment by niemtin007** [comment]
### WE DIT IT !!!

Thank you for your help.

Great! Now we can run any ISO Windows with name contains spaces ^^

You can remove this message in your code. We no need this warning anymore:

> File path contains spaces. This may cause problems! Press any key to continue.

Please change your start.bat content like below and rebuild your install.gz:

![image](https://user-images.githubusercontent.com/12592676/71712249-062e5480-2e37-11ea-86aa-d0d21977330c.png)

**Comment by a1ive** [comment]
Thanks.
> You can remove this message in your code. We no need this warning anymore: 
> > File path contains spaces. This may cause problems! Press any key to continue.

This warning is for linux isos.

> Please change your start.bat content like below and rebuild your install.gz

It would be better if you could create a pull request.
