### ISSUE TITLE
Compile errors - is this normal?

### ISSUE THREAD

**Issue by steve6375** [a1ive/grub2-filemanager#67]
steve@steve-VirtualBox ~/grub2-filemanager $ sudo ./build.sh
checking for gettext ... ok
checking for mkisofs ... ok
checking for grub ... ok
common files
Language / 语言 / 語言
1. Simplified Chinese / 简体中文
2. Traditional Chinese / 正體中文
3. English (United States)
4. Turkish
5. German
6. Vietnamese
7. Russian
8. Hebrew
Please make a choice: 3
en_US
x86_64-efi
copying ahci.mod
cp: cannot stat ‘grub/x86_64-efi/ahci.mod’: No such file or directory
copying ata.mod
cp: cannot stat ‘grub/x86_64-efi/ata.mod’: No such file or directory
copying crypto.mod
cp: cannot stat ‘grub/x86_64-efi/crypto.mod’: No such file or directory
copying cryptodisk.mod
cp: cannot stat ‘grub/x86_64-efi/cryptodisk.mod’: No such file or directory
copying gcry_sha256.mod
cp: cannot stat ‘grub/x86_64-efi/gcry_sha256.mod’: No such file or directory
copying gcry_sha512.mod
cp: cannot stat ‘grub/x86_64-efi/gcry_sha512.mod’: No such file or directory
copying geli.mod
cp: cannot stat ‘grub/x86_64-efi/geli.mod’: No such file or directory
copying luks.mod
cp: cannot stat ‘grub/x86_64-efi/luks.mod’: No such file or directory
copying pbkdf2.mod
cp: cannot stat ‘grub/x86_64-efi/pbkdf2.mod’: No such file or directory
copying scsi.mod
cp: cannot stat ‘grub/x86_64-efi/scsi.mod’: No such file or directory
5847 blocks
grub-mkimage: error: cannot open `./grub/x86_64-efi/moddep.lst': No such file or directory.
i386-efi
copying ahci.mod
cp: cannot stat ‘grub/i386-efi/ahci.mod’: No such file or directory
copying ata.mod
cp: cannot stat ‘grub/i386-efi/ata.mod’: No such file or directory
copying crypto.mod
cp: cannot stat ‘grub/i386-efi/crypto.mod’: No such file or directory
copying cryptodisk.mod
cp: cannot stat ‘grub/i386-efi/cryptodisk.mod’: No such file or directory
copying gcry_sha256.mod
cp: cannot stat ‘grub/i386-efi/gcry_sha256.mod’: No such file or directory
copying gcry_sha512.mod
cp: cannot stat ‘grub/i386-efi/gcry_sha512.mod’: No such file or directory
copying geli.mod
cp: cannot stat ‘grub/i386-efi/geli.mod’: No such file or directory
copying luks.mod
cp: cannot stat ‘grub/i386-efi/luks.mod’: No such file or directory
copying pbkdf2.mod
cp: cannot stat ‘grub/i386-efi/pbkdf2.mod’: No such file or directory
copying scsi.mod
cp: cannot stat ‘grub/i386-efi/scsi.mod’: No such file or directory
5587 blocks
grub-mkimage: error: cannot open `./grub/i386-efi/moddep.lst': No such file or directory.
i386-pc
copying acpi.mod
cp: cannot stat ‘grub/i386-pc/acpi.mod’: No such file or directory
copying affs.mod
cp: cannot stat ‘grub/i386-pc/affs.mod’: No such file or directory
copying afs.mod
cp: cannot stat ‘grub/i386-pc/afs.mod’: No such file or directory
copying all_video.mod
cp: cannot stat ‘grub/i386-pc/all_video.mod’: No such file or directory
copying aout.mod
cp: cannot stat ‘grub/i386-pc/aout.mod’: No such file or directory
copying bfs.mod
cp: cannot stat ‘grub/i386-pc/bfs.mod’: No such file or directory
copying bitmap.mod
cp: cannot stat ‘grub/i386-pc/bitmap.mod’: No such file or directory
copying bitmap_scale.mod
cp: cannot stat ‘grub/i386-pc/bitmap_scale.mod’: No such file or directory
copying blocklist.mod
cp: cannot stat ‘grub/i386-pc/blocklist.mod’: No such file or directory
copying bsd.mod
cp: cannot stat ‘grub/i386-pc/bsd.mod’: No such file or directory
copying btrfs.mod
cp: cannot stat ‘grub/i386-pc/btrfs.mod’: No such file or directory
copying cat.mod
cp: cannot stat ‘grub/i386-pc/cat.mod’: No such file or directory
copying cmp.mod
cp: cannot stat ‘grub/i386-pc/cmp.mod’: No such file or directory
copying commandline.mod
cp: cannot stat ‘grub/i386-pc/commandline.mod’: No such file or directory
copying cpuid.mod
cp: cannot stat ‘grub/i386-pc/cpuid.mod’: No such file or directory
copying crc.mod
cp: cannot stat ‘grub/i386-pc/crc.mod’: No such file or directory
copying date.mod
cp: cannot stat ‘grub/i386-pc/date.mod’: No such file or directory
copying datehook.mod
cp: cannot stat ‘grub/i386-pc/datehook.mod’: No such file or directory
copying datetime.mod
cp: cannot stat ‘grub/i386-pc/datetime.mod’: No such file or directory
copying dd.mod
cp: cannot stat ‘grub/i386-pc/dd.mod’: No such file or directory
copying disk.mod
cp: cannot stat ‘grub/i386-pc/disk.mod’: No such file or directory
copying diskfilter.mod
cp: cannot stat ‘grub/i386-pc/diskfilter.mod’: No such file or directory
copying dm_nv.mod
cp: cannot stat ‘grub/i386-pc/dm_nv.mod’: No such file or directory
copying drivemap.mod
cp: cannot stat ‘grub/i386-pc/drivemap.mod’: No such file or directory
copying elf.mod
cp: cannot stat ‘grub/i386-pc/elf.mod’: No such file or directory
copying eval.mod
cp: cannot stat ‘grub/i386-pc/eval.mod’: No such file or directory
copying expr.mod
cp: cannot stat ‘grub/i386-pc/expr.mod’: No such file or directory
copying f2fs.mod
cp: cannot stat ‘grub/i386-pc/f2fs.mod’: No such file or directory
copying fdlibm.mod
cp: cannot stat ‘grub/i386-pc/fdlibm.mod’: No such file or directory
copying file.mod
cp: cannot stat ‘grub/i386-pc/file.mod’: No such file or directory
copying freedos.mod
cp: cannot stat ‘grub/i386-pc/freedos.mod’: No such file or directory
copying functional_test.mod
cp: cannot stat ‘grub/i386-pc/functional_test.mod’: No such file or directory
copying gcry_md5.mod
cp: cannot stat ‘grub/i386-pc/gcry_md5.mod’: No such file or directory
copying getkey.mod
cp: cannot stat ‘grub/i386-pc/getkey.mod’: No such file or directory
copying gfxmenu.mod
cp: cannot stat ‘grub/i386-pc/gfxmenu.mod’: No such file or directory
copying gfxterm.mod
cp: cannot stat ‘grub/i386-pc/gfxterm.mod’: No such file or directory
copying gfxterm_background.mod
cp: cannot stat ‘grub/i386-pc/gfxterm_background.mod’: No such file or directory
copying gfxterm_menu.mod
cp: cannot stat ‘grub/i386-pc/gfxterm_menu.mod’: No such file or directory
copying gptsync.mod
cp: cannot stat ‘grub/i386-pc/gptsync.mod’: No such file or directory
copying hashsum.mod
cp: cannot stat ‘grub/i386-pc/hashsum.mod’: No such file or directory
copying hexdump.mod
cp: cannot stat ‘grub/i386-pc/hexdump.mod’: No such file or directory
copying hfs.mod
cp: cannot stat ‘grub/i386-pc/hfs.mod’: No such file or directory
copying hfsplus.mod
cp: cannot stat ‘grub/i386-pc/hfsplus.mod’: No such file or directory
copying jfs.mod
cp: cannot stat ‘grub/i386-pc/jfs.mod’: No such file or directory
copying jpeg.mod
cp: cannot stat ‘grub/i386-pc/jpeg.mod’: No such file or directory
copying keystatus.mod
cp: cannot stat ‘grub/i386-pc/keystatus.mod’: No such file or directory
copying legacycfg.mod
cp: cannot stat ‘grub/i386-pc/legacycfg.mod’: No such file or directory
copying loadenv.mod
cp: cannot stat ‘grub/i386-pc/loadenv.mod’: No such file or directory
copying lsacpi.mod
cp: cannot stat ‘grub/i386-pc/lsacpi.mod’: No such file or directory
copying lsapm.mod
cp: cannot stat ‘grub/i386-pc/lsapm.mod’: No such file or directory
copying lvm.mod
cp: cannot stat ‘grub/i386-pc/lvm.mod’: No such file or directory
copying macho.mod
cp: cannot stat ‘grub/i386-pc/macho.mod’: No such file or directory
copying mmap.mod
cp: cannot stat ‘grub/i386-pc/mmap.mod’: No such file or directory
copying mdraid09.mod
cp: cannot stat ‘grub/i386-pc/mdraid09.mod’: No such file or directory
copying mdraid09_be.mod
cp: cannot stat ‘grub/i386-pc/mdraid09_be.mod’: No such file or directory
copying multiboot.mod
cp: cannot stat ‘grub/i386-pc/multiboot.mod’: No such file or directory
copying multiboot2.mod
cp: cannot stat ‘grub/i386-pc/multiboot2.mod’: No such file or directory
copying net.mod
cp: cannot stat ‘grub/i386-pc/net.mod’: No such file or directory
copying offsetio.mod
cp: cannot stat ‘grub/i386-pc/offsetio.mod’: No such file or directory
copying part_apple.mod
cp: cannot stat ‘grub/i386-pc/part_apple.mod’: No such file or directory
copying part_bsd.mod
cp: cannot stat ‘grub/i386-pc/part_bsd.mod’: No such file or directory
copying partnew.mod
cp: cannot stat ‘grub/i386-pc/partnew.mod’: No such file or directory
copying parttool.mod
cp: cannot stat ‘grub/i386-pc/parttool.mod’: No such file or directory
copying password.mod
cp: cannot stat ‘grub/i386-pc/password.mod’: No such file or directory
copying png.mod
cp: cannot stat ‘grub/i386-pc/png.mod’: No such file or directory
copying priority_queue.mod
cp: cannot stat ‘grub/i386-pc/priority_queue.mod’: No such file or directory
copying probe.mod
cp: cannot stat ‘grub/i386-pc/probe.mod’: No such file or directory
copying procfs.mod
cp: cannot stat ‘grub/i386-pc/procfs.mod’: No such file or directory
copying progress.mod
cp: cannot stat ‘grub/i386-pc/progress.mod’: No such file or directory
copying raid5rec.mod
cp: cannot stat ‘grub/i386-pc/raid5rec.mod’: No such file or directory
copying raid6rec.mod
cp: cannot stat ‘grub/i386-pc/raid6rec.mod’: No such file or directory
copying random.mod
cp: cannot stat ‘grub/i386-pc/random.mod’: No such file or directory
copying read.mod
cp: cannot stat ‘grub/i386-pc/read.mod’: No such file or directory
copying reboot.mod
cp: cannot stat ‘grub/i386-pc/reboot.mod’: No such file or directory
copying regexp.mod
cp: cannot stat ‘grub/i386-pc/regexp.mod’: No such file or directory
copying reiserfs.mod
cp: cannot stat ‘grub/i386-pc/reiserfs.mod’: No such file or directory
copying search_fs_uuid.mod
cp: cannot stat ‘grub/i386-pc/search_fs_uuid.mod’: No such file or directory
copying search_label.mod
cp: cannot stat ‘grub/i386-pc/search_label.mod’: No such file or directory
copying sendkey.mod
cp: cannot stat ‘grub/i386-pc/sendkey.mod’: No such file or directory
copying serial.mod
cp: cannot stat ‘grub/i386-pc/serial.mod’: No such file or directory
copying squash4.mod
cp: cannot stat ‘grub/i386-pc/squash4.mod’: No such file or directory
copying syslinuxcfg.mod
cp: cannot stat ‘grub/i386-pc/syslinuxcfg.mod’: No such file or directory
copying terminfo.mod
cp: cannot stat ‘grub/i386-pc/terminfo.mod’: No such file or directory
copying tga.mod
cp: cannot stat ‘grub/i386-pc/tga.mod’: No such file or directory
copying time.mod
cp: cannot stat ‘grub/i386-pc/time.mod’: No such file or directory
copying trig.mod
cp: cannot stat ‘grub/i386-pc/trig.mod’: No such file or directory
copying true.mod
cp: cannot stat ‘grub/i386-pc/true.mod’: No such file or directory
copying vbe.mod
cp: cannot stat ‘grub/i386-pc/vbe.mod’: No such file or directory
copying vboot.mod
cp: cannot stat ‘grub/i386-pc/vboot.mod’: No such file or directory
copying version.mod
cp: cannot stat ‘grub/i386-pc/version.mod’: No such file or directory
copying vga.mod
cp: cannot stat ‘grub/i386-pc/vga.mod’: No such file or directory
copying vhd.mod
cp: cannot stat ‘grub/i386-pc/vhd.mod’: No such file or directory
copying video.mod
cp: cannot stat ‘grub/i386-pc/video.mod’: No such file or directory
copying video_bochs.mod
cp: cannot stat ‘grub/i386-pc/video_bochs.mod’: No such file or directory
copying video_cirrus.mod
cp: cannot stat ‘grub/i386-pc/video_cirrus.mod’: No such file or directory
copying video_colors.mod
cp: cannot stat ‘grub/i386-pc/video_colors.mod’: No such file or directory
copying video_fb.mod
cp: cannot stat ‘grub/i386-pc/video_fb.mod’: No such file or directory
copying videoinfo.mod
cp: cannot stat ‘grub/i386-pc/videoinfo.mod’: No such file or directory
copying xfs.mod
cp: cannot stat ‘grub/i386-pc/xfs.mod’: No such file or directory
copying xnu.mod
cp: cannot stat ‘grub/i386-pc/xnu.mod’: No such file or directory
copying zfs.mod
cp: cannot stat ‘grub/i386-pc/zfs.mod’: No such file or directory
copying zstd.mod
cp: cannot stat ‘grub/i386-pc/zstd.mod’: No such file or directory
copying ahci.mod
cp: cannot stat ‘grub/i386-pc/ahci.mod’: No such file or directory
copying ata.mod
cp: cannot stat ‘grub/i386-pc/ata.mod’: No such file or directory
copying crypto.mod
cp: cannot stat ‘grub/i386-pc/crypto.mod’: No such file or directory
copying cryptodisk.mod
cp: cannot stat ‘grub/i386-pc/cryptodisk.mod’: No such file or directory
copying gcry_sha256.mod
cp: cannot stat ‘grub/i386-pc/gcry_sha256.mod’: No such file or directory
copying gcry_sha512.mod
cp: cannot stat ‘grub/i386-pc/gcry_sha512.mod’: No such file or directory
copying geli.mod
cp: cannot stat ‘grub/i386-pc/geli.mod’: No such file or directory
copying luks.mod
cp: cannot stat ‘grub/i386-pc/luks.mod’: No such file or directory
copying pbkdf2.mod
cp: cannot stat ‘grub/i386-pc/pbkdf2.mod’: No such file or directory
copying pci.mod
cp: cannot stat ‘grub/i386-pc/pci.mod’: No such file or directory
copying scsi.mod
cp: cannot stat ‘grub/i386-pc/scsi.mod’: No such file or directory
5470 blocks
grub-mkimage: error: cannot open `./grub/i386-pc/moddep.lst': No such file or directory.
cat: grub/i386-pc/cdboot.img: No such file or directory
Warning: creating filesystem that does not conform to ISO-9660.
I: -input-charset not specified, using utf-8 (detected in locale settings)
Size of boot image is 4 sectors -> No emulation
Total translation table size: 2048
Total rockridge attributes bytes: 1265
Total directory bytes: 2048
Path table size(bytes): 28
Max brk space used 0
2174 extents written (4 MB)
steve@steve-VirtualBox ~/grub2-filemanager $ ls -l
total 4792
drwxr-xr-x  6 root root    4096 Jan  3 10:05 arch
drwxr-xr-x  2 root root    4096 Jan  3 10:05 bin
drwxr-xr-x  3 root root    4096 Jan  3 10:05 boot
-rw-r--r--  1 root root    5015 Jan  3 10:05 build.bat
-rwxr-xr-x  1 root root    4984 Jan  3 10:05 build.sh
-rw-r--r--  1 root root     165 Jan  3 10:05 crowdin.yml
-rwxr-xr-x  1 root root     310 Jan  3 10:05 gencrt.sh
-rw-r--r--  1 root root       0 Jan  3 10:09 grubfmia32.efi
-rw-r--r--  1 root root 4452352 Jan  3 10:09 grubfm.iso
-rw-r--r--  1 root root       0 Jan  3 10:09 grubfmx64.efi
drwxr-xr-x 13 root root    4096 Jan  3 10:05 lang
-rw-r--r--  1 root root   35141 Jan  3 10:05 LICENSE
-rw-r--r--  1 root root  343492 Jan  3 10:05 loadfm
-rwxr-xr-x  1 root root    1303 Jan  3 10:05 preloader.sh
-rw-r--r--  1 root root    3466 Jan  3 10:05 README.md
-rwxr-xr-x  1 root root     642 Jan  3 10:05 release.sh
drwxr-xr-x  3 root root    4096 Jan  3 10:05 samples
drwxr-xr-x  2 root root    4096 Jan  3 10:05 secureboot
-rwxr-xr-x  1 root root     221 Jan  3 10:05 sign.sh
-rwxr-xr-x  1 root root     161 Jan  3 10:05 update_grub2.sh
-rw-r--r--  1 root root     510 Jan  3 10:05 update_grub4dos.bat

**Comment by a1ive** [comment]
Sorry, instructions in README.md are outdated.
Please run `./update_grub2.sh` to download grub2 binary.
If you are using windows, just download it from https://github.com/a1ive/grub/releases/tag/latest and unzip it.
#65

**Comment by steve6375** [comment]
sudo ./update_grub2.sh worked - thanks.
