### ISSUE TITLE
What files\folders are required for bootable media?

### ISSUE THREAD

**Issue by steve6375** [a1ive/grub2-filemanager#69]
After building filemanager, there are no instructions on what files\folders are required to be copied to bootable media - e.g. USB drive.
For instance, UEFI booting does not work if copy \secureboot folder contents to \EFI\BOOT folder because it says grubfmx64.efi is missing on UEFI-boot even though it is in the root.
What other files are needed and where should they be placed?
Is \arch folder required to be on bootable media?
Please give folder structure (or better yet, .sh and .cmd file which copies correct files to a partition).
For UEFI-booting, a FAT32 partition is required. Can a 2nd partition be created to hold payload files (e.g. NTFS, exFAT, ext2/3/4)? Presumably NTFS will be most compatible for Windows Install ISOs?
![image](https://user-images.githubusercontent.com/1469350/71724812-95347000-2e29-11ea-9a60-a024bcc3b636.png)
P.S. Very nice work! :-)

**Comment by a1ive** [comment]
For UEFI booting, just copy grubfmx64.efi/grubfmia32.efi to any partition, and chainload it using any bootloader (e.g. grub2/rEFInd).
For UEFI Secure booting, the instructiions are outdated. I recommend "[Super-UEFIinSecureBoot-Disk
](https://github.com/ValdikSS/Super-UEFIinSecureBoot-Disk)" or https://habr.com/ru/post/446238/

**Comment by steve6375** [comment]
OK. I copied the grubfm files to \EFI\BOOT and it works without needing any grub bootloader.
For Super-UEFIinSecureBootDisk, I replaced  grubx64_real.efi with grubfmx64.efi and grubia32_real.efi with grubfmia32.efi.
However, I have found a lot of problems with MokManager on various systems. It is very unreliable.
P.S. I have also found that quite a few systems do not like scrolling in the grub2 graphical menu system (when using a theme scrolling is very slow - about 1 seconds per line). For this reason I prefer to have a choice of  theme or no theme. Maybe add an F button to toggle theme on\off?
Thanks!

**Comment by a1ive** [comment]
> OK. I copied the grubfm files to \EFI\BOOT and it works without needing any grub bootloader.
> For Super-UEFIinSecureBootDisk, I replaced grubx64_real.efi with grubfmx64.efi and grubia32_real.efi with grubfmia32.efi.
> However, I have found a lot of problems with MokManager on various systems. It is very unreliable.
> P.S. I have also found that quite a few systems do not like scrolling in the grub2 graphical menu system (when using a theme scrolling is very slow - about 1 second per line). For this reason I prefer to have a choice of theme or no theme. Maybe add an F button to toggle theme on\off?
> Thanks!

> However, I have found a lot of problems with MokManager on various systems. It is very unreliable.

Yes, we all know MokManager sucks.
Inspired by [ValdikSS's article](https://habr.com/en/post/446238/), I have a better solution to circumvent UEFI Secure Boot to load ANY unsigned efi application.
See http://bbs.wuyou.net/forum.php?mod=viewthread&tid=416924 (Simplified Chinese)
[sb_minimal.zip](https://github.com/a1ive/grub2-filemanager/files/4021768/sb_minimal.zip)

> I have also found that quite a few systems do not like scrolling in the grub2 graphical menu system (when using a theme scrolling is very slow - about 1 second per line). For this reason I prefer to have a choice of theme or no theme. Maybe add an F button to toggle theme on\off?

Already planed in 'next' branch.

**Comment by steve6375** [comment]
Wow! It works (for Secure Boot UEFI64). 🥇

**Comment by Qwertylex** [comment]
what about for MBR / BIOS / i386-pc? How do I install this to a USB drive? [I'm on linux]
