### ISSUE TITLE
file info option can take a long time

### ISSUE THREAD

**Issue by steve6375** [a1ive/grub2-filemanager#70]
Calculating CRC32 on large files can take many minutes.
Suggest asking user first if file > 200MB in size?
'CRC32 (Y/N)'
![image](https://user-images.githubusercontent.com/1469350/71725323-5b646900-2e2b-11ea-869c-45a72e1ad93f.png)

Also file size does not seem correct ??

**Comment by a1ive** [comment]
Maybe I should remove the "File Info" menu entry, it's useless.
BTW I'm rewriting this project using C, see ['next'](https://github.com/a1ive/grub2-filemanager/tree/next) branch. File size should be displayed in boot menu.
![screen](https://user-images.githubusercontent.com/10670106/71758038-029dda80-2ed6-11ea-8a5e-9771942c879d.png)
