### ISSUE TITLE
Do not list NTFS filesystem files

### ISSUE THREAD

**Issue by steve6375** [a1ive/grub2-filemanager#71]
Recycle bin, $Extend, System Volume Information and $ files
![image](https://user-images.githubusercontent.com/1469350/71726050-cb73ee80-2e2d-11ea-8744-1dcb2d508cab.png)
![image](https://user-images.githubusercontent.com/1469350/71726076-e181af00-2e2d-11ea-923c-ed0b40b519da.png)

**Comment by niemtin007** [comment]
Hello steve6375,

If you want to hide the filesystem files you can modify `enum_file` function in the `main.lua` like below:

```
function enum_file (name)
    local item = path .. "/" .. name
    local name_temp = string.lower(name)
    local name_temp = string.match (name_temp, "^%$")
    if name_temp ~= "$" then
      if grub.file_exist (item) then
          i = i + 1
          f_table[i] = name
      elseif (name ~= "." and name ~= "..") then
          j = j + 1
          d_table[j] = name
      end
    end
end
```

Then rebuild the grub2-filemanager.

**Preview**:
![image](https://user-images.githubusercontent.com/12592676/71770983-a33bdb00-2f66-11ea-9584-ec35fa38ff6b.png)

**Comment by steve6375** [comment]
Thanks. That works. Will main.lua be updated?

**Comment by a1ive** [comment]
@niemtin007 It would be nice if you could create a pull request.
