### ISSUE TITLE
UEFI boot using partnew supported?

### ISSUE THREAD

**Issue by steve6375** [a1ive/grub2-filemanager#72]
Ubuntu x64 ISO does not boot using  map option when UEFI64 booting.
Is partnew implemented?
It should be possible to generically boot **most** Linux ISOs without cheat codes or loopback.cfg files, by using partnew and map commands?

**Comment by steve6375** [comment]
Example:

![image](https://user-images.githubusercontent.com/1469350/71728967-7ee0e100-2e36-11ea-95ab-9338a906752f.png)

**Comment by a1ive** [comment]
> It should be possible to generically boot most Linux ISOs without cheat codes or loopback.cfg files, by using partnew and map commands?

Yes, but I don't like it, because partnew will write the partition table.What if the ISO is on a hard drive?

**Comment by steve6375** [comment]
You should check that partition is the MBR type and that partition #4 has no Type number (type - 0) before using the partnew command.
Also use Type 0 for the partnew type and check that the ISO file is contiguous.
In this way it will not harm the disk partition table and it is safe.

You already use partnew (Easy2Boot) for MBR File Manager - why not for UEFI?
It can boot 99% of ISOs without needing to know any kernel parameters\cheat codes. The problem with Linux is that there as so many distros and versions and they change their cheat codes a lot. This means that any men which uses kernel parameters stops working after a few month or a year, so you have to keep updating the menu code and then it doesn't work with older versions, etc.
Using map + partnew removes all these issues (but the file must be contiguous).

**Comment by steve6375** [comment]
P.S. MBR 'Easy2Boot' menu seems to use grub4dos for the map command???
![image](https://user-images.githubusercontent.com/1469350/71763585-8acfb000-2ed5-11ea-8df6-dbb9f63bce19.png)

**Comment by steve6375** [comment]
code says hd0,4 - is this always correct? is only hd0 ever used?

 `command = "echo " .. grub.gettext ("WARNING: Will erase ALL data on (hd0,4).") .. "; " ..`

**Comment by a1ive** [comment]
> code says hd0,4 - is this always correct? is only hd0 ever used?
> 
> `command = "echo " .. grub.gettext ("WARNING: Will erase ALL data on (hd0,4).") .. "; " ..`
```
devnum = string.match (device, "^(hd%d+),msdos[1-3]$")
```
```
"\n  partnew --type=0x00 --file=" .. file .. " " .. devnum .. " 4" ..
```
> `command = "echo " .. grub.gettext ("WARNING: Will erase ALL data on (hd0,4).") .. "; " ..`
This is just the text displayed.

**Comment by a1ive** [comment]
> P.S. MBR 'Easy2Boot' menu seems to use grub4dos for the map command???

Yes.

**Comment by steve6375** [comment]
> This is just the text displayed.

yes, so user could say yes, but is destroys #4 partition on a different disk ?
