### ISSUE TITLE
Request: Add ability to add own menus

### ISSUE THREAD

**Issue by steve6375** [a1ive/grub2-filemanager#74]
Not sure if this is already a feature - if so how to do it?

For instance, if a file with a special extension is found (e.g. .grub2) then assume it contains grub2 code for a menuentry and add the menu entry into the open menu using source command

In the environment, we have:
$root $path $file $file_type $grub_platform $grub_cpu

but $file_name (name of file with no extension)  and $file_path (path of file with no device) and file_ext (extension of file)  are missing. Could you add these as variables? This will allow the user to use these variable in their own menuentry menus.

e.g.  mylinux.grub2

menuentry "$file_name" --class android {
    set isofile=$path/$file_name.$file_ext
    loopback loop $file
    linux (loop)/casper/vmlinuz.efi boot=casper iso-scan/filename=$isofile noprompt noeject
    initrd (loop)/casper/initrd.lz
}

We could also use if  tests for i386 or uefi and add menus for persistence by using partnew commands with an ext partition image. What do you think?

Also how can the user add a menu entry to return back to the previous menu (open menu)?

**Comment by a1ive** [comment]
I have rewritten the main part of the file manager and uploaded the code.
Adding a custom "open with" menu is now easier.
See [/boot/grub/types](https://github.com/a1ive/grub2-filemanager/tree/master/boot/grub/types) and [/boot/grub/rules](https://github.com/a1ive/grub2-filemanager/tree/master/boot/grub/rules).

**Comment by a1ive** [comment]
Under /boot/grub/types, the file name is the extension of files in file manager (e.g. wim for *.wim).
The syntax of configuration files is INI.
```
[type]
icon = wim
default = 0

[0]
menu = wim/wimboot.sh
title = "Boot NT6.x WIM (wimboot)"
icon = wim
enable = all

[1]
menu = wim/ntboot.sh
title = "Boot NT6.x WIM (NTBOOT)"
icon = nt6
enable = all
```
In 'type' section, only 'icon' parameter is currently supported.

**Comment by steve6375** [comment]
Don't quite get it.
So how does the end user (not developer) make a grub2 menu for a particular ISO (for instance)?

**Comment by a1ive** [comment]
I've made an example.
This feature requires latest grub2.
See [/boot/grub/types/iso](https://github.com/a1ive/grub2-filemanager/blob/master/boot/grub/types/iso).
This file defines "open menu" of iso files.
It has 3 menu entries,each menu entry has its own serial number, starting from "0", without interruption in the middle. ([0], [1], [2], [3], ...)
![深度截图_选择区域_20200108202032](https://user-images.githubusercontent.com/10670106/71977729-80564300-3254-11ea-951b-d9d27b6dea32.png)

Each menu entry has mutiple keys, some of them are required (menu, title), some are optional (icon, condition, enable).
Take menu entry "[0]" for example,
```
[0]
menu = iso/loop.sh
condition = iso/loop_test.sh
title = "Boot ISO (Loopback)"
icon = gnu-linux
enable = all
```
"title = Boot ISO (Loopback)" defines the title of menu.
"menu = iso/loop.sh" means this menu entry will execute `configfile (memdisk)/boot/grub/rules/iso/loop.sh`
![深度截图_选择区域_20200108202051](https://user-images.githubusercontent.com/10670106/71977756-949a4000-3254-11ea-8189-82f01c062aef.png)
In [/boot/grub/rules/iso/loop.sh](https://github.com/a1ive/grub2-filemanager/blob/master/boot/grub/rules/iso/loop.sh), you could see the code to loopback-boot iso.FIle path is ${grubfm_file}.
"condition = iso/loop_test.sh" means file manager will run "(memdisk)/boot/grub/rules/iso/loop_test.sh" first to check if the file meets the requirements, and generates a menu item if the requirements are met.
In [/boot/grub/rules/iso/loop_test.sh](https://github.com/a1ive/grub2-filemanager/blob/master/boot/grub/rules/iso/loop_test.sh)
```
loopback -d loop;
loopback loop "${grubfm_file}";
if [ -f (loop)/boot/grub/loopback.cfg ];
then
  set grubfm_test=1;
else
  set grubfm_test=0;
fi;
```
If the file meets the requirements, the variable "grubfm_test" should be set to 1(or other non-zero numbers), otherwise it should be set to 0 (or unset it).

**Comment by steve6375** [comment]
But there is no /boot/grub/rules/iso/ folder accessible to the end user?

I want to provide a system to the end user where he\she can simply add .iso files (for instance) to a second partition and boot them.

The end user has no linux knowledge or compiler skills. The end user just adds files to the drive and boots.

In addition, if the **end user** requires a special menu - e.g. run an ISO + persistence file, then the menu file is added into the Open menu automatically:

e.g.
Ptn2: \MyFiles\Ubuntux64.iso
Ptn2:\MyFiles\Ubuntux64_persistence.grubfm

The *.grubfm file is automatically added into the Open menu.
The .grubfm is a menuentry file which is added in using the _source_ command.
The end user can add different .grubfm files for different ISOs and different purposes.
e.g. persistence file added using partnew and use 'persistence' kernel parameter.

In the .grubfm file, the end user can use $ variables for  device, path, filename and extension of the target grubfm_file.

**Comment by a1ive** [comment]
> But there is no /boot/grub/rules/iso/ folder accessible to the end user?
> 
> I want to provide a system to the end user where he\she can simply add .iso files (for instance) to a second partition and boot them.

The root device of file manager can be changed.
e.g. `grubfm_set --root hd0,1` to load file type configurations (/boot/grub/types or rules) from hd0,1.
You don't have to use grubx64.efi with embeded memdisk.
I've provided two commands, `grubfm` and `grubfm_open`.You can use it to generate menu automatically.
However, grub2 can only read configuration from a single device path, otherwise it has to deal with possible file conflicts.

**Comment by a1ive** [comment]
> In addition, if the end user requires a special menu - e.g. run an ISO + persistence file, then the menu file is added into the Open menu automatically:
> 
> e.g.
> Ptn2: \MyFiles\Ubuntux64.iso
> Ptn2:\MyFiles\Ubuntux64_persistence.grubfm
> 
> The *.grubfm file is automatically added into the Open menu.
> The .grubfm is a menuentry file which is added in using the source command.
> The end user can add different .grubfm files for different ISOs and different purposes.
> e.g. persistence file added using partnew and use 'persistence' kernel parameter.
> 
> In the .grubfm file, the end user can use $ variables for device, path, filename and extension of the target grubfm_file.

I think file path (${grubfm_file}) is enough.
You can get device/name/extension from it using `regexp`.

**Comment by steve6375** [comment]
The end user does not understand regexp.
It would be better to provide simple $ variables.
$file_name (name of file with no extension) and $file_path (path of file with no device) and file_ext (extension of file) are missing.

**Comment by a1ive** [comment]
> The end user does not understand regexp.
> It would be better to provide simple $ variables.
> $file_name (name of file with no extension) and $file_path (path of file with no device) and file_ext (extension of file) are missing.

This may be right.
I prefer to use grub2 script to provide these variables.'End users' can use source command to get them.

**Comment by a1ive** [comment]
For 'deepin-15.11-amd64.iso', if 'deepin-15.11-amd64.grubfm' exists, a usr menu will be added to "open with" menu.
![深度截图_选择区域_20200109091828](https://user-images.githubusercontent.com/10670106/72029685-b2ea5500-32c1-11ea-8f7d-2d3ab4502bc0.png)
![深度截图_选择区域_20200109091811](https://user-images.githubusercontent.com/10670106/72029693-b8479f80-32c1-11ea-8497-a99362c95c77.png)

> It would be better to provide simple $ variables.
> $file_name (name of file with no extension) and $file_path (path of file with no device) and file_ext (extension of file) are missing.

See [func.sh](https://github.com/a1ive/grub2-filemanager/blob/master/boot/grub/func.sh).
![深度截图_选择区域_20200109091935](https://user-images.githubusercontent.com/10670106/72029761-e4632080-32c1-11ea-8998-c7e4874b2c1d.png)

**Comment by steve6375** [comment]
Thanks, I will test  today but with this method you can only have one .grubfm file per ISO.
It would be better if the user selected the .grubfm files.
One ISO can be run in many different ways, e.g. different persistence files can be used with the same ISO, different kernel parameters can be used with the same ISO. etc.

e.g.
Ubuntu x64 with persistence (general use).grubfm
Ubuntu x64 with persistence for Fred.grubfm
Ubuntu x64 with iodd kernel cheat code.grubfm
Ubuntu x64 (safe mode).grubfm
etc.

**Comment by a1ive** [comment]
> Thanks, I will test today but with this method you can only have one .grubfm file per ISO.
> It would be better if the user selected the .grubfm files.
> One ISO can be run in many different ways, e.g. different persistence files can be used with the same ISO, different kernel parameters can be used with the same ISO. etc.
> 
> e.g.
> Ubuntu x64 with persistence (general use).grubfm
> Ubuntu x64 with persistence for Fred.grubfm
> Ubuntu x64 with iodd kernel cheat code.grubfm
> Ubuntu x64 (safe mode).grubfm
> etc.

I think one .grubfm is better.
Users can add many menu entries to *.grubfm.
If there are many *.grubfm files, what should be the menu title?
I don't like long file names, e.g. "ubuntu-19.10-desktop-amd64_persist_general_use.grubfm".

**Comment by steve6375** [comment]
OK. I will test.
When a .grubfm file is run, how can the user add a menu entry to return back to the Open menu?

**Comment by a1ive** [comment]
grubfm_open "${grubfm_file}"

**Comment by steve6375** [comment]
Can we have pre-defined  $grubfm_dev too please?

regexp --set=1:dev '(hd[0-9]+),msdos[1-3]' "${grubfm_device}"

so we can we in partnew command.

**Comment by steve6375** [comment]
Success!

manjaro-xfce-18.0.1-stable-x86_64.grubfm
```

menuentry "Boot: Manjaro.x86_64 xfce " --class=Manjaro "$grubfm_name" {
regexp --set=1:dev '(hd[0-9]+),msdos[1-3]' "${grubfm_device}"
partnew --type=0x00 --file=${grubfm_file} (${dev}) 4
loopback loop ${grubfm_file} 
set root=(loop)
linux /boot/vmlinuz-x86_64 lang=en_US keytable=us tz=UTC driver=free nouveau.modeset=1 i915.modeset=1 radeon.modeset=1 misobasedir=manjaro misolabel=MJRO1801 systemd.show_status=1
initrd /boot/amd_ucode.img /boot/intel_ucode.img /boot/initramfs-x86_64.img
}

menuentry "Back" {
grubfm_open "${grubfm_file}"
}

```

**Comment by steve6375** [comment]
custom.sh does not seem to work if the  iso file name contains spaces ??

**Comment by a1ive** [comment]
I forgot to quote the path.

**Comment by steve6375** [comment]
Another request!

Manjaro 64-bit can only boot on 64-bit CPUs, but there is no variable set for the user for CPU bitness.
grub_cpu does not show bitness of CPU in Legacy mode - e.g. always  i386 in Legacy mode even with 64-bit CPU.

Might be useful to also add a variable for CPU bitness:
if cpuid -l; then set grubfm_cpu=64; else set grubfm_cpu=32; fi

so that use can make a menuentry using  if statement.
User can use grubfm_cpu, grub_cpu and grub_platform with menus.

if [ "$grub_cpu" == "64" ] ; then
menuentry .... for 64-bit
else
# return back to 'open' menu
grubfm_open "${grubfm_file}"
fi

**Comment by a1ive** [comment]
> Another request!
> 
> Manjaro 64-bit can only boot on 64-bit CPUs, but there is no variable set for the user for CPU bitness.
> grub_cpu does not show bitness of CPU in Legacy mode - e.g. always i386 in Legacy mode even with 64-bit CPU.
> 
> Might be useful to also add a variable for CPU bitness:
> if cpuid -l; then set grubfm_cpu=64; else set grubfm_cpu=32; fi
> 
> so that user can make a menuentry using if statement.
> User can use grubfm_cpu, grub_cpu and grub_platform with menus.
> 
> ```
> if [ "$grub_cpu" == "64" ] ; then
> menuentry .... for 64-bit
> else
> # return back to 'open' menu
> grubfm_open "${grubfm_file}"
> fi
> ```
> 
> https://rmprepusb.blogspot.com/2020/01/a1ives-grub2-file-manager-v12.html

Why not using `cpuid -l` directly?

**Comment by steve6375** [comment]
just because user would have to know the command and add it to every menu that he make.

For my E2B grub2 menu system, I define easy variables for user to use:
# DEFINE VARIABLES FOR MBR\EFI and 32/64-bit
set BIT64=false; set BIT32=false; set MBR=false; set EFI=false; set EFI64=false; set EFI32=false; set MBR32=false; set MBR64=false
if cpuid -l; then set BIT64=true; else set BIT32=true; fi
if [ "${grub_platform}" == "pc" ]; then set MBR=true; fi
if [ "${grub_platform}" == "efi" ]; then set EFI=true; fi
if [ "${grub_cpu}" == "x86_64" and $EFI = true ]; then set EFI64=true; fi
if [ "${grub_cpu}" == "i386" and $EFI = true ]; then set EFI32=true; fi
if [ $BIT64 = true and $MBR = true ]; then set MBR64=true; fi
if [ $BIT32 = true and $MBR = true ]; then set MBR32=true; fi
export MBR EFI MBR32 MBR64 EFI32 EFI64 BIT32 BIT64
#Examples
#if [ $BIT64 = true and $MBR = true ] ; then echo 64-bit MBR ; fi
#if [ $BIT64 = true and $EFI = true ] ; then echo 64-bit EFI ; fi
#if $BIT64 ; then echo 64-bit ; fi
#if $BIT32 ; then echo 32-bit ; fi

**Comment by steve6375** [comment]
Ubuntu with persistence menu:

https://rmprepusb.blogspot.com/2020/01/a1ive-grub2-file-manager-menu-for.html


```
# available variables are:
# grubfm_file  - (dev)+fullpath+name_ext
# grubfm_path  - e.g. /test/ubunto.iso
# grubfm_dir   - e.g. /test/
# grubfm_device - e.g. hd0,msdos1
# grubfm_disk    - e.g. hd0
# grubfm_name    - e.g. ubuntu.iso
# grubfm_filename - e.g. ubuntu
# grubfm_fileext   - e.g. iso
# grub_platform=efi or pc  (UEFI or Legacy BIOS)
# grub_cpu=i386 or x86_64 (i386=Legacy mode or 32-bit UEFI, x86_64=UEFI64)
# grub_uefi_version  (e.g. 2.4)
# grub_secureboot
# CPU  (=32 or 64)

if cpuid -l; then set CPU=64; else set CPU=32; fi

# --class=   defines the icon displayed next to the menuentry

# Only show menu if 64-bit CPU:
if [ "$CPU" == "64" ] ; then
menuentry "Ubuntu 64-bit with persistence" --unrestricted --class ubuntu {
	partnew --type=0x00 --file="(${grubfm_device})/perist/${grubfm_filename}" (${grubfm_disk}) 4
	loopback loop "${grubfm_file}" 
	set root=(loop)
  	if [ -e (loop)/casper/vmlinuz ]; then set vml=vmlinuz ; fi
	if [ -e (loop)/casper/vmlinuz.efi ]; then set vml=vmlinuz.efi ; fi
	if [ -e (loop)/casper/initrd ]; then set init=initrd ; fi
	if [ -e (loop)/casper/initrd.lz ]; then set init=initrd.lz ; fi
	linux (loop)/casper/$vml boot=casper persistent iso-scan/filename=$grubfm_path quiet splash
	initrd (loop)/casper/$init
	boot
}
else
# return back to 'open' menu
grubfm_open "${grubfm_file}"
fi

menuentry "Back" {
grubfm_open "${grubfm_file}"
}

```

**Comment by steve6375** [comment]
Suggest do not list  *.grubfm files? They have to be in the same folder as the ISO and just clog up the menu?

Also do not show  System Volume Information folder?
![image](https://user-images.githubusercontent.com/1469350/72100305-4b142880-331a-11ea-82ca-61b70301725f.png)

**Comment by steve6375** [comment]
How can we test if a partition has a partition type?
In grub4dos we have the parttype command.
It would be nice to test before we write to the partition table to prevent accidents.

**Comment by a1ive** [comment]
> Suggest do not list *.grubfm files? They have to be in the same folder as the ISO and just clog up the menu?

I don't think we should hide a 'normal' file.

**Comment by a1ive** [comment]
> How can we test if a partition has a partition type?
> In grub4dos we have the parttype command.
> It would be nice to test before we write to the partition table to prevent accidents.

use `test -d (hd0,4)` ?

**Comment by steve6375** [comment]
`if ! test -d (hd0,4) ; then partnew --type=0x00 --file="(${grubfm_device})/perist/${grubfm_filename}" (${grubfm_disk}) 4 ; fi
`
This works. Thanks!

**Comment by steve6375** [comment]
Could you also add the .grubfm functionality to all the other file types (e.g. .img, .wim, .ima, etc.).

The menu entry at the moment for ISO says 'ISO user menu' - this could be changed to 'User menu'
and be generic for all types.

For instance, may want to use wimboot to boot from own menu and inject own XML or startnet.cmd, etc. or may want to use partnew with two .img file. e.g. BSD memstick images should be bootable by extracting  1.img and using partnew (hd0,msdos2) 0xa5 and then booting BSD.img memstick file using map command.
