### ISSUE TITLE
'grubfm_open' menu does not show file name

### ISSUE THREAD

**Issue by steve6375** [a1ive/grub2-filemanager#75]
Is it possible to show the name of the file in this menu?

![image](https://user-images.githubusercontent.com/1469350/72203857-4316ce80-3469-11ea-9ead-3a99b41d08d6.png)

**Comment by a1ive** [comment]
where to show it?

**Comment by steve6375** [comment]
maybe separate line as heading - or just file name + extension on File Info line, e.g.

`File Info (xxxxxxxxx.iso)`

**Comment by a1ive** [comment]
It is better to show the full path in the upper left corner of the screen.
![深度截图_选择区域_20200113110615](https://user-images.githubusercontent.com/10670106/72231198-0bd52880-35f5-11ea-819b-1796a1f6500e.png)

**Comment by steve6375** [comment]
Thanks - but I think it would also be good to add just the filename after the File Info menu entry in this menu as well.
File Info (xxxxxxxxx.iso)

???

**Comment by a1ive** [comment]
> File Info (xxxxxxxxx.iso)

I prefer full path.

**Comment by steve6375** [comment]
Top of display already has full path so user can see full path (but it is not very easily seen).
So add filename is needed for File Info.
File Info (xxxxxxxxx.iso)
??

**Comment by a1ive** [comment]
It's difficult to implement it.

**Comment by steve6375** [comment]
OK. I will close this issue.
