### ISSUE TITLE
Enhancement: Boot Win ISOs with XML file

### ISSUE THREAD

**Issue by steve6375** [a1ive/grub2-filemanager#76]
Windows 7 ISOs typically contain all Editions of Windows but you can only install one Edition - e.g. a Win7 Pro ISO contains all editions but if you boot it normally, it will only install Pro.
Win 8.1 ISOs always prompt the user to enter a Product Key - annoyingly this _cannot be skipped by the user_. The use _must_ enter a 5x5 Product Key (even if just an install-only key).
Win10 allows you to skip entering a Product Key so no problem (but user may wish to specify an XML file).

All these issues could be avoided by allowing the user to select an XML file which contains a product key and then you can run Setup by pointing to the unattend XML file.

Could the script be modified to search for .xml files which are in the same folder as the ISO? If no .xml file exists then just run immediately. If one or more .xml files exist, ask user does he want to use an XML file and then allow user to pick one of them or not use any XML file.

**Comment by a1ive** [comment]
Could you please provide some XML files (for win8 or win10) for testing?

**Comment by steve6375** [comment]
[WINDOWS_8_XML.zip](https://github.com/a1ive/grub2-filemanager/files/4050593/WINDOWS_8_XML.zip)

Many examples in Easy2Boot (in \_ISO\WINDOWS\xxxxx folders but contain RunSychnronous section which is not used for this case) or make your own on WAFG site https://www.windowsafg.com/

**Comment by a1ive** [comment]
![深度截图_选择区域_20200113151726](https://user-images.githubusercontent.com/10670106/72238461-bc085880-3618-11ea-9743-4fe41f6a5e67.png)

**Comment by steve6375** [comment]
It works!
But there seems to be double \\  backslashes in the path?

![image](https://user-images.githubusercontent.com/1469350/72245169-d83fd180-35e7-11ea-8a76-e8253f1992df.png)

**Comment by a1ive** [comment]
> It works!
> But there seems to be double \ backslashes in the path?
> 
> ![image](https://user-images.githubusercontent.com/1469350/72245169-d83fd180-35e7-11ea-8a76-e8253f1992df.png)

Sometimes GRUB2 eats single backslashes in scripts. I think '\\' also work well.

**Comment by steve6375** [comment]
I can't quite remember , but wasnt there a  NTBOOT option before in the open menu?

**Comment by a1ive** [comment]
"NTBOOT" is for wim & vhd

**Comment by steve6375** [comment]
ah yes. OK. I will close this issue. Thanks! Nice job!
