### ISSUE TITLE
Tails 4.2 ISO not UEFI64 booting

### ISSUE THREAD

**Issue by steve6375** [a1ive/grub2-filemanager#77]
Tails 4.2 (test on _real system_ and use _Removable_ USB flash drive), but UEFI64 is not working.
Seems to hang\crash very early on loading EFI file or just return back to menu?
https://tails.boum.org/news/version_4.2/index.en.html
Boots Ok if extract files to a FAT32 USB drive or if make .imgPTN file for E2B.

**Comment by a1ive** [comment]
tails-amd64-4.2.iso is not UEFI-bootable.
It doesn't have an eltorito fat image.
![深度截图_选择区域_20200114173740](https://user-images.githubusercontent.com/10670106/72335654-4b396d00-36fa-11ea-9e75-9fb2a9deba15.png)
![深度截图_选择区域_20200114181606](https://user-images.githubusercontent.com/10670106/72335681-58565c00-36fa-11ea-96aa-97b7d8cc364c.png)
Its uefi eltorito image is iso9660.
Compare with kali.iso
![深度截图_选择区域_20200114181709](https://user-images.githubusercontent.com/10670106/72336132-1ed22080-36fb-11ea-8e31-c297d189a2d9.png)

**Comment by steve6375** [comment]
OK.
At least it boots from a config file. Must use real USB device on real system.
e.g.
[tails-amd64-4.2.grubfm.zip](https://github.com/a1ive/grub2-filemanager/files/4058632/tails-amd64-4.2.grubfm.zip)

**Comment by a1ive** [comment]
It seems that we still need to add a menu entry to use cheat codes to boot non-standard iso. :disappointed:

**Comment by steve6375** [comment]
Sorry - how do I use that menu?

**Comment by a1ive** [comment]
It's for old version of grubfm.I haven't added it.
