### ISSUE TITLE
Can't boot into Kali Linux live mode (UEFI, Loopback)

### ISSUE THREAD

**Issue by dareelkendu** [a1ive/grub2-filemanager#79]
I've got this error message when booting into Kali Linux live mode:

> [3.273402] [drm:intel_cpu_fifo_underrun_irq_handler [i915]] *ERROR* CPU pipe A FIFO underrun
> [3273569] [drm:intel_set_pch_fifo_underrun_reporting [i915]] *ERROR* uncleared pch fifo underrun on pch transcoder A
> 3273660 ] (drm:cpt_irq_hand ler 191511 ERROR PCH transcoder A FIFO underrun
> 
> BusyBox u1.30.1 (Debian 1:1.30.1-4) built-in shell (ash)
> Enter 'help' for a list of built-in commands
> 
> (initramfs)

Do you have any suggestions?

**Comment by a1ive** [comment]
Try 'fail-safe' mode?
run `cat /proc/cmdline` in busybox shell to see the cmdline.

**Comment by dareelkendu** [comment]
This is the cmdline output:

> (initramfs) cat proc/cmdline
> BOOT_IMAGE=/live/vmlinuz-5.3.0-kali2-amd64 boot=live components quiet splash username=root hostname=kali noeject

Excuse me, where is the 'Easy2Boot' method?
Thank you for quick reply

**Comment by a1ive** [comment]
![深度截图_选择区域_20200116101927](https://user-images.githubusercontent.com/10670106/72487671-b9407a00-3849-11ea-884f-824bb79c63ae.png)

**Comment by dareelkendu** [comment]
I have this option instead:

![image](https://user-images.githubusercontent.com/44135106/72491718-6ff22980-384d-11ea-9ebf-742eb8ae8876.png)

But I can't boot from that.

**Comment by a1ive** [comment]
kali iso image is on a gpt disk?
select "Boot Debian from", then choose "Root login", then select "Debian Live"
![深度截图_选择区域_20200116135407](https://user-images.githubusercontent.com/10670106/72497657-0895a300-3868-11ea-8572-a896c42b1b34.png)
![深度截图_选择区域_20200116135435](https://user-images.githubusercontent.com/10670106/72497659-0c292a00-3868-11ea-9195-5e0ce0223573.png)
The iso must be in a fat32 partition, ntfs won't work.

**Comment by dareelkendu** [comment]
It works! Thanks for your help!
