### ISSUE TITLE
Issues MBR booting some wim files

### ISSUE THREAD

**Issue by steve6375** [a1ive/grub2-filemanager#83]
Download SergeiStrelec WinPE ISO.
https://sergeistrelec.ru/winpe-10-8-sergei-strelec-english/180-winpe-10-8-sergei-strelec-x86-x64-native-x86-20191002-english-version.html
Extract \SSTR\strelec10x64Eng.wim
This will UEFI64 boot, but when MBR-booting using NTBOOT I get a bootmgr corrupt message.
However, it works when booting to an Easy2Boot drive which also uses NTBOOT.
grubfm with wimboot also works.
The other .wim files in \SSTR also fail.
![image](https://user-images.githubusercontent.com/1469350/72688453-56780880-3aff-11ea-8f52-a309ce00ffdb.png)

**Comment by a1ive** [comment]
I can't reproduce it here (both in vmware vm and my laptop).

**Comment by a1ive** [comment]
btw I updated the Simplified Chinese translation file for e2b.
[STRINGS.txt](https://github.com/a1ive/grub2-filemanager/files/4084090/STRINGS.txt)

**Comment by steve6375** [comment]
I am testing by adding a \_ISO\MAINMENU\grubfm.mnu file to the Easy2Boot USB drive.
I then boot to Easy2Boot and then select the menu item from the main menu to load grubfm.iso

```
iftitle Grub2 File Manager (a1ive) \nBoot a file using grub2
find --set-root /grubfm.iso
map --mem /grubfm.iso (0xff)
map --hook
chainloader (0xff)
boot
```

Can you try this please?

**Comment by steve6375** [comment]
I think I have fixed the issue by stopping animation and unmapping!

```
errorcheck on
debug off
splashimage --animated=0
map --unmap=0:0xff > nul
map --unhook
find --set-root /grubfm.iso
map --mem /grubfm.iso (0xff)
map --hook
chainloader (0xff)
boot
```
The animation had set up a timer interrupt!

**Comment by steve6375** [comment]
The issue seems to be caused because E2B has mapped fd3 to a floppy image (to use as a source of files for the animation). If I use:
```
map --unmap=0:0x03 > nul
map --unhook
find --set-root /grubfm.iso
map --mem /grubfm.iso (0xff)
map --hook
chainloader (0xff)
boot
```

It works OK. So perhaps your grub4dos code could unmap and rehook all floppies before you use them?

**Comment by a1ive** [comment]
I don't have windows, so I installed e2b in winpe.
I put grubfm.iso in _ISO\UTILITIES, but still can't reproduce.
![深度录屏_vmware_20200120190021](https://user-images.githubusercontent.com/10670106/72721723-afa37300-3bb7-11ea-804a-3bce6dbc542f.gif)

**Comment by steve6375** [comment]
Yes- that works because you are booting from the ISO and the E2B code unhooks fd3.
You only see the problem if you use a .mnu file because that did not unhook fd3.

**Comment by a1ive** [comment]
![深度录屏_选择区域_20200120191355](https://user-images.githubusercontent.com/10670106/72722419-3d339280-3bb9-11ea-97f9-8c56971b524a.gif)

**Comment by steve6375** [comment]
Strange. That seems the same that I am doing except I am using VBox.
But I have reproduced it on a real system also and so has another user.
http://reboot.pro/topic/22232-a1ives-grub2-and-file-manager-has-great-uefi-support/?p=213799

**Comment by steve6375** [comment]
![windemo](https://user-images.githubusercontent.com/1469350/72723856-a72c4780-3b79-11ea-994f-6bea80d2f432.gif)

**Comment by a1ive** [comment]
> Strange. That seems the same that I am doing except I am using VBox.

I reproduced it on my laptop.

**Comment by a1ive** [comment]
> So perhaps your grub4dos code could unmap and rehook all floppies before you use them

I'm not familiar with BIOS related things, how to unmap all floppies in grub4dos?
BTW, if we don't enter grub4dos, how can we unmap floppies?

**Comment by steve6375** [comment]
I used this in NTBOOT and replaced the one in grubfm.iso with it:

```
:NTBOOT_START
::设置默认WINDOWS路径


map --unmap=0:03 > nul
map --unhook
```

and it seems to work.

Not sure is we should unmap all  drives 0:0xff  ??

**Comment by a1ive** [comment]
maybe we should edit here
https://github.com/a1ive/grub2-filemanager/blob/e7c070eedf76119a71270f13462956e2f1a1ab67/arch/legacy/ntboot/NTBOOT#L191
but I still don't know why we have to unmap it, is it a bug in grub4dos?

**Comment by steve6375** [comment]
It seems BOOTMGR etc is on fd0

```
:BOOT
if exist BOOT && %BOOT%
map --mem (rd)+1 %BOOTDEV%
map --unmap=0,1,2,3,0xfb,0xfc,0xfe,0xff,0xcd
map --rehook
call :CHECK_FILE %NTLDR%
chainloader %NTLDR%
root %BOOTDEV%
boot
exit
```

![image](https://user-images.githubusercontent.com/1469350/72726613-a6e37a80-3b80-11ea-93e9-a57f2e20a866.png)


But this works OK
```
:BOOT
if exist BOOT && %BOOT%
map --mem (rd)+1 %BOOTDEV%
map --unmap=2,3,0xfb,0xfc,0xfe,0xff,0xcd
map --rehook
call :CHECK_FILE %NTLDR%
chainloader %NTLDR%
root %BOOTDEV%
boot
exit

```

**Comment by steve6375** [comment]
I put in a 
`map --status ;; pause`
command under :BOOT label
![image](https://user-images.githubusercontent.com/1469350/72727026-cc24b880-3b81-11ea-8e26-04c399aa90a5.png)

This seems to work OK:
`map --unmap=1:0xff
`

**Comment by steve6375** [comment]
Maybe you could ask Chenal about this on the grub4dos Chinese forum?

P.S.  your NTBOOT does not support wim files with spaces in the filename.
The NTBOOT in Easy2Boot (\_ISO\E2B\GRUB\NTBOOT) has some changes to fix this (but you can't use my NTBOOT because it won't directly replace your NTBOOT).

**Comment by a1ive** [comment]
> P.S. your NTBOOT does not support wim files with spaces in the filename.
> The NTBOOT in Easy2Boot (_ISO\E2B\GRUB\NTBOOT) has some changes to fix this (but you can't use my NTBOOT because it won't directly replace your NTBOOT).

Even if ntboot is modified so that it supports spaces, it will not boot properly.
We have to modify linux kernel (grub.exe) cmdline to make it support spaces.

**Comment by steve6375** [comment]
some characters are illegal in paths\filenames such as colon (:) 
You could substitute space for colon in grub.exe line
and then translate back in grub4dos?

**Comment by a1ive** [comment]
> Maybe you could ask Chenal about this on the grub4dos Chinese forum?

He said he had forgotten why he did that. :rofl:

**Comment by steve6375** [comment]
OK - but can he think of any reason why using unmap=1:0xff  is a bad solution?
i.e. is it OK for us to use unmap=1:0xff ?

**Comment by steve6375** [comment]
Thanks for STRINGS.txt 👍
