### ISSUE TITLE
.grubfm not loaded with .wim

### ISSUE THREAD

**Issue by steve6375** [a1ive/grub2-filemanager#85]
\SSTR\strelec10x64Eng.wim
\SSTR\strelec10x64Eng.grubfm

![image](https://user-images.githubusercontent.com/1469350/72797745-993dfb80-3c39-11ea-89c5-7abea76deb54.png)
![image](https://user-images.githubusercontent.com/1469350/72797803-b96dba80-3c39-11ea-8b3c-d1d8807f1e02.png)

**Comment by steve6375** [comment]
menuentry "Strelec 64-bit" --class=nt6 {
ls
read
	source (memdisk)/boot/grub/rules/iso/win.sh
echo 	win_isoboot  "(${grubfm_device})${grubfm_dir}${grubfm_filename}.wim"
read
	win_isoboot  "(${grubfm_device})${grubfm_dir}${grubfm_filename}.wim"
}
I tried this.

**Comment by a1ive** [comment]
can't reproduce.
![深度录屏_vmware_20200121184804](https://user-images.githubusercontent.com/10670106/72798751-ae894900-3c7e-11ea-9ad4-49a70263fe58.gif)

**Comment by steve6375** [comment]
I am running grubfm.iso from E2B menu and get this
![image](https://user-images.githubusercontent.com/1469350/72799082-53366700-3c3c-11ea-94a8-24633c36578e.png)

**Comment by steve6375** [comment]
MBR boot.

**Comment by steve6375** [comment]
Is it OK to use win_isoboot for wim file?

**Comment by a1ive** [comment]
In wimboot.sh,
```
initrd16 newc:bootmgr:(wimboot)/bootmgr \
           newc:bootmgr.exe:(wimboot)/bootmgr.exe \
           newc:bcd:(wimboot)/bcd \
           newc:boot.sdi:(wimboot)/boot.sdi \
           newc:boot.wim:"${grubfm_file}";
```
and in win.sh,
```
initrd16 newc:bootmgr:(loop)/bootmgr \
              newc:bcd:(wimboot)/bcd \
              newc:boot.sdi:(loop)/boot/boot.sdi \
              ...
              newc:boot.wim:"${1}";
```
so we should inject bootmgr.exe to strelec's wim?
but win10 installation isos don't need it.

**Comment by steve6375** [comment]
On further thought, I don't think it is valid to use win.sh for winpe wims.
I will close this as we should use wimboot.sh.
