### ISSUE TITLE
query: cannot use chainloader to boot bootx64.efi after partnew

### ISSUE THREAD

**Issue by steve6375** [a1ive/grub2-filemanager#86]
```
menuentry "Install Windows10x642018_04-02.imgPTN23 English Partnew 1" --class=nt6 {
   set "grubfm_file=(${grubfm_device})/_ISO/WINDOWS/WIN10/Windows10x642018_04-02.imgPTN23"
  partnew --type=0x0C --file="${grubfm_file}" (${grubfm_disk}) 1
set root=(${grubfm_disk},msdos1)
set grubfm_file="(hd0,msdos1)/EFI/BOOT/BOOTX64.efi"
set gfxpayload=keep
chainloader -b -t "${grubfm_file}"
}
```

Ptn1: NTFS (but replaced by partnew command with FAT32)
Ptn2: FAT32  grub2 files

1. UEFI64 boot to File Manager
2. Run above menu
3. Get error 0x8000000000000002
I have tried various chainloader commands but get NULL file or above error.

If I UEFI-boot again (after partnew command) and use File Manager to select the \efi\boot\bootx64.efi file (which uses chainloader -b -t grubfm_file) it boots fine!!!

Any idea why I need to reboot ?

**Comment by steve6375** [comment]
![image](https://user-images.githubusercontent.com/1469350/73292551-2664ef80-41fa-11ea-88a7-bea8be6214d7.png)
This is error (i renamed the EFI file from bootx64 so the system always booted to 2nd partition with File Manager).

**Comment by a1ive** [comment]
Because we need a command equivalent to 'map --rehook'.
partition name in grub2 won't change if you edit the partition table.

**Comment by steve6375** [comment]
OK, so the best I can do is partnew and then

chainloader (hd0,msdos2)/grubfmx64.efi

to reload grub2 and then boot to the Windows bootx64.efi?

**Comment by a1ive** [comment]
I will implement 'map --rehook' if I have time.

**Comment by steve6375** [comment]
Great! Together with dd sector backup of LBA0 that means I can have any Secure Boot UEFI Windows payload as partition 1 without needing to reboot.

The UEFI64 Secure Boot patch does not work for Windows wimboot or NTBOOT - it has to boot from flat file bootx64.efi otherwise I get 0xc000000f  error.

**Comment by a1ive** [comment]
> The UEFI64 Secure Boot patch does not work for Windows wimboot or NTBOOT - it has to boot from flat file bootx64.efi otherwise I get 0xc000000f error.

Use win7 bootmgfw.efi.(Some PC won't work after MS ended support for WIN7)

**Comment by steve6375** [comment]
map --update not working :-(
![image](https://user-images.githubusercontent.com/1469350/73442977-bd8e8c00-434d-11ea-91ca-184e41fbcec5.png)

**Comment by steve6375** [comment]
chainloader -a -b  hangs
![image](https://user-images.githubusercontent.com/1469350/73443123-047c8180-434e-11ea-89b9-504513225195.png)

**Comment by a1ive** [comment]
> map --update not working :-(
> ![image](https://user-images.githubusercontent.com/1469350/73442977-bd8e8c00-434d-11ea-91ca-184e41fbcec5.png)

It seems that we should install Simple FileSystem Protocol to the partition manually.
The UEFI firmware won't recognize it automatically. :thinking:

**Comment by a1ive** [comment]
> Care must be taken by UEFI utilities that manipulate partitions. The utility must gain exclusive access to
> the physical disk to cause the partition driver to be stopped before it changes the partition information. If
> the exclusive request is not granted, then the utility must reset the system after changing the partition
> information.

See https://uefi.org/sites/default/files/resources/UEFI_Spec_2_8_final.pdf (13.18)

**Comment by a1ive** [comment]
After `partnew` and `map --update`, what will happen if we map `(hd0)` again?
```
partnew --type=0x0C --file (hd0,1)/xxx.img (hd0) 1
map --update
map --type=HD (hd0)
```

**Comment by steve6375** [comment]
```
partnew --type=0x0C --file (hd0,1)/xxx.img (hd0) 1
map --update
```
This is OK in non-secure UEFI64, but doesn't work in Secure Boot mode.

Using chainloader (hd0,msdos1)/efi/boot/bootx64.efi returns a
FILE: null
error in Secure Boot mode.

If I add 
`map --type=HD (hd0)`
it seems to make things worse and I get a 0xc000000f error even in non-secure UEFI boot mode.

**Comment by a1ive** [comment]
> The UEFI64 Secure Boot patch does not work for Windows wimboot or NTBOOT - it has to boot from flat file bootx64.efi otherwise I get 0xc000000f error.

Now you can secure-booting wimboot/NTBOOT without 0xc000000f error.

**Comment by steve6375** [comment]
Install Windows from ISO now works in Secure Boot. Great!
