### ISSUE TITLE
partnew prompt Y/N does not work on QWERTZ keyboard

### ISSUE THREAD

**Issue by steve6375** [a1ive/grub2-filemanager#87]
Is it possible to change the question to use a different answer key (e.g. 1 = Yes) or maybe a number key so a German user can use the English version? QWERTZ and AZERTY keyboards need to be considered. I know I can compile for a different language but it is awkward to supply multiple versions in different languages. Also one system may have a US keyboard but the next system may have a QWERTZ or AZERTY keyboard, etc.

Are you working on a multi-language version?

P.S.
It would be nice for agFM to pick up the settings for language and keyboard from some sort of user config file (\grubfm_config.sh ?). The user could set the required keyboard, timezone, language, theme folder, text mode, text colours, splashimage, etc. and could maybe also allow us to add our own extensions and rules without needing to recompile?

For instance, I would like a range of file extensions *.imgPTN* to be recognised and to automatically run my own .sh script when one is selected. i.e. \xxx\yyyy.imgPTN and \xxx\yyy.imgPTN23 and \xxx\yyy.imgPTN23auto ,etc. will all run the same .sh file. Is this possible?

**Comment by a1ive** [comment]
> Is it possible to change the question to use a different answer key (e.g. 1 = Yes) or maybe a number key so a German user can use the English version? QWERTZ and AZERTY keyboards need to be considered. 

I have never seen other keyboard mappings (e.g. QWERTZ).
Does it have the same scan code as a QWERTY keyboard ?(e.g. ENTER -- 0x0d, 'y' -- 0x79)
I think using ENTER is better.

**Comment by a1ive** [comment]
> It would be nice for agFM to pick up the settings for language and keyboard from some sort of user config file (\grubfm_config.sh ?). The user could set the required keyboard, timezone, language, theme folder, text mode, text colours, splashimage, etc. and could maybe also allow us to add our own extensions and rules without needing to recompile?

maybe in future?
I prefer to load/save user configurations in grub envblk files.
However, user-defined themes are not considered.

**Comment by steve6375** [comment]
On a German QWERTZ keyboard you need to press z to get the key code that you test for.
i.e. the same scan code is generated by the same key - it is just that the keys are marked differently.
I would prefer _not_ to use ENTER because it may accidentally cause a partition to be deleted.
The question is only asked if a partition 4 exists - therefore it is important that the user has to think carefully before allowing the write to occur.

**Comment by steve6375** [comment]
maybe an F key? F10?
