### ISSUE TITLE
Fx menus have no 'Back' menu entry and ESC does not work.

### ISSUE THREAD

**Issue by steve6375** [a1ive/grub2-filemanager#88]
I know the user can press F2 from these menus, but I always seem to be looking for a 'Back' menu entry or I try pressing ESC before I realise I have to press F2. e.g.  if I go to the F6 menu.
It is only a small issue.

**Comment by a1ive** [comment]
ESC is disabled by default.
set grub_disable_esc to 0 to enable ESC.(see grub2 Chinese manual https://a1ive.github.io/grub2_zh.html)
In grubfm, ESC won't work because there are no real menu files(.cfg).

**Comment by steve6375** [comment]
So no 'Back' menu entry in F6 menu ???
![image](https://user-images.githubusercontent.com/1469350/73607863-a51fab00-45b3-11ea-83cd-42727ef40449.png)

**Comment by a1ive** [comment]
yes.
