### ISSUE TITLE
How to add user-defined rules and types?

### ISSUE THREAD

**Issue by steve6375** [a1ive/grub2-filemanager#89]
I would like to add my own rules and types files (e.g. for example to add .imgPTN and  .imgPTN23 as a file types).
I know I can add them in to the sources before compiling, but this is very time consuming to compile - copy - test, and then repeat many times.
It would be easier if there was a user \grubfm-user\rules and \grubfm-user\types folder which would also be searched and used. The folders could be added by the user to the FAT32 source partition if required. Is this possible please?

**Comment by steve6375** [comment]
How do I use this please?

**Comment by a1ive** [comment]
![深度截图_选择区域_20200210155926](https://user-images.githubusercontent.com/10670106/74131069-85752c00-4c1e-11ea-94b9-909e93f6d505.png)
example: 
[boot.zip](https://github.com/a1ive/grub2-filemanager/files/4179581/boot.zip)
just unzip and copy it to any partition.

**Comment by steve6375** [comment]
Thanks,  I will test.
Does a user rules\types override the default  rules\types - e.g. if I had a grubfm\rules\iso file?

**Comment by a1ive** [comment]
yes.

**Comment by steve6375** [comment]
Working well so far. Brilliant! Easy2Boot users seem to really like agFM! Thank you so much.
Is there an easy way to define a user icon for the menu entry - e.g. for a .imgPTN file? If not, don't worry. It would just be nice but I suspect it is too difficult because it is part of the theme?

**Comment by a1ive** [comment]
gfxmenu themes don't support loading icon from other folders.
