### ISSUE TITLE
Enhancement: Display volume names, etc. in F3 boot menu

### ISSUE THREAD

**Issue by steve6375** [a1ive/grub2-filemanager#90]
![image](https://user-images.githubusercontent.com/1469350/73748794-16956000-4752-11ea-940b-63632532beb4.png)

It would be useful to display the volume name and also the disk size and partition size and partition type (NTFS, FAT32, exFAT, etc.).

**Comment by a1ive** [comment]
![13102436](https://user-images.githubusercontent.com/10670106/74425373-8c09da80-4e8e-11ea-8f7e-6d160e58c9e6.png)

**Comment by steve6375** [comment]
Volume Name would be really helpful ??

**Comment by a1ive** [comment]
text is too long, don't fit in the menu.

**Comment by steve6375** [comment]
![image](https://user-images.githubusercontent.com/1469350/74426352-1cbfc680-4e4d-11ea-9578-5b8c13a10255.png)

**Comment by steve6375** [comment]
Thanks!
