### ISSUE TITLE
Enhancement: only list files with specific extensions

### ISSUE THREAD

**Issue by steve6375** [a1ive/grub2-filemanager#92]
Most people will use agFM to boot from bootable files or partitions. When using the File Manager there is often a lot of other files in folders and you have to scroll down a lot to find the one you want.
Would it be possible to have a switch (e.g. F7) which toggles between showing all files and just showing bootable files (files with 'rules' extensions??) ?
Ideally I would like the default to be 'Show all files=disabled', or a way of configuring the default setting with an external file.

**Comment by a1ive** [comment]
run `grubfm_set --hide 1` to enable this feature.
example for boot/grubfm/types/cfg
(display)
```
[type]
icon = cfg
boot = cfg/grub2.sh
display = 1
 ...
```
(hide)
```
[type]
icon = cfg
boot = cfg/grub2.sh
 ...
```
if config has `display = ` key, then will display, otherwise it will hide.

**Comment by steve6375** [comment]
great work! Many thanks.
