### ISSUE TITLE
Enhancement: Files with long filenames don't fit in the menu

### ISSUE THREAD

**Issue by steve6375** [a1ive/grub2-filemanager#93]
Also display the currently selected file name at the top of the display?

![image](https://user-images.githubusercontent.com/1469350/74138552-b8e99380-4be9-11ea-9f88-a4c70767d3b9.png)

**Comment by a1ive** [comment]
Use ctrl+l / ctrl+r to scroll text.
![深度录屏_选择区域_20200210174813](https://user-images.githubusercontent.com/10670106/74139100-bc067300-4c2d-11ea-975c-7890d48b34d3.gif)
https://github.com/a1ive/grub/commit/49e6b430bcf26e80f663ab63272499900325a5fa

**Comment by steve6375** [comment]
Thanks
Would be easier if it could be displayed at top of screen too?
Also add ctrl+r  ctrl+l  tip to F1 screen?

**Comment by a1ive** [comment]
> Would be easier if it could be displayed at top of screen too?

It's too difficult.

**Comment by a1ive** [comment]
> Would be easier if it could be displayed at top of screen too?

It's too difficult.

**Comment by steve6375** [comment]
OK. Thanks.
