### ISSUE TITLE
When in XML menu there is no way to go back

### ISSUE THREAD

**Issue by steve6375** [a1ive/grub2-filemanager#94]
F2 does not work.
No 'Back' menu entry.

**Comment by a1ive** [comment]
But do we really need a 'back' menu entry?

**Comment by steve6375** [comment]
Well, if anyone is exploring the agFM system and gets into the XML menu there is no way out except to reboot.
Since servers can take many minutes to reboot, it is kind of annoying to not have F2 or a Back entry present...
