### ISSUE TITLE
stat -c is crashing on large files

### ISSUE THREAD

**Issue by steve6375** [a1ive/grub2-filemanager#95]
When using in large files (3GB) get graphics corruption at top of screen.
File access takes 20 seconds or more and then stops.
System hang.
NTFS partition

![image](https://user-images.githubusercontent.com/1469350/74143998-c9067080-4bf3-11ea-8367-fe28033cf5a2.png)

Blocklist command takes a long time, but works OK.
![image](https://user-images.githubusercontent.com/1469350/74144155-200c4580-4bf4-11ea-8f5d-4471f9486e1e.png)

**Comment by steve6375** [comment]
Maybe need unsigned long long  in several places?

**Comment by steve6375** [comment]
Is there a way for` stat -c `to not read all sectors as it takes a really long time on large files?
Grub4dos blocklist command is v quick.
Does the partnew command check for a contiguous file (as the file needs to be contiguous).

**Comment by a1ive** [comment]
> Maybe need unsigned long long in several places?

doesn't work :disappointed: 

> Does the partnew command check for a contiguous file (as the file needs to be contiguous)?
no.

**Comment by a1ive** [comment]
https://github.com/chenall/grub4dos/blob/8bb58453e08f997241db6b876736f206f180f528/stage2/builtins.c#L411
It seems that grub4dos also reads the whole file.

**Comment by steve6375** [comment]
![image](https://user-images.githubusercontent.com/1469350/74328631-2f22fd00-4d86-11ea-82bc-920f4c37087b.png)
The blocklist command on an NTFS filesystem returns instantly with these results on grub4dos.
So I don't think it can be reading all bytes of the file???

**Comment by steve6375** [comment]
Same files under grub2 take 10-20 seconds each...

![image](https://user-images.githubusercontent.com/1469350/74328895-a5276400-4d86-11ea-93d6-321b325bd3b2.png)

**Comment by a1ive** [comment]
grub4dos
![深度截图_选择区域_20200212190835](https://user-images.githubusercontent.com/10670106/74329883-9adb8900-4dcb-11ea-99f8-ad1ffcd489a4.png)
grub2
![深度截图_选择区域_20200212191102](https://user-images.githubusercontent.com/10670106/74329902-a464f100-4dcb-11ea-9655-29c5304b5ea8.png)
For file '/test/wepe.wim' (file 2 in picture), grub4dos says `798440+388584`, while grub2 says `798440+388583,1187023[0-227]`.
The file is contiguous, but according to grub2, it has 2 fragments?

**Comment by steve6375** [comment]
The file is contiguous. I think it is just indicating that the last cluster is only using bytes 0-256.
129285216 + 1367187 = 130652403.

**Comment by a1ive** [comment]
http://bbs.wuyou.net/forum.php?mod=redirect&goto=findpost&ptid=418876&pid=3972831&fromuid=505580

**Comment by a1ive** [comment]
yaya:
> 以前grub4dos也慢。是chenall做了改进。具体做法是跳过真实读磁盘。

**Comment by a1ive** [comment]
![深度截图_选择区域_20200213120256](https://user-images.githubusercontent.com/10670106/74400495-091a5d00-4e59-11ea-9434-b0672981bdaf.png)
Now it won't crash, but still slow.

**Comment by a1ive** [comment]
[speedup block_read_func](https://github.com/chenall/grub4dos/commit/756d924cb61f861773ab793181f777ab4495ae8e)
[Bug fixed in block_read_func](https://github.com/chenall/grub4dos/commit/bcc4b7b932f28129f0578c724f8a1aac35e71b13)

**Comment by steve6375** [comment]
does not crash now, but still slow.
The partnew command really should check that the file is contiguous (because a partition must be contiguous) so a fast way to check that a file is contiguous is really needed...

**Comment by a1ive** [comment]
issue moved to here https://github.com/a1ive/grub/issues/33

**Comment by a1ive** [comment]
@steve6375 does grub4dos support map non-contiguous blocklist files, e.g. 
'map (hd0)1234+567,8901+2345'?
