### ISSUE TITLE
Query: Possible to make a file run immediately using a user extension

### ISSUE THREAD

**Issue by steve6375** [a1ive/grub2-filemanager#96]
If I make a .cfg file, the user has to select the .cfg file and then select 'grub2 menu' in order to run it.

I can add a user-defined  .cfg  type and rule (or make up a new extension), but how can I get the agFM to immediately run that file without a second menu having to be selected by the user?

i.e. I don't want this second menu...

![image](https://user-images.githubusercontent.com/1469350/74150514-f823de80-4c01-11ea-8acb-38c25679c0af.png)

**Comment by a1ive** [comment]
28a986c7f8e0383ec1b95de82e7c9bc6ffba8563
add `grubfm_set --boot 1` to /boot/grub/config to enable `boot=` feature.
example: 
[boot.zip](https://github.com/a1ive/grub2-filemanager/files/4197884/boot.zip)

**Comment by steve6375** [comment]
Working well! Thanks.
