### ISSUE TITLE
to_g4d_path does not allow for spaces

### ISSUE THREAD

**Issue by steve6375** [a1ive/grub2-filemanager#97]
to_g4d_path converts the device from hd0,msdos1 to hd0,0 but it does not convert spaces in the path

PC i386 booting to "Ubuntu 64.iso" and choosing Easy2Boot fails unless space is removed.

e2b.sh

In grub4dos, spaces are escaped with a \\, e.g.

> Ubuntu\ 64.iso

**Comment by a1ive** [comment]
I don't know how to modify ntboot to support file name with spaces (not good at grub4dos scripts), could you please help me?

**Comment by steve6375** [comment]
[NTBOOT.zip](https://github.com/a1ive/grub2-filemanager/files/4209584/NTBOOT.zip)
The version you have is older than mine and has less features.
I have tried to make the changes but I have not tested it!

**Comment by a1ive** [comment]
![深度截图_选择区域_20200216175452](https://user-images.githubusercontent.com/10670106/74602606-717d6e80-50e5-11ea-9585-39046c74a8fc.png)
It doesn't work.

**Comment by steve6375** [comment]
I think it is a problem with passing filename to ntboot.sh via grub.exe
NTBOOT is printing
'Checking file (hd0,1)/test/asd\ ...'
It should print
'Checking file (hd0,1)/test/asd\ fgh\ jkl.wim ...'
Entering file path manually may not work if spaces in path.

```
    set g4d_cmd="find --set-root --ignore-floppies /fm.loop;/NTBOOT NT6=${g4d_path};";
    linux ${prefix}/grub.exe --config-file=${g4d_cmd};
```

grub.exe is probably parsing the line and not escaping \(space).
    set g4d_cmd="find --set-root --ignore-floppies /fm.loop;/NTBOOT NT6=${g4d_path};";

Not sure how to solve???

**Comment by steve6375** [comment]
maybe add ' ??
set g4d_cmd='"find --set-root --ignore-floppies /fm.loop;/NTBOOT NT6=${g4d_path};"';

**Comment by a1ive** [comment]
> grub.exe is probably parsing the line and not escaping (space).

I don't think so.`map` works fine.
![深度录屏_选择区域_20200216193151](https://user-images.githubusercontent.com/10670106/74603876-29654880-50f3-11ea-97fd-5d852f615c41.gif)

**Comment by a1ive** [comment]
> maybe add ' ??
> set g4d_cmd='"find --set-root --ignore-floppies /fm.loop;/NTBOOT NT6=${g4d_path};"';

![深度截图_选择区域_20200216193544](https://user-images.githubusercontent.com/10670106/74603907-8a8d1c00-50f3-11ea-8f11-4728ad9686ce.png)

**Comment by a1ive** [comment]
https://github.com/a1ive/grub2-filemanager/blob/0e2baf5ebea20a8855dd982e4fb32472baad1f39/boot/grubfm/rules/iso/map.sh#L11
https://github.com/a1ive/grub2-filemanager/blob/0e2baf5ebea20a8855dd982e4fb32472baad1f39/boot/grubfm/rules/wim/ntboot.sh#L15

**Comment by steve6375** [comment]
![image](https://user-images.githubusercontent.com/1469350/74604855-e20e9600-50b9-11ea-8034-1dcd1a1295a7.png)

This works (even with original NTBOOT)

**Comment by steve6375** [comment]
![image](https://user-images.githubusercontent.com/1469350/74604949-07e86a80-50bb-11ea-94c9-f69f3c3f0ded.png)
Works with or without = sign as grub4dos treats space and = as parameter separators.

**Comment by a1ive** [comment]
> set "g4d_path=(hd0,0)/....wim"

this looks strange.Is it correct?

**Comment by steve6375** [comment]
yes
(hd0,0) is equivalent to (hd0,msdos1) in grub2

it is just a test .cfg file

ntboot.sh would be:

```
source ${prefix}/func.sh;
if [ "$grub_platform" = "efi" ];
then
  set lang=en_US;
  loopback wimboot ${prefix}/wimboot.gz;
  ntboot --efi=(wimboot)/bootmgfw.efi \
         --sdi=(wimboot)/boot.sdi \
         "${grubfm_file}";
elif [ "$grub_platform" = "pc" ];
then
  to_g4d_path "${grubfm_file}";
  if [ -n "${g4d_path}" ];
  then
#    set g4d_cmd="find --set-root --ignore-floppies /fm.loop;/NTBOOT NT6=${g4d_path};";
	set g4d_cmd="find --set-root --ignore-floppies /fm.loop;set \"g=${g4d_path}\";/NTBOOT NT6=%g%;";
    linux ${prefix}/grub.exe --config-file=${g4d_cmd};
    boot;
  fi;
fi;

```

**Comment by steve6375** [comment]
hmmm. not sure it is working now...

**Comment by a1ive** [comment]
I don't have computer right now, so I haven't test it.

**Comment by steve6375** [comment]
I think it may also need modified NTBOOT as I get 0xc000000f error when using your NTBOOT.

**Comment by steve6375** [comment]
It seems to be the linux command is adding an extra \

	set g4d_cmd="find --set-root --ignore-floppies /fm.loop ; pause xxx ${g4d_path} ; (hd0,1)/NTBOOT NT6=${g4d_path}"

![image](https://user-images.githubusercontent.com/1469350/74606464-6831d900-50c8-11ea-807e-70c6a7a76a72.png)

**Comment by steve6375** [comment]
`	set g4d_cmd="find --set-root --ignore-floppies /fm.loop ; echo !BAT > (md)0x300+1; echo -e set h=${g4d_path} >> (md)0x300+1;call (md)0x300+1;/NTBOOT NT6=%h%"
`
This seems to work - it needs the NTBOOT that I sent you though or you will get 0xc000000f error.
it works by converting the \\ characters that seems to be inserted by the grub2 linux command to just a single \.

**Comment by steve6375** [comment]
MAP works because it contains
`echo -e %* | set img=`

`the  echo -e     causes \\ to become \ and so it works.`

**Comment by steve6375** [comment]
Seems OK now. Thanks!
