### ISSUE TITLE
Set a file as the default selection plus timeout

### ISSUE THREAD

**Issue by steve6375** [a1ive/grub2-filemanager#98]
A user from reboot.pro has asked if it is possible to select one of the files (or a folder) as the 'default' one and also a timeout value.

http://reboot.pro/topic/22232-a1ives-grub2-and-file-manager-has-great-uefi-support/page-3#entry213906

i.e.
1. Boot to agFM
2. Read a default file which has file or folder + timeout value
(maybe indicates default  at top of screen?)
3. After timeout it selects the file\folder in grubfm else stays at first partition list screen

Use an Fx key to set the default file\folder + timeout value. ??

I am not sure if this really fits in with the idea of a File Manager but it might be useful. Do you think this is a suitable enhancement?

**Comment by a1ive** [comment]
https://github.com/a1ive/grub2-filemanager/blob/28a986c7f8e0383ec1b95de82e7c9bc6ffba8563/boot/grubfm/init.sh#L49-L53
Maybe you can do something in /boot/grubfm/config on you pendrive to skip grubfm.

**Comment by steve6375** [comment]
Does not quite work. Can you advise please?

![image](https://user-images.githubusercontent.com/1469350/74515110-d7ab9b00-4f05-11ea-8bc4-0acc6b1d67c8.png)

config
```
# user menu

grubfm_set --boot 1;

unset grubfm_default
set grubfm_timeout=3
if [ -f (${user})/boot/grubfm/default.txt ] ; then source (${user})/boot/grubfm/default.txt ; fi
echo Default=$grubfm_default Timeout=$grubfm_timeout
echo Press ESC for agFM
if [ -f "${grubfm_default}" ] ; then 
	if sleep -i -v $grubfm_timeout ; then set grubfm_file="${grubfm_default}" ; grubfm_open "${grubfm_default}" ; fi
fi
read
```

**Comment by a1ive** [comment]
config
```
# user menu
grubfm_set --boot 1;
configfile (${user})/boot/grubfm/test.cfg;
```
test.cfg
```
set timeout=15;
set default=0;

menuentry "winpe.iso" {
  map (hd0,1)/winpe.iso;
}

menuentry "grubfm" {
  grubfm;
}
```

**Comment by steve6375** [comment]
Thanks, but I wanted the user to be able to set any type of file as the default and then have grubfm open that file to present a menu of options like this
![image](https://user-images.githubusercontent.com/1469350/74518958-aaaeb680-4f0c-11ea-8da7-0dabbfac67b7.png)

**Comment by a1ive** [comment]
now `grubfm_open xxx` works

**Comment by steve6375** [comment]
Thanks - but same issue
![image](https://user-images.githubusercontent.com/1469350/74525489-1c8cfd00-4f19-11ea-9dc5-00dab15dc74f.png)

```
set grubfm_default=(hd0,msdos1)/_ISO/MAINMENU/FreeBSD-12.0-RELEASE-amd64-dvd1.iso
set timeout=2;
set default=0;

menuentry "winpe.iso" {
  grubfm_open ${grubfm_default}
  read
}

menuentry "grubfm" {
  grubfm;
}

```
Do I need to recompile grubfm ?

**Comment by a1ive** [comment]
Update grub2 and rebuild grubfm

**Comment by steve6375** [comment]
Thanks, working now ;-)
