### ISSUE TITLE
Default is changed when using a config file

### ISSUE THREAD

**Issue by steve6375** [a1ive/grub2-filemanager#99]
When using menu entries on startup, if default is set to 3 (agFM), then when agFM is launched, the default file entry is set to 3 instead of 0.

How to fix ?

![image](https://user-images.githubusercontent.com/1469350/74585658-e1e99a00-4fd6-11ea-897b-453f0de37d88.png)

\boot\grub\config
```
# user menu
grubfm_set --boot 1;
grubfm_set --hide 1;
if [ -f (${user})/boot/grubfm/startup_menu.txt ] ; then configfile (${user})/boot/grubfm/startup_menu.txt ; fi

```

\boot\grub\startup_menu.txt

```
set timeout=2;
set default=3;

(3 menu entries here)

menuentry "a1ive grub2 File Manager" {
export default=0
  grubfm
}

```

**Comment by a1ive** [comment]
You could a new menu xxx.cfg with only one command:
```
grubfm
```
and then run `configfile` to load it.

**Comment by steve6375** [comment]
No easy way then...
Maybe I always must make sure that  grubfm entry is 0  ;-)
